def Floor_Corner_Extended():
  global _hidden_verificationVariable=0
  step_count_477d2b75_14a1_4bd1_8ed8_9c73e5511d13 = 0.0
  thread Step_Counter_Thread_391a7927_408d_45dc_aa4e_0d8bac6dafc5():
    while (True):
      step_count_477d2b75_14a1_4bd1_8ed8_9c73e5511d13 = step_count_477d2b75_14a1_4bd1_8ed8_9c73e5511d13 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_391a7927_408d_45dc_aa4e_0d8bac6dafc5()
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(0)
  set_tcp(p[1.4000000000000001E-4,-0.01751,0.284,0.0,0.0,0.0])
  set_target_payload(10.800000, [-0.001000, -0.053000, 0.068000], [0.081228, 0.081228, 0.081228, 0.000000, 0.000000, 0.000000])
  set_gravity([0.0, 0.0, 9.82])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_safety_mode_transition_hardness(1)
  global robot_number=2
  global Point_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Point_2=p[0.0,0.0,0.0,0.0,0.0,0.0]
  # begin: URCap Installation Node
  #   Source: UR Connect, 1.13.79, Universal Robots
  #   Type: UR Connect
  myurRPC = rpc_factory("xmlrpc","http://127.0.0.1:40474")
  # end: URCap Installation Node
  # begin: URCap Installation Node
  #   Source: MachineLogic for Universal Robots, 3.1.7, Vention Inc.
  #   Type: MachineLogic for Universal Robots
  def waitForResponse(expected_response_vention, cname_vention):
  response_vention = socket_read_string(cname_vention,timeout=15)
  while response_vention != expected_response_vention:
  sleep(0.01)
  response_vention = socket_read_string(cname_vention,timeout=15)
  end
  sleep(0.01)
  sync()
  end
  def sendString(string_vention, expected_response_vention, cname_vention):
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  while response_vention != expected_response_vention:
  sleep(0.01)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  end
  sleep(0.01)
  sync()
  end
  def sendStringNAck(string_vention, expected_response_vention, cname_vention):
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  while(response_vention != expected_response_vention and response_vention != "nAck"):
  sleep(0.01)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received",blocking=True)
  end
  end
  sleep(0.01)
  sync()
  end
  def sendStringWithTimeout(string_vention, expected_response_vention, cname_vention):
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=10)
  if(response_vention == "nAck"):
  popup("nAck received"+string_vention)
  end
  sleep(0.01)
  sync()
  end
  def pollString(string_vention, expected_response_vention, cname_vention):
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  while response_vention != expected_response_vention:
  sleep(1)
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  end
  sleep(0.01)
  sync()
  end
  def sendVariable(var_vention, data_vention, expected_response_vention, cname_vention):
  socket_set_var(var_vention, data_vention, cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  while response_vention != expected_response_vention:
  sleep(0.01)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  end
  sleep(0.01)
  sync()
  end
  def intToString(integer_vention,cname_vention):
  stringFix=""
  multiplier_vention123=1
  if integer_vention<0:
  stringFix="-"
  multiplier_vention123=-1
  end
  socket_set_var("GetString",integer_vention*multiplier_vention123,cname_vention)
  string_vention=""
  while string_vention=="":
  sleep(0.01)
  string_vention=socket_read_string(cname_vention,timeout=15)
  end
  sleep(0.01)
  sync()
  string_vention=stringFix+string_vention
  return string_vention
  end
  string_vention=""
  isVentionMovementBusy = False
  isVentionParallelMovementSendingScript = False
  ventionThreadHandle = 1
  isVentionMovementBusyMachineMotion1 = False
  isVentionParallelMovementSendingScriptMachineMotion1 = False
  socket_vention = socket_open("192.168.3.52", 9999, "MachineMotion1")
  if socket_vention==False:
  popup("Check configuration, can't connect to MachineMotion")
  end
  waitForResponse("MachineMotion connection established", "MachineMotion1")
  sendString("isReady", "MachineMotion isReady = true", "MachineMotion1")
  sendStringWithTimeout("setURCapVersion2", "setURCapVersion loaded", "MachineMotion1")
  sendString("SET speed_v2 1000000", "Ack", "MachineMotion1")
  sendString("SET acceleration_v2 100000", "Ack", "MachineMotion1")
  sendString("SET de_axis_1_microsteps_config 8", "Ack", "MachineMotion1")
  sendString("SET de_axis_1_mechanical_gain_config_v2 150000.0", "Ack", "MachineMotion1")
  sendString("SET de_axis_1_direction_config 1", "Ack", "MachineMotion1")
  sendString("SET de_axis_1_type_config Custom Actuator ", "Ack", "MachineMotion1")
  sendString("de_axis_1_config_exec", "Ack", "MachineMotion1")
  # end: URCap Installation Node
  # begin: URCap Installation Node
  #   Source: WireTank Serial, 4.9.0, WireTank, LLC
  #   Type: WireTank Serial
  WTSerialBridge = rpc_factory("xmlrpc","http://127.0.0.1:40511/RPC2")
  # end: URCap Installation Node
  global free_dr_already=  False  
  global freedrive_m_var=  False  
  global Waypoint_76_p=p[.886939072471, .356263001241, .442999104957, 2.316306590719, 2.057646408592, .074101958719]
  global Waypoint_76_q=[-3.2647881984118814, -1.2522049299371645, 1.5824044773896437, 0.9175786249801816, -0.008369636028316307, -1.3112608249927966]
  global Waypoint_50_p=p[-.568711442653, .230601791901, .220208834751, -1.519093932087, -.535128035721, .573965472012]
  global Waypoint_50_q=[-0.021522347127095998, -1.2794721287539979, 2.4323821703540247, 5.090870934515753, -2.2996109167682093, 1.533644199371338]
  global Waypoint_51_p=p[-.689649894186, .139001107022, .230693120258, -.852023156701, -1.645963115617, 1.645984943001]
  global Waypoint_51_q=[-1.1454814116107386, -1.5427037247321387, 2.8454700152026575, 4.979047852545538, -4.902958456669943, 1.5718834400177002]
  global Waypoint_52_p=p[-.160992057407, .970528182050, .722037363514, -.554955923310, .106486629259, .328544950173]
  global Waypoint_52_q=[-1.2978580633746546, -1.3217003357461472, 2.2583277861224573, 3.7025129038044433, -2.952825371419088, 0.9627944231033325]
  global Waypoint_53_p=p[-.157624488365, .513351401913, .815670293526, -.672704566373, -1.852329693545, -.055423312366]
  global Waypoint_53_q=[-2.7676661650287073, -1.8206430874266566, 2.312763277684347, 1.0122546392628173, -1.0765226523028772, -0.8102834860431116]
  global Waypoint_54_p=p[-.308528116178, .606080777007, .242371251996, -2.133736658076, .349438277129, 2.130953356703]
  global Waypoint_54_q=[-1.9617512861834925, -1.2994225782207032, 2.207935158406393, 0.745708628291748, 1.5955500602722168, 1.41863214969635]
  global Waypoint_65_p=p[-.850299549699, -.229060500451, .580194265918, -.066683564301, -1.566406749139, -.045536147896]
  global Waypoint_65_q=[0.11527767777442932, -1.206728772526123, 2.660132948552267, 3.2525827127644042, -4.69939905801882, -0.18521625200380498]
  global Waypoint_55_p=p[-.850295942693, .369353811615, .580190947871, -.066690142153, -1.566409865149, -.045506050424]
  global Waypoint_55_q=[-0.89636737505068, -1.198587493305542, 2.6061368624316614, 3.3119169908710937, -4.700617257748739, 0.826545238494873]
  global Waypoint_59_p=p[-.689650832419, .138973473550, .230700469426, -.851985360280, -1.645991124348, 1.645990580233]
  global Waypoint_59_q=[-1.1454528013812464, -1.5427289356342335, 2.8454795519458216, 4.979044186859884, -4.902960960065023, 1.5718833208084106]
  global Waypoint_71_p=p[-.289684660393, .534258475721, .757199031184, -.295236718653, -.653013693815, .389426431276]
  global Waypoint_71_q=[-1.3941848913775843, -1.6550847492613734, 2.7336130777942103, 4.156678839320801, -3.798194471989767, 1.7310842275619507]
  global Waypoint_58_p=p[.191120239889, .567518478899, .815512910186, -.135765364935, .396070873472, .208834263225]
  global Waypoint_58_q=[-1.651280705128805, -1.7712346516051234, 2.617981735860006, 3.3066598612019042, -2.656208101903097, 0.8563313484191895]
  global Waypoint_56_p=p[-.254568281661, .502958752129, 1.135400507516, -.261908057482, -.749714619963, 1.349050618455]
  global Waypoint_56_q=[-2.0344861189471644, -1.9012485943236292, 2.469647232686178, 2.2012061315723876, -1.1677187124835413, -0.5094392935382288]
  global Waypoint_57_p=p[-.009221327687, .593713365169, .505808930157, -1.424394189587, -2.344106819810, -.527597949261]
  global Waypoint_57_q=[-2.920837704335348, -1.9932075939574183, 2.3856611887561243, 0.6815890508839111, -0.5688460508929651, -1.1506975332843226]
  global Waypoint_67_p=p[-.339169194335, .114271165560, .051007401747, -.434162127311, 1.872717119498, -1.885153895998]
  global Waypoint_67_q=[-1.410516087208883, -0.9778240484050293, 2.47756010690798, -1.72361483196401, -0.3956816832171839, 1.808600902557373]
  global Waypoint_69_p=p[-.760826542313, -.049762698068, .082649581767, -1.026233921905, -1.612699318499, 1.547123897415]
  global Waypoint_69_q=[-0.22154647508730108, -1.118469015961029, 2.7561236063586634, -1.5568565337783475, -3.851987902318136, 1.559481143951416]
  global Waypoint_70_p=p[-.154414768496, .636923137577, .016979120256, -.302753655748, 1.486961848367, .122240024639]
  global Waypoint_70_q=[-1.1281922499286097, -1.0678585332683106, 2.4290812651263636, -2.7994214497008265, -1.6034835020648401, 1.7401196956634521]
  global Waypoint_49_p=p[.397354147848, .356263001249, .319808682466, 2.316306590727, 2.057646408591, .074101958728]
  global Waypoint_49_q=[-3.4579480330096644, -2.0568953953185023, 2.3266006151782435, -0.2270372670939942, -0.1993797461139124, -0.10534602800478154]
  global Waypoint_75_p=p[.886939072471, .356263001241, .442999104957, 2.316306590719, 2.057646408592, .074101958719]
  global Waypoint_75_q=[-3.2647881984118814, -1.2522049299371645, 1.5824044773896437, 0.9175786249801816, -0.008369636028316307, -1.3112608249927966]
  global Waypoint_46_p=p[.897631799353, .353934909904, .354805178378, 2.318109555057, 2.056931948624, .061383861333]
  global Waypoint_46_q=[-3.2637236754046843, -1.174605057840683, 1.6528332869159141, 1.0000695425220945, -0.0017340818988245132, -1.5358897417550086]
  global Waypoint_20_p=p[.833090611797, .298095916052, .522915034559, -2.069934341898, -1.817090229983, .262480162787]
  global Waypoint_20_q=[-3.3684676667627205, -1.191816195275802, 1.4015747865517827, 0.7519456332104983, -0.12742073350990069, -0.5504001287532203]
  global Waypoint_8_p=p[-.689650873132, .138963273545, .230691387978, -.851994598965, -1.645998530536, 1.646007616333]
  global Waypoint_8_q=[-0.9414032141314905, -1.501500443821289, 2.801856819783346, 4.981602895050802, -4.698942009602682, 1.571649193763733]
  global raa1_p=p[-.689643170661, .139073527807, .230690921608, -.852069296672, -1.645944888292, 1.645881185303]
  global raa1_q=[-1.1455705801593226, -1.5426994071206828, 2.8454588095294397, 4.979022520571508, -4.9029627482043665, 1.5718539953231812]
  global raa2_p=p[-.114157470946, .855108345894, .597477301975, -.505907028801, .325764798924, .388694870300]
  global raa2_q=[-1.2560303846942347, -1.339010552769043, 2.4151175657855433, 3.6540276247211914, -2.7377544085132044, 1.1360299587249756]
  global raa3_p=p[-.308547482234, .387797636904, .242407099860, 1.976327760240, .350206946999, -1.916000398832]
  global raa3_q=[-1.8931763807879847, -1.3096025747111817, 2.212959591542379, 0.7217818933674316, 1.639076590538025, 0.8125834465026855]
  global raa4_p=p[-.733576132099, .077690893520, .242409727900, 1.976419296976, .350069431278, -1.916084616091]
  global raa4_q=[-0.8909156958209437, -1.3431089532426377, 2.273750130330221, 0.7266384798237304, 1.5611975193023682, 1.8127720355987549]
  global Waypoint_23_p=p[-.540166575654, .215949141041, .034631452617, -1.505795438113, 1.057579835594, 1.573514753692]
  global Waypoint_23_q=[-0.46167117754091436, -1.1365486842444916, 2.508885685597555, 0.15223841249432368, 1.4952874183654785, 3.819530963897705]
  global Waypoint_24_p=p[-.308525559537, .606096497354, .242373144855, -2.133742737559, .349425192770, 2.130939839044]
  global Waypoint_24_q=[-1.8709262053119105, -1.2877716285041352, 2.192875687276022, 0.7510036665150146, 1.5878156423568726, 1.5091480016708374]
  global Waypoint_39_p=p[.397377312153, .356253310648, .319810281486, 2.316317670744, 2.057592854035, .074120023159]
  global Waypoint_39_q=[-3.4579551855670374, -2.0568958721556605, 2.3265963236438196, -0.22706706941638188, -0.19935590425600225, -0.10534030595888311]
  global Waypoint_37_p=p[.397366630181, .356258644196, .319813668943, 2.316299214281, 2.057614642521, .074125657910]
  global Waypoint_37_q=[-3.4579508940326136, -2.056904455224508, 2.3265963236438196, -0.2270481151393433, -0.19937020937074834, -0.10535222688783819]
  global Waypoint_15_p=p[-.157621040248, .513353603496, .815677694745, -.672699538592, -1.852318447516, -.055422773001]
  global Waypoint_15_q=[-2.770456854497091, -1.8207680187621058, 2.3065691629992884, 1.0170823770710449, -1.0767205397235315, -0.8071182409869593]
  global Waypoint_25_p=p[-.161036555831, .970524399959, .722042384791, -.554954311189, .106465018540, .328580879483]
  global Waypoint_25_q=[-1.3071630636798304, -1.3366777312806626, 2.2083633581744593, 3.7187773424335937, -2.9519384543048304, 0.9132363796234131]
  global Waypoint_72_p=p[-.289685725237, .534256396594, .757196155975, -.295237726329, -.653009715205, .389435972469]
  global Waypoint_72_q=[-1.394179646168844, -1.6550847492613734, 2.7336154619800013, 4.156686468715332, -3.7981911341296595, 1.731092095375061]
  global Waypoint_26_p=p[-.689650873132, .138963273545, .230691387978, -.851994598965, -1.645998530536, 1.646007616333]
  global Waypoint_26_q=[-0.9414032141314905, -1.501500443821289, 2.801856819783346, 4.981602895050802, -4.698942009602682, 1.571649193763733]
  global Waypoint_27_p=p[-.568724745609, .230601805298, .220208295176, -1.519097711196, -.535155391172, .573964121010]
  global Waypoint_27_q=[-0.04883271852602178, -1.2753942471793671, 2.4771457354175013, 5.041022258787908, -2.326899592076437, 1.532160997390747]
  global Waypoint_28_p=p[-.568724745609, .230601805298, .220208295176, -1.519097711196, -.535155391172, .573964121010]
  global Waypoint_28_q=[-0.04883271852602178, -1.2753942471793671, 2.4771457354175013, 5.041022258787908, -2.326899592076437, 1.532160997390747]
  global Waypoint_29_p=p[-.689650873132, .138963273545, .230691387978, -.851994598965, -1.645998530536, 1.646007616333]
  global Waypoint_29_q=[-0.9414032141314905, -1.501500443821289, 2.801856819783346, 4.981602895050802, -4.698942009602682, 1.571649193763733]
  global Waypoint_30_p=p[-.853851193668, .133266829906, .060418082908, -.274178222953, -2.359710051999, .046821166283]
  global Waypoint_30_q=[-0.608560864125387, -1.0122360748103638, 2.787060801182882, 3.7283646303364257, -4.940747324620382, 0.3777344226837158]
  global Waypoint_31_p=p[-.979398188272, -.259625449453, .211289397035, -.673010443572, -1.459355862765, -.640164958946]
  global Waypoint_31_q=[0.36968713998794556, -0.5732358259013672, 2.138303581868307, 3.1253925996967773, -4.70385724702944, -1.2100523153888147]
  global Waypoint_32_p=p[-.826865752305, .369357632284, .043113676955, .574997346548, -1.492225541214, .597128135378]
  global Waypoint_32_q=[-1.0355513731585901, -0.33930082738909917, 2.126244846974508, 2.9386045175739746, -4.711197797452108, 1.7860286235809326]
  global Waypoint_33_p=p[-.689650873132, .138963273545, .230691387978, -.851994598965, -1.645998530536, 1.646007616333]
  global Waypoint_33_q=[-0.9414032141314905, -1.501500443821289, 2.801856819783346, 4.981602895050802, -4.698942009602682, 1.571649193763733]
  global Waypoint_73_p=p[-.289671192632, .534275423553, .757232902417, -.295189983811, -.652980753171, .389398176275]
  global Waypoint_73_q=[-1.39418870607485, -1.65509094814443, 2.7335642019854944, 4.156684561366699, -3.7981610933886927, 1.731088399887085]
  global Waypoint_16_p=p[.191112811238, .567512170908, .815514010937, -.135771161622, .396053809900, .208825693369]
  global Waypoint_16_q=[-1.6536315123187464, -1.762029310266012, 2.6225650946246546, 3.2891055780598144, -2.6549678484546106, 0.8520665764808655]
  global Waypoint_17_p=p[-.254565633623, .502963426820, 1.135401557820, -.261910507478, -.749716086887, 1.349041636154]
  global Waypoint_17_q=[-2.035229508076803, -1.8928028545775355, 2.468372408543722, 2.19391576826062, -1.167032543812887, -0.5091407934771937]
  global Waypoint_18_p=p[-.009208376822, .593717720951, .505810027228, -1.424406033077, -2.344120510145, -.527630245278]
  global Waypoint_18_q=[-2.9172328154193323, -1.9945279560484828, 2.3804522196399134, 0.6930715280720214, -0.5671199003802698, -1.1566088835345667]
  global Waypoint_38_p=p[.397379749540, .356252016937, .319817140705, 2.316310534508, 2.057580214841, .074134378577]
  global Waypoint_38_q=[-3.457958761845724, -2.0569073162474574, 2.3265913168536585, -0.22705944002185063, -0.19935638109316045, -0.10534793535341436]
  global Waypoint_40_p=p[.360688403366, .270119715397, .646144746546, .057805349154, 2.125995180379, 2.134053153683]
  global Waypoint_40_q=[-3.4579489866839808, -2.0569035015501917, 2.3265796343432825, -0.22706706941638188, -0.1993501822101038, -0.10534793535341436]
  global Waypoint_2_p=p[-.548957282596, .386284559177, .143710178207, 1.570800598292, -.000025190822, .000004803470]
  global Waypoint_2_q=[-1.0516188780414026, -1.010990933781006, 2.1562450567828577, -1.143702046280243, -1.0526168982135218, -0.0017235914813440445]
  global r1_ek_oldhome_p=p[.397380247322, .356253634699, .319820846021, 2.316316320871, 2.057594704604, .074118471609]
  global r1_ek_oldhome_q=[-3.457949940358297, -2.056894441644186, 2.32658034959902, -0.2270551484874268, -0.19935208955873662, -0.10533696809877569]
  global r1_ek_extrude_p=p[.454852104155, .405448828659, .064015413765, 2.316807606413, 2.051392071696, .076664825947]
  global r1_ek_extrude_q=[-3.274653975163595, -1.5604325172356148, 2.467809502278463, -0.34438879907641606, -0.014281574879781544, -0.6303489843951624]
  global r1_ek_front_p=p[.439064809878, .405452261046, .065996139932, 2.316843937268, 2.051427632497, .076607106393]
  global r1_ek_front_q=[-3.280560557042257, -1.6287623844542445, 2.502561871205465, -0.47416289270434575, -0.019731823598043263, -0.4669149557696741]
  global r1_ek_middle_p=p[.419010105608, .404850828431, .065994665459, 2.309574128677, 2.044678176343, .089098333896]
  global r1_ek_middle_q=[-3.290863100682394, -1.70143522838735, 2.548208538685934, -0.589385525589325, -0.029501263295308888, -0.3372734228717249]
  global r1_ek_middle2_p=p[.417011768852, .405435328663, .065002627117, 2.316867113472, 2.051334925313, .076628493429]
  global r1_ek_middle2_q=[-3.289830032979147, -1.6934038601317347, 2.5445857683764856, -0.579618052845337, -0.028589550648824513, -0.33885270753969365]
  global r1_ek_bottom_p=p[.413071667620, .405431286494, .067999701073, 2.316819721954, 2.051304037200, .076688572349]
  global r1_ek_bottom_q=[-3.2916205565081995, -1.708447118798727, 2.5485368410693567, -0.5849895042232056, -0.03033763567079717, -0.32244998613466436]
  global r1_ek_end_p=p[.389998638281, .405443674081, .068004818811, 2.316851991921, 2.051367741778, .076612018685]
  global r1_ek_end_q=[-3.3030064741717737, -1.7640062771239222, 2.5831297079669397, -0.63420523822818, -0.04154044786562139, -0.2521465460406702]
  global r2_ek_oldhome_p=p[.397380247322, .356253634699, .319820846021, 2.316316320871, 2.057594704604, .074118471609]
  global r2_ek_oldhome_q=[-3.461132842686933, -2.062320779349874, 2.32916033290004, -0.21924456446492258, -0.20097883707844666, -0.11039879152527199]
  global r2_ek_extrude_p=p[.612885745678, .429305279732, .100477107124, 2.149994969793, 2.225764025207, .087353352584]
  global r2_ek_extrude_q=[-3.199475796455825, -1.4862854517875999, 2.263543898005424, -0.6928175084157413, -0.09183293866530295, -0.15653548683830643]
  global r2_ek_front_p=p[.556405415915, .429305279815, .076984362723, -2.170411249256, -2.268200695165, -.015853660170]
  global r2_ek_front_q=[-3.2029012478485694, -1.4943971905029905, 2.3176866046272355, -0.727203417516419, -0.10461513056100813, -0.1013922369747533]
  global r2_ek_middle_p=p[.550033970532, .429305279917, .076253920653, -2.170411249261, -2.268200695170, -.015853660159]
  global r2_ek_middle_q=[-3.2036200175167613, -1.5006788185274456, 2.326226188945654, -0.730095076239345, -0.10533288811000929, -0.10075548926859312]
  global r2_ek_bottom_p=p[.546594660555, .429305280025, .080868477599, -2.170411249265, -2.268200695174, -.015853660149]
  global r2_ek_bottom_q=[-3.204010221105431, -1.5099366263094405, 2.3272215014458872, -0.722096275899732, -0.10572512264357048, -0.10049057923478166]
  global r2_ek_end_p=p[.537335106646, .429305280055, .080868477459, -2.170411249266, -2.268200695175, -.015853660146]
  global r2_ek_end_q=[-3.205098875769389, -1.5204959829395506, 2.3387656715508855, -0.724001524008818, -0.10681294496314919, -0.09956563917089412]
  global r3_ek_oldhome_p=p[.397385850131, .356252441346, .369809999696, 2.316320575836, 2.057576093691, .074125563417]
  global r3_ek_oldhome_q=[-3.4600108097540825, -2.084533794186367, 2.2686976909438377, -0.1444297831854957, -0.20178034518575938, -0.10248789488416588]
  global r3_ek_extrude_p=p[.612883684377, .429310301838, .149999999683, 2.149962295817, 2.225777492182, .087374550826]
  global r3_ek_extrude_q=[-3.1980123446153748, -1.538400201434774, 2.229744902146236, -0.6115506790497731, -0.09278008251792791, -0.15193191663383665]
  global r3_ek_front_p=p[.612883684377, .429310301838, .149999999683, 2.149962295817, 2.225777492182, .087374550826]
  global r3_ek_front_q=[-3.1980123446153748, -1.538400201434774, 2.229744902146236, -0.6115506790497731, -0.09278008251792791, -0.15193191663383665]
  global r3_ek_middle_p=p[.612883684377, .429310301838, .149999999683, 2.149962295817, 2.225777492182, .087374550826]
  global r3_ek_middle_q=[-3.1980123446153748, -1.538400201434774, 2.229744902146236, -0.6115506790497731, -0.09278008251792791, -0.15193191663383665]
  global r3_ek_bottom_p=p[.612883684377, .429310301838, .149999999683, 2.149962295817, 2.225777492182, .087374550826]
  global r3_ek_bottom_q=[-3.1980123446153748, -1.538400201434774, 2.229744902146236, -0.6115506790497731, -0.09278008251792791, -0.15193191663383665]
  global r3_ek_end_p=p[.612883684377, .429310301838, .149999999683, 2.149962295817, 2.225777492182, .087374550826]
  global r3_ek_end_q=[-3.1980123446153748, -1.538400201434774, 2.229744902146236, -0.6115506790497731, -0.09278008251792791, -0.15193191663383665]
  global r4_ek_oldhome_p=p[.397380247322, .356253634699, .319820846021, 2.316316320871, 2.057594704604, .074118471609]
  global r4_ek_oldhome_q=[-3.4680860338785493, -2.070376223306912, 2.3329367157510497, -0.22828162349163783, -0.20619604348947362, -0.09694130604598783]
  global r4_ek_extrude_p=p[.458670548589, .429305279741, .125141489362, 2.149994969793, 2.225764025207, .087353352584]
  global r4_ek_extrude_q=[-3.224306558956634, -1.7135315940479465, 2.43410270276974, -0.6768839938806144, -0.1154143142053492, -0.11562209601533713]
  global r4_ek_front_p=p[.420084046436, .429305279533, .122370065986, -2.206701899775, -2.177374452500, .052747240372]
  global r4_ek_front_q=[-3.2223885287117087, -1.7265329174617632, 2.4434355314143925, -0.6644243149558609, -0.06512925128431313, -0.01659929377642566]
  global r4_ek_middle_p=p[.385663706386, .429305279588, .119862350556, -2.206701899778, -2.177374452500, .052747240377]
  global r4_ek_middle_q=[-3.2295441306515738, -1.774240686665987, 2.4822688267544946, -0.6583601229072489, -0.07232201786773373, -0.0137735297523216]
  global r4_ek_bottom_p=p[.385663706260, .429305279599, .122809894660, -2.206701899778, -2.177374452501, .052747240377]
  global r4_ek_bottom_q=[-3.2295577467539287, -1.7778480193330992, 2.4794176409730713, -0.6518633442593682, -0.07233077879629679, -0.013811892538432069]
  global r4_ek_end_p=p[.366757227289, .429305279628, .122809894538, -2.206701899780, -2.177374452501, .052747240380]
  global r4_ek_end_q=[-3.2341047638544715, -1.8072551968371293, 2.4987903200913473, -0.6435011221874376, -0.07689850609233773, -0.01212997029934737]
  global oldhome_p=p[.397683836105, .356251384911, .315246899233, 2.316304177919, 2.057561756051, .074146544723]
  global oldhome_q=[-3.457960907612936, -2.0569125614561976, 2.326589886342184, -0.22707636774096684, -0.19935208955873662, -0.10534269014467412]
  global Waypoint_34_p=p[.695155464390, .367451880816, .502522491683, 2.093108370749, 1.857548644474, .308841595089]
  global Waypoint_34_q=[-3.249415699635641, -1.9387923679747523, 2.3226097265826624, 3.981850786800049, -0.05697328249086553, 1.5286790132522583]
  global Waypoint_35_p=p[.687527620967, .415165960724, .537921070000, 2.127101811831, 1.929915403723, .470130777221]
  global Waypoint_35_q=[-3.249424997960226, -1.9387947521605433, 2.32263428369631, 3.9818588930317382, -6.198007937763826, 1.5286580324172974]
  global Waypoint_36_p=p[-.693756081485, .141369193308, .218584735520, -.851978179689, -1.646001533937, 1.646008371360]
  global Waypoint_36_q=[-1.1533568541156214, -1.4924076360515137, 2.8518698851214808, 4.922323781042852, -4.910887185727255, 1.5719373226165771]
  def calculate_point_to_move_towards(feature, direction, position_distance):
    local posDir=[direction[0], direction[1], direction[2]]
    if (norm(posDir) < 1e-6):
      return get_target_waypoint()
    end
    local direction_vector_normalized=normalize(posDir)
    local displacement_pose=p[direction_vector_normalized[0] * position_distance,direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,0,0,0]
    local wanted_displacement_in_base_frame=pose_sub(pose_trans(feature, displacement_pose), feature)
    return pose_add(get_target_waypoint(), wanted_displacement_in_base_frame)
  end
  global Waypoint_4_p=p[-.658264763546, .299530128456, .030909835036, .426821001551, -1.621505068649, .437070885767]
  global Waypoint_4_q=[-1.350241486226217, -0.9702387017062684, 2.492185179387228, -1.7834822140135707, -0.33723670641054326, 1.8489984273910522]
  global Waypoint_13_p=p[-.343952006273, .632142227752, .615174722549, -.025948978133, -.008794819136, -.567469912202]
  global Waypoint_13_q=[-1.350241486226217, -0.9702451390079041, 2.492171827946798, -3.0669099293150843, 1.575993537902832, 2.355180025100708]
  global Waypoint_14_p=p[-.343952006273, .632142227752, .615174722549, -.025948978133, -.008794819136, -.567469912202]
  global Waypoint_14_q=[-1.350241486226217, -0.9702451390079041, 2.492171827946798, -3.0669099293150843, 1.575993537902832, 2.355180025100708]
  global Waypoint_41_p=p[.392127936214, .533269017847, .644148583936, .057822570580, 2.125982462550, 2.134033989912]
  global Waypoint_41_q=[-3.4579578081714075, -2.0569120846190394, 2.3265841642962855, -0.22706885755572515, -0.1993349234210413, -0.10534984270204717]
  def move_path_3right():
    $ 136 "move_path_3right" "noBreak"
    $ 137 "'this is the path for Down, Over, then Back Around'"
    # 'this is the path for Down, Over, then Back Around'
    $ 138 "Comment"
    # Comment
    $ 147 "align_ready_for_welding()"
    align_ready_for_welding()
    $ 148 "Comment"
    # Comment
    $ 149 "p1≔pathturn[0]"
    global p1=pathturn[0]
    $ 150 "p2≔pathturn[1]"
    global p2=pathturn[1]
    $ 151 "p4≔pathturn[2]"
    global p4=pathturn[2]
    $ 152 "p5≔pathturn[3]"
    global p5=pathturn[3]
    $ 153 "pa1≔p[p1[0]+0.05,p1[1]+0.05,p1[2],p1[3],p1[4],p1[5]]"
    global pa1=p[p1[0]+0.05,p1[1]+0.05,p1[2],p1[3],p1[4],p1[5]]
    $ 154 "liftcolumnup"
    $ 155 "liftcolumnz≔liftcolumnzneeded"
    global liftcolumnz=liftcolumnzneeded
    $ 156 "If liftcolumnz>0"
    if (liftcolumnz>0):
      # begin: URCap Program Node
      #   Source: MachineLogic for Universal Robots, 3.1.7, Vention Inc.
      #   Type: MachineLogic for Universal Robots
      $ 157 "MachineLogic Move to Position"
      while isVentionMovementBusyMachineMotion1==True:
      sleep(0.05)
      end
      if(isVentionMovementBusyMachineMotion1 == False):
      isVentionMovementBusyMachineMotion1 = True
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      while(temp_estop_var_vention=="estop/status true"):
      if temp_estop_var_vention=="estop/status true":
      sendStringWithTimeout("estop/systemreset/request","Ack estop/systemreset/request;","MachineMotion1")
      end
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      if temp_estop_var_vention=="estop/status true":
      popup("MachineMotion in estop, make sure you have all emergency modules released manually. If you continue the system will try to reset MachineMotion automatically.",blocking=True)
      end
      end
      else:
      popup("resource is being used already: MachineMotion1")
      halt
      end
      sendString("SET speed_v2 3000000.000", "Ack", "MachineMotion1")
      sendString("SET acceleration_v2 50000.000", "Ack", "MachineMotion1")
      string_vention=intToString(liftcolumnz*1000,"MachineMotion1")
      sendString("SET de_move_abs_1 "+string_vention, "Ack", "MachineMotion1")
      sendString("de_move_abs_exec", "Ack", "MachineMotion1")
      isVentionParallelMovementSendingScriptMachineMotion1 = False
      pollString("isMotionCompleted", "MachineMotion isMotionCompleted = true", "MachineMotion1")
      isVentionMovementBusyMachineMotion1 = False
      sleep(0.03)
      # end: URCap Program Node
    end
    $ 158 "MoveJ"
    $ 159 "pa1" "breakAfter"
    movej(pa1, a=1.3962634015954636, v=0.3490658503988659)
    $ 160 "MoveL"
    $ 161 "p1" "breakAfter"
    movel(p1, a=0.2, v=0.05)
    $ 162 "Wait: 8.0"
    sleep(8.0)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 163 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 164 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    $ 165 "Wait: 1.0"
    sleep(1.0)
    $ 167 "Set DO[0]=On"
    set_standard_digital_out(0, True)
    $ 168 "MoveL"
    $ 169 "p2" "breakAfter"
    movel(p2, a=0.1, v=0.01)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 170 "Serial Bridge uR0"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,48], False)
    # end: URCap Program Node
    $ 171 "Wait: 0.5"
    sleep(0.5)
    $ 172 "Set DO[0]=Off"
    set_standard_digital_out(0, False)
    $ 173 "MoveL"
    $ 174 "p4" "breakAfter"
    movel(p4, a=0.01, v=0.12)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 175 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 176 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    $ 177 "Wait: 1.0"
    sleep(1.0)
    $ 179 "Set DO[0]=On"
    set_standard_digital_out(0, True)
    $ 180 "MoveL"
    $ 181 "p5" "breakAfter"
    movel(p5, a=0.1, v=0.01)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 182 "Serial Bridge uR0"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,48], False)
    # end: URCap Program Node
    $ 183 "Wait: 2.0"
    sleep(2.0)
    $ 184 "Set DO[0]=Off"
    set_standard_digital_out(0, False)
    $ 185 "Comment"
    # Comment
    $ 186 "pret1≔p[p5[0]+.1,p5[1],p5[2],p5[3],p5[4],p5[5]]"
    global pret1=p[p5[0]+.1,p5[1],p5[2],p5[3],p5[4],p5[5]]
    $ 187 "p_1≔pathturn[4]"
    global p_1=pathturn[4]
    $ 188 "p_2≔pathturn[5]"
    global p_2=pathturn[5]
    $ 189 "p_3≔pathturn[6]"
    global p_3=pathturn[6]
    $ 190 "p_4≔pathturn[7]"
    global p_4=pathturn[7]
    $ 191 "p_5≔pathturn[8]"
    global p_5=pathturn[8]
    $ 192 "p_preheat≔p[p_3[0]+.01,p_3[1],p_3[2],p_3[3],p_3[4],p_3[5]]"
    global p_preheat=p[p_3[0]+.01,p_3[1],p_3[2],p_3[3],p_3[4],p_3[5]]
    $ 193 "p_pre_ret≔p[p_1[0]+.03,p_1[1]+.03,p_1[2],p_1[3],p_1[4],p_1[5]]"
    global p_pre_ret=p[p_1[0]+.03,p_1[1]+.03,p_1[2],p_1[3],p_1[4],p_1[5]]
    $ 194 "p_pre_ret2≔p[p_3[0]+.1,p_3[1],p_3[2],p_3[3],p_3[4],p_3[5]]"
    global p_pre_ret2=p[p_3[0]+.1,p_3[1],p_3[2],p_3[3],p_3[4],p_3[5]]
    $ 195 "'twist'"
    # 'twist'
    $ 196 "MoveJ"
    $ 197 "pret1" "breakAfter"
    movej(pret1, a=1.3962634015954636, v=1.3962634015954636)
    $ 198 "Waypoint_8" "breakAfter"
    movej(get_inverse_kin(Waypoint_8_p, qnear=Waypoint_8_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 200 "MoveJ"
    $ 201 "raa1" "breakAfter"
    movej(get_inverse_kin(raa1_p, qnear=raa1_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 202 "raa2" "breakAfter"
    movej(get_inverse_kin(raa2_p, qnear=raa2_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 203 "raa3" "breakAfter"
    movej(get_inverse_kin(raa3_p, qnear=raa3_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 204 "raa4" "breakAfter"
    movej(get_inverse_kin(raa4_p, qnear=raa4_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 206 "If liftcolumnz≠0.0"
    if (liftcolumnz != 0.0):
      # begin: URCap Program Node
      #   Source: MachineLogic for Universal Robots, 3.1.7, Vention Inc.
      #   Type: MachineLogic for Universal Robots
      $ 207 "MachineLogic Homing"
      while isVentionMovementBusyMachineMotion1==True:
      sleep(0.05)
      end
      if(isVentionMovementBusyMachineMotion1 == False):
      isVentionMovementBusyMachineMotion1 = True
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      while(temp_estop_var_vention=="estop/status true"):
      if temp_estop_var_vention=="estop/status true":
      sendStringWithTimeout("estop/systemreset/request","Ack estop/systemreset/request;","MachineMotion1")
      end
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      if temp_estop_var_vention=="estop/status true":
      popup("MachineMotion in estop, make sure you have all emergency modules released manually. If you continue the system will try to reset MachineMotion automatically.",blocking=True)
      end
      end
      else:
      popup("resource is being used already: MachineMotion1")
      halt
      end
      isVentionMovementBusyMachineMotion1 = True
      sendString("im_home_axis_1", "MachineMotion im_home_axis_1 = completed", "MachineMotion1")
      isVentionMovementBusyMachineMotion1 = False
      sendString("SET im_set_encoder_pos_aux_1 0.000", "Ack", "MachineMotion1")
      isVentionMovementBusyMachineMotion1 = False
      sleep(0.03)
      # end: URCap Program Node
    end
    $ 208 "'preheat'"
    # 'preheat'
    $ 211 "MoveL"
    $ 212 "p_pre_ret2" "breakAfter"
    movel(p_pre_ret2, a=1.2, v=0.25)
    $ 213 "p_preheat" "breakAfter"
    movel(p_preheat, a=1.2, v=0.25)
    $ 214 "Wait: 6.0"
    sleep(6.0)
    $ 215 "MoveL"
    $ 216 "p_pre_ret2" "breakAfter"
    movel(p_pre_ret2, a=1.2, v=0.25)
    $ 217 "p_pre_ret" "breakAfter"
    movel(p_pre_ret, a=1.2, v=0.25)
    $ 218 "Set"
    set_tcp(p[0.00451,-0.328,0.105,1.2092,-1.2092,1.2092])
    $ 219 "MoveL"
    $ 220 "p_1" "breakAfter"
    movel(p_1, a=1.2, v=0.05)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 221 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 222 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    $ 223 "Wait: 1.0"
    sleep(1.0)
    $ 224 "Set DO[0]=On"
    set_standard_digital_out(0, True)
    $ 226 "Wait: 1.0"
    sleep(1.0)
    $ 227 "MoveL"
    $ 228 "p_2" "breakAfter"
    movel(p_2, a=1.2, v=0.01)
    $ 229 "MoveP"
    $ 230 "CircleMove"
    $ 231 "p_3" "noBreak"
    
    $ 232 "p_4" "breakAfter"
    movec(p_3, p_4, a=0.01, v=5.0E-4, r=0.0, mode=1)
    $ 233 "MoveL"
    $ 234 "p_5" "breakAfter"
    movel(p_5, a=1.2, v=0.012)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 235 "Serial Bridge uR0"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,48], False)
    # end: URCap Program Node
    $ 236 "Wait: 2.0"
    sleep(2.0)
    $ 237 "Set DO[0]=Off"
    set_standard_digital_out(0, False)
    $ 238 "MoveL"
    $ 239 "Waypoint_23" "breakAfter"
    movel(Waypoint_23_p, a=1.2, v=0.25)
    $ 240 "MoveJ"
    $ 241 "Waypoint_24" "breakAfter"
    movej(get_inverse_kin(Waypoint_24_p, qnear=Waypoint_24_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 242 "Waypoint_39" "breakAfter"
    movej(get_inverse_kin(Waypoint_39_p, qnear=Waypoint_39_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 243 "'above waypoint is home'"
    # 'above waypoint is home'
  end
  def move_path_3left():
    $ 244 "move_path_3left" "noBreak"
    $ 245 "'this is the path for Down, Over, then Back Around'"
    # 'this is the path for Down, Over, then Back Around'
    $ 246 "Comment"
    # Comment
    $ 247 "MoveJ"
    $ 248 "Waypoint_37" "breakAfter"
    movej(get_inverse_kin(Waypoint_37_p, qnear=Waypoint_37_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 249 "'above point is home'"
    # 'above point is home'
    $ 250 "liftcolumnup"
    $ 251 "liftcolumnz≔liftcolumnzneeded"
    global liftcolumnz=liftcolumnzneeded
    $ 252 "If liftcolumnz>0"
    if (liftcolumnz>0):
      # begin: URCap Program Node
      #   Source: MachineLogic for Universal Robots, 3.1.7, Vention Inc.
      #   Type: MachineLogic for Universal Robots
      $ 253 "MachineLogic Move to Position"
      while isVentionMovementBusyMachineMotion1==True:
      sleep(0.05)
      end
      if(isVentionMovementBusyMachineMotion1 == False):
      isVentionMovementBusyMachineMotion1 = True
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      while(temp_estop_var_vention=="estop/status true"):
      if temp_estop_var_vention=="estop/status true":
      sendStringWithTimeout("estop/systemreset/request","Ack estop/systemreset/request;","MachineMotion1")
      end
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      if temp_estop_var_vention=="estop/status true":
      popup("MachineMotion in estop, make sure you have all emergency modules released manually. If you continue the system will try to reset MachineMotion automatically.",blocking=True)
      end
      end
      else:
      popup("resource is being used already: MachineMotion1")
      halt
      end
      sendString("SET speed_v2 3000000.000", "Ack", "MachineMotion1")
      sendString("SET acceleration_v2 50000.000", "Ack", "MachineMotion1")
      string_vention=intToString(liftcolumnz*1000,"MachineMotion1")
      sendString("SET de_move_abs_1 "+string_vention, "Ack", "MachineMotion1")
      sendString("de_move_abs_exec", "Ack", "MachineMotion1")
      isVentionParallelMovementSendingScriptMachineMotion1 = False
      pollString("isMotionCompleted", "MachineMotion isMotionCompleted = true", "MachineMotion1")
      isVentionMovementBusyMachineMotion1 = False
      sleep(0.03)
      # end: URCap Program Node
    end
    $ 254 "Waypoint_15" "breakAfter"
    movej(get_inverse_kin(Waypoint_15_p, qnear=Waypoint_15_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 255 "Waypoint_25" "breakAfter"
    movej(get_inverse_kin(Waypoint_25_p, qnear=Waypoint_25_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 256 "Waypoint_72" "breakAfter"
    movej(get_inverse_kin(Waypoint_72_p, qnear=Waypoint_72_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 257 "Waypoint_26" "breakAfter"
    movej(get_inverse_kin(Waypoint_26_p, qnear=Waypoint_26_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 258 "Waypoint_27" "breakAfter"
    movej(get_inverse_kin(Waypoint_27_p, qnear=Waypoint_27_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 263 "Comment"
    # Comment
    $ 264 "p1≔pathturn[0]"
    global p1=pathturn[0]
    $ 265 "p2≔pathturn[1]"
    global p2=pathturn[1]
    $ 266 "p4≔pathturn[2]"
    global p4=pathturn[2]
    $ 267 "p5≔pathturn[3]"
    global p5=pathturn[3]
    $ 268 "pa1≔p[p1[0]+0.05,p1[1]-0.05,p1[2],p1[3],p1[4],p1[5]]"
    global pa1=p[p1[0]+0.05,p1[1]-0.05,p1[2],p1[3],p1[4],p1[5]]
    $ 269 "MoveJ"
    $ 270 "pa1" "breakAfter"
    movej(pa1, a=1.3962634015954636, v=1.0471975511965976)
    $ 271 "MoveL"
    $ 272 "p1" "breakAfter"
    movel(p1, a=0.1, v=0.05)
    $ 273 "Wait: 8.0"
    sleep(8.0)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 274 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 275 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    $ 276 "Wait: 1.0"
    sleep(1.0)
    $ 278 "Set DO[0]=On"
    set_standard_digital_out(0, True)
    $ 279 "MoveL"
    $ 280 "p2" "breakAfter"
    movel(p2, a=0.1, v=0.01)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 281 "Serial Bridge uR0"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,48], False)
    # end: URCap Program Node
    $ 282 "Wait: 0.5"
    sleep(0.5)
    $ 283 "Set DO[0]=Off"
    set_standard_digital_out(0, False)
    $ 284 "MoveL"
    $ 285 "p4" "breakAfter"
    movel(p4, a=0.01, v=0.12)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 286 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 287 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    $ 288 "Wait: 1.0"
    sleep(1.0)
    $ 290 "Set DO[0]=On"
    set_standard_digital_out(0, True)
    $ 291 "MoveL"
    $ 292 "p5" "breakAfter"
    movel(p5, a=0.1, v=0.01)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 293 "Serial Bridge uR0"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,48], False)
    # end: URCap Program Node
    $ 294 "Wait: 2.0"
    sleep(2.0)
    $ 295 "Set DO[0]=Off"
    set_standard_digital_out(0, False)
    $ 296 "Comment"
    # Comment
    $ 297 "pret1≔p[p5[0]+.1,p5[1],p5[2],p5[3],p5[4],p5[5]]"
    global pret1=p[p5[0]+.1,p5[1],p5[2],p5[3],p5[4],p5[5]]
    $ 298 "p_1≔pathturn[4]"
    global p_1=pathturn[4]
    $ 299 "p_2≔pathturn[5]"
    global p_2=pathturn[5]
    $ 300 "p_3≔pathturn[6]"
    global p_3=pathturn[6]
    $ 301 "p_4≔pathturn[7]"
    global p_4=pathturn[7]
    $ 302 "p_5≔pathturn[8]"
    global p_5=pathturn[8]
    $ 303 "p_preheat≔p[p_3[0]+.01,p_3[1],p_3[2],p_3[3],p_3[4],p_3[5]]"
    global p_preheat=p[p_3[0]+.01,p_3[1],p_3[2],p_3[3],p_3[4],p_3[5]]
    $ 304 "p_pre_ret≔p[p_1[0]+.03,p_1[1]-.03,p_1[2],p_1[3],p_1[4],p_1[5]]"
    global p_pre_ret=p[p_1[0]+.03,p_1[1]-.03,p_1[2],p_1[3],p_1[4],p_1[5]]
    $ 305 "p_pre_ret2≔p[p_3[0]+.03,p_3[1],p_3[2],p_3[3],p_3[4],p_3[5]]"
    global p_pre_ret2=p[p_3[0]+.03,p_3[1],p_3[2],p_3[3],p_3[4],p_3[5]]
    $ 306 "MoveJ"
    $ 307 "pret1" "breakAfter"
    movej(pret1, a=1.3962634015954636, v=1.3962634015954636)
    $ 308 "Waypoint_28" "breakAfter"
    movej(get_inverse_kin(Waypoint_28_p, qnear=Waypoint_28_q), a=1.3962634015954636, v=1.3962634015954636)
    $ 309 "If liftcolumnz≠0.0"
    if (liftcolumnz != 0.0):
      # begin: URCap Program Node
      #   Source: MachineLogic for Universal Robots, 3.1.7, Vention Inc.
      #   Type: MachineLogic for Universal Robots
      $ 310 "MachineLogic Homing"
      while isVentionMovementBusyMachineMotion1==True:
      sleep(0.05)
      end
      if(isVentionMovementBusyMachineMotion1 == False):
      isVentionMovementBusyMachineMotion1 = True
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      while(temp_estop_var_vention=="estop/status true"):
      if temp_estop_var_vention=="estop/status true":
      sendStringWithTimeout("estop/systemreset/request","Ack estop/systemreset/request;","MachineMotion1")
      end
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      if temp_estop_var_vention=="estop/status true":
      popup("MachineMotion in estop, make sure you have all emergency modules released manually. If you continue the system will try to reset MachineMotion automatically.",blocking=True)
      end
      end
      else:
      popup("resource is being used already: MachineMotion1")
      halt
      end
      isVentionMovementBusyMachineMotion1 = True
      sendString("im_home_axis_1", "MachineMotion im_home_axis_1 = completed", "MachineMotion1")
      isVentionMovementBusyMachineMotion1 = False
      sendString("SET im_set_encoder_pos_aux_1 0.000", "Ack", "MachineMotion1")
      isVentionMovementBusyMachineMotion1 = False
      sleep(0.03)
      # end: URCap Program Node
    end
    $ 311 "'now go into the ccw weld position'"
    # 'now go into the ccw weld position'
    $ 312 "Waypoint_29" "breakAfter"
    movej(get_inverse_kin(Waypoint_29_p, qnear=Waypoint_29_q), a=1.3962634015954636, v=1.3962634015954636)
    $ 313 "Comment"
    # Comment
    $ 314 "Waypoint_30" "breakAfter"
    movej(get_inverse_kin(Waypoint_30_p, qnear=Waypoint_30_q), a=1.3962634015954636, v=1.3962634015954636)
    $ 315 "Waypoint_31" "breakAfter"
    movej(get_inverse_kin(Waypoint_31_p, qnear=Waypoint_31_q), a=1.3962634015954636, v=1.3962634015954636)
    $ 324 "MoveL"
    $ 325 "p_pre_ret" "breakAfter"
    movel(p_pre_ret, a=1.2, v=0.25)
    $ 326 "p_pre_ret2" "breakAfter"
    movel(p_pre_ret2, a=1.2, v=0.25)
    $ 327 "p_preheat" "breakAfter"
    movel(p_preheat, a=1.2, v=0.25)
    $ 328 "Wait: 6.0"
    sleep(6.0)
    $ 329 "MoveL"
    $ 330 "p_pre_ret2" "breakAfter"
    movel(p_pre_ret2, a=1.2, v=0.25)
    $ 331 "p_pre_ret" "breakAfter"
    movel(p_pre_ret, a=1.2, v=0.25)
    $ 332 "Set"
    set_tcp(p[0.00451,-0.328,0.105,1.2092,-1.2092,1.2092])
    $ 333 "MoveL"
    $ 334 "p_1" "breakAfter"
    movel(p_1, a=0.1, v=0.05)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 335 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 336 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    $ 337 "Wait: 1.0"
    sleep(1.0)
    $ 338 "Set DO[0]=On"
    set_standard_digital_out(0, True)
    $ 340 "Wait: 1.0"
    sleep(1.0)
    $ 341 "MoveL"
    $ 342 "p_2" "breakAfter"
    movel(p_2, a=1.2, v=0.01)
    $ 343 "MoveP"
    $ 344 "CircleMove"
    $ 345 "p_3" "noBreak"
    
    $ 346 "p_4" "breakAfter"
    movec(p_3, p_4, a=0.01, v=5.0E-4, r=0.0, mode=1)
    $ 347 "MoveL"
    $ 348 "p_5" "breakAfter"
    movel(p_5, a=1.2, v=0.012)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 349 "Serial Bridge uR0"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,48], False)
    # end: URCap Program Node
    $ 350 "Wait: 2.0"
    sleep(2.0)
    $ 351 "Set DO[0]=Off"
    set_standard_digital_out(0, False)
    $ 356 "MoveJ"
    $ 357 "Waypoint_32" "breakAfter"
    movej(get_inverse_kin(Waypoint_32_p, qnear=Waypoint_32_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 358 "Waypoint_33" "breakAfter"
    movej(get_inverse_kin(Waypoint_33_p, qnear=Waypoint_33_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 359 "Waypoint_73" "breakAfter"
    movej(get_inverse_kin(Waypoint_73_p, qnear=Waypoint_73_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 360 "Comment"
    # Comment
    $ 361 "MoveJ"
    $ 362 "Waypoint_16" "breakAfter"
    movej(get_inverse_kin(Waypoint_16_p, qnear=Waypoint_16_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 363 "Waypoint_17" "breakAfter"
    movej(get_inverse_kin(Waypoint_17_p, qnear=Waypoint_17_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 364 "Waypoint_18" "breakAfter"
    movej(get_inverse_kin(Waypoint_18_p, qnear=Waypoint_18_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 365 "Waypoint_38" "breakAfter"
    movej(get_inverse_kin(Waypoint_38_p, qnear=Waypoint_38_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 366 "'above point is home'"
    # 'above point is home'
  end
  def Test_Teach_Position():
    $ 367 "Test_Teach_Position" "noBreak"
    $ 371 "MoveJ"
    $ 372 "Waypoint_40" "breakAfter"
    set_tcp(p[0.0,0.0,0.019,0.0,0.0,0.0])
    movej(get_inverse_kin(Waypoint_40_p, qnear=Waypoint_40_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 373 "'above waypoint is home'"
    # 'above waypoint is home'
    $ 374 "Waypoint_2" "breakAfter"
    set_tcp(p[0.0,0.0,0.019,0.0,0.0,0.0])
    movej(get_inverse_kin(Waypoint_2_p, qnear=Waypoint_2_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 375 "Set"
    set_tcp(p[1.4000000000000001E-4,-0.01751,0.284,0.0,0.0,0.0])
    $ 376 "freedrive_m_var≔ False "
    global freedrive_m_var=  False  
    $ 377 "freedrive_m_var≔ True "
    global freedrive_m_var=  True  
    $ 378 "Popup: Move the TCP to the top of the weld, then click 'Continue'"
    popup("Move the TCP to the top of the weld, then click 'Continue'", "Message", False, False, blocking=True)
    $ 379 "tcp_pose_top≔get_actual_tcp_pose()"
    global tcp_pose_top= get_actual_tcp_pose ()
    $ 380 "Popup: Move the TCP to the corner of the tank, then click 'Continue'"
    popup("Move the TCP to the corner of the tank, then click 'Continue'", "Message", False, False, blocking=True)
    $ 381 "tcp_pose≔get_actual_tcp_pose()"
    global tcp_pose= get_actual_tcp_pose ()
    $ 382 "freedrive_m_var≔ False "
    global freedrive_m_var=  False  
    $ 383 "Wait: 0.25"
    sleep(0.25)
    $ 384 "sync()"
    sync()
  end
  def align_tcp_left():
    $ 385 "align_tcp_left" "noBreak"
    $ 386 "'this program aligns the tcp parallel to the y direction'"
    # 'this program aligns the tcp parallel to the y direction'
    $ 387 "cp≔get_actual_tcp_pose()"
    global cp= get_actual_tcp_pose ()
    $ 388 "aligned_y_pose≔p[cp[0],cp[1],cp[2],1.570796,0,0]"
    global aligned_y_pose=p[cp[0],cp[1],cp[2],1.570796,0,0]
    $ 389 "MoveJ"
    $ 390 "aligned_y_pose" "breakAfter"
    movej(aligned_y_pose, a=1.3962634015954636, v=1.0471975511965976)
  end
  def extrude_knife3():
    $ 391 "extrude_knife3" "noBreak"
    $ 392 "pre program stuff"
    $ 393 "Set"
    set_tcp(p[-0.011699999999999999,-0.328,0.105,1.2092,-1.2092,1.2092])
    $ 394 "ek_sp≔get_actual_tcp_pose()"
    global ek_sp= get_actual_tcp_pose ()
    $ 395 "MoveL"
    $ 396 "ek_sp" "breakAfter"
    movel(ek_sp, a=1.2, v=0.005)
    $ 397 "'list possible points'"
    # 'list possible points'
    $ 398 "robot 1 moves"
    $ 399 "If 1≟2"
    if (1 == 2):
      $ 400 "MoveJ"
      $ 401 "r1_ek_oldhome" "breakAfter"
      movej(get_inverse_kin(r1_ek_oldhome_p, qnear=r1_ek_oldhome_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 402 "r1_ek_extrude" "breakAfter"
      movej(get_inverse_kin(r1_ek_extrude_p, qnear=r1_ek_extrude_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 403 "r1_ek_front" "breakAfter"
      movej(get_inverse_kin(r1_ek_front_p, qnear=r1_ek_front_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 404 "r1_ek_middle" "breakAfter"
      movej(get_inverse_kin(r1_ek_middle_p, qnear=r1_ek_middle_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 405 "r1_ek_middle2" "breakAfter"
      movej(get_inverse_kin(r1_ek_middle2_p, qnear=r1_ek_middle2_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 406 "r1_ek_bottom" "breakAfter"
      movej(get_inverse_kin(r1_ek_bottom_p, qnear=r1_ek_bottom_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 407 "r1_ek_end" "breakAfter"
      movej(get_inverse_kin(r1_ek_end_p, qnear=r1_ek_end_q), a=1.3962634015954636, v=1.0471975511965976)
    end
    $ 408 "robot 2 moves"
    $ 409 "If 1≟2"
    if (1 == 2):
      $ 410 "MoveJ"
      $ 411 "r2_ek_oldhome" "breakAfter"
      movej(get_inverse_kin(r2_ek_oldhome_p, qnear=r2_ek_oldhome_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 413 "r2_ek_extrude" "breakAfter"
      movej(get_inverse_kin(r2_ek_extrude_p, qnear=r2_ek_extrude_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 414 "r2_ek_front" "breakAfter"
      movej(get_inverse_kin(r2_ek_front_p, qnear=r2_ek_front_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 415 "r2_ek_middle" "breakAfter"
      movej(get_inverse_kin(r2_ek_middle_p, qnear=r2_ek_middle_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 416 "r2_ek_bottom" "breakAfter"
      movej(get_inverse_kin(r2_ek_bottom_p, qnear=r2_ek_bottom_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 417 "r2_ek_end" "breakAfter"
      movej(get_inverse_kin(r2_ek_end_p, qnear=r2_ek_end_q), a=1.3962634015954636, v=1.0471975511965976)
    end
    $ 418 "robot 3 moves"
    $ 419 "If 1≟2"
    if (1 == 2):
      $ 420 "MoveJ"
      $ 421 "r3_ek_oldhome" "breakAfter"
      movej(get_inverse_kin(r3_ek_oldhome_p, qnear=r3_ek_oldhome_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 422 "r3_ek_extrude" "breakAfter"
      movej(get_inverse_kin(r3_ek_extrude_p, qnear=r3_ek_extrude_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 423 "r3_ek_front" "breakAfter"
      movej(get_inverse_kin(r3_ek_front_p, qnear=r3_ek_front_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 424 "r3_ek_middle" "breakAfter"
      movej(get_inverse_kin(r3_ek_middle_p, qnear=r3_ek_middle_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 425 "r3_ek_bottom" "breakAfter"
      movej(get_inverse_kin(r3_ek_bottom_p, qnear=r3_ek_bottom_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 426 "r3_ek_end" "breakAfter"
      movej(get_inverse_kin(r3_ek_end_p, qnear=r3_ek_end_q), a=1.3962634015954636, v=1.0471975511965976)
    end
    $ 427 "robot 4 moves"
    $ 428 "If 1≟2"
    if (1 == 2):
      $ 429 "MoveJ"
      $ 430 "r4_ek_oldhome" "breakAfter"
      movej(get_inverse_kin(r4_ek_oldhome_p, qnear=r4_ek_oldhome_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 431 "r4_ek_extrude" "breakAfter"
      movej(get_inverse_kin(r4_ek_extrude_p, qnear=r4_ek_extrude_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 432 "r4_ek_front" "breakAfter"
      movej(get_inverse_kin(r4_ek_front_p, qnear=r4_ek_front_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 433 "r4_ek_middle" "breakAfter"
      movej(get_inverse_kin(r4_ek_middle_p, qnear=r4_ek_middle_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 434 "r4_ek_bottom" "breakAfter"
      movej(get_inverse_kin(r4_ek_bottom_p, qnear=r4_ek_bottom_q), a=1.3962634015954636, v=1.0471975511965976)
      $ 435 "r4_ek_end" "breakAfter"
      movej(get_inverse_kin(r4_ek_end_p, qnear=r4_ek_end_q), a=1.3962634015954636, v=1.0471975511965976)
    end
    $ 436 "'detemine correct points for which robot'"
    # 'detemine correct points for which robot'
    $ 437 "If robot_number≟1"
    if (robot_number == 1):
      $ 438 "robot1 positions"
      $ 439 "ek_oldhome≔r1_ek_oldhome_p"
      global ek_oldhome=r1_ek_oldhome_p
      $ 440 "ek_extrude≔r1_ek_extrude_p"
      global ek_extrude=r1_ek_extrude_p
      $ 441 "ek_front≔r1_ek_front_p"
      global ek_front=r1_ek_front_p
      $ 442 "ek_middle≔r1_ek_middle_p"
      global ek_middle=r1_ek_middle_p
      $ 443 "ek_middle2≔r1_ek_middle2_p"
      global ek_middle2=r1_ek_middle2_p
      $ 444 "ek_bottom≔r1_ek_bottom_p"
      global ek_bottom=r1_ek_bottom_p
      $ 445 "ek_end≔r1_ek_end_q"
      global ek_end=r1_ek_end_q
    else:
      $ 446 "ElseIf robot_number≟2"
      if (robot_number == 2):
        $ 447 "robot2 positions"
        $ 448 "ek_oldhome≔r2_ek_oldhome_p"
        global ek_oldhome=r2_ek_oldhome_p
        $ 449 "ek_extrude≔r2_ek_extrude_p"
        global ek_extrude=r2_ek_extrude_p
        $ 450 "ek_front≔r2_ek_front_p"
        global ek_front=r2_ek_front_p
        $ 451 "ek_middle≔r2_ek_middle_p"
        global ek_middle=r2_ek_middle_p
        $ 452 "ek_middle2≔r2_ek_middle_p"
        global ek_middle2=r2_ek_middle_p
        $ 453 "ek_bottom≔r2_ek_bottom_p"
        global ek_bottom=r2_ek_bottom_p
        $ 454 "ek_end≔r2_ek_end_q"
        global ek_end=r2_ek_end_q
      else:
        $ 455 "ElseIf robot_number≟3"
        if (robot_number == 3):
          $ 456 "robot3 positions"
          $ 457 "ek_oldhome≔r3_ek_oldhome_p"
          global ek_oldhome=r3_ek_oldhome_p
          $ 458 "ek_extrude≔r3_ek_extrude_p"
          global ek_extrude=r3_ek_extrude_p
          $ 459 "ek_front≔r3_ek_front_p"
          global ek_front=r3_ek_front_p
          $ 460 "ek_middle≔r3_ek_middle_p"
          global ek_middle=r3_ek_middle_p
          $ 461 "ek_middle2≔r3_ek_middle_p"
          global ek_middle2=r3_ek_middle_p
          $ 462 "ek_bottom≔r3_ek_bottom_p"
          global ek_bottom=r3_ek_bottom_p
          $ 463 "ek_end≔r3_ek_end_q"
          global ek_end=r3_ek_end_q
        else:
          $ 464 "ElseIf robot_number≟4"
          if (robot_number == 4):
            $ 465 "robot4 positions"
            $ 466 "ek_oldhome≔r4_ek_oldhome_p"
            global ek_oldhome=r4_ek_oldhome_p
            $ 467 "ek_extrude≔r4_ek_extrude_p"
            global ek_extrude=r4_ek_extrude_p
            $ 468 "ek_front≔r4_ek_front_p"
            global ek_front=r4_ek_front_p
            $ 469 "ek_middle≔r4_ek_middle_p"
            global ek_middle=r4_ek_middle_p
            $ 470 "ek_middle2≔r4_ek_middle_p"
            global ek_middle2=r4_ek_middle_p
            $ 471 "ek_bottom≔r4_ek_bottom_p"
            global ek_bottom=r4_ek_bottom_p
            $ 472 "ek_end≔r4_ek_end_q"
            global ek_end=r4_ek_end_q
          end
        end
      end
    end
    $ 473 "'start of program'"
    # 'start of program'
    $ 475 "Set"
    set_tcp(p[-0.011699999999999999,-0.328,0.105,1.2092,-1.2092,1.2092])
    $ 476 "MoveJ"
    $ 478 "ek_oldhome" "breakAfter"
    movej(ek_oldhome, a=1.3962634015954636, v=1.0471975511965976)
    $ 479 "'above waypoint is home'"
    # 'above waypoint is home'
    $ 480 "'move above bucket'"
    # 'move above bucket'
    $ 481 "MoveJ"
    $ 483 "ek_extrude" "breakAfter"
    movej(ek_extrude, a=1.3962634015954636, v=1.0471975511965976)
    $ 484 "'extrude out a foot'"
    # 'extrude out a foot'
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 486 "Serial Bridge uR1"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,49], False)
    # end: URCap Program Node
    $ 487 "Set DO[0]=On"
    set_standard_digital_out(0, True)
    $ 488 "Wait: 24.0"
    sleep(24.0)
    # begin: URCap Program Node
    #   Source: WireTank Serial, 4.9.0, WireTank, LLC
    #   Type: WireTank Serial
    $ 489 "Serial Bridge uR0"
    SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,48], False)
    # end: URCap Program Node
    $ 490 "Wait: 1.0"
    sleep(1.0)
    $ 491 "Set DO[0]=Off"
    set_standard_digital_out(0, False)
    $ 492 "'slice'"
    # 'slice'
    $ 493 "MoveL"
    $ 499 "ek_front" "breakAfter"
    movel(ek_front, a=0.05, v=0.03)
    $ 500 "ek_middle" "breakAfter"
    movel(ek_middle, a=0.05, v=0.03)
    $ 501 "ek_middle2" "breakAfter"
    movel(ek_middle2, a=0.05, v=0.03)
    $ 502 "ek_bottom" "breakAfter"
    movel(ek_bottom, a=0.05, v=0.03)
    $ 503 "ek_end" "breakAfter"
    movel(ek_end, a=0.05, v=0.03)
    $ 504 "MoveJ"
    $ 506 "ek_oldhome" "breakAfter"
    movej(ek_oldhome, a=1.3962634015954636, v=1.0471975511965976)
    $ 507 "'above waypoint is home'"
    # 'above waypoint is home'
  end
  def align_tcp_forward():
    $ 509 "align_tcp_forward" "noBreak"
    $ 510 "'this program aligns the tcp parallel to the y direction'"
    # 'this program aligns the tcp parallel to the y direction'
    $ 511 "cp≔get_actual_tcp_pose()"
    global cp= get_actual_tcp_pose ()
    $ 512 "aligned_y_pose≔p[cp[0],cp[1],cp[2],0,-1.570796,0]"
    global aligned_y_pose=p[cp[0],cp[1],cp[2],0,-1.570796,0]
    $ 513 "MoveJ"
    $ 514 "aligned_y_pose" "breakAfter"
    movej(aligned_y_pose, a=1.3962634015954636, v=1.0471975511965976)
  end
  def align_tcp_up():
    $ 515 "align_tcp_up" "noBreak"
    $ 516 "'this program aligns the tcp parallel to the y direction'"
    # 'this program aligns the tcp parallel to the y direction'
    $ 517 "cp≔get_actual_tcp_pose()"
    global cp= get_actual_tcp_pose ()
    $ 518 "aligned_y_pose≔p[cp[0],cp[1],cp[2],0,0,0]"
    global aligned_y_pose=p[cp[0],cp[1],cp[2],0,0,0]
    $ 519 "MoveJ"
    $ 520 "aligned_y_pose" "breakAfter"
    movej(aligned_y_pose, a=1.3962634015954636, v=1.0471975511965976)
  end
  def align_ready_for_welding():
    $ 521 "align_ready_for_welding" "noBreak"
    $ 522 "'this program takes the welder from home to a position alined ready for welding (vertically down)'"
    # 'this program takes the welder from home to a position alined ready for welding (vertically down)'
    $ 523 "MoveJ"
    $ 524 "oldhome" "breakAfter"
    movej(get_inverse_kin(oldhome_p, qnear=oldhome_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 525 "Waypoint_34" "breakAfter"
    movej(get_inverse_kin(Waypoint_34_p, qnear=Waypoint_34_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 526 "Waypoint_35" "breakAfter"
    movej(get_inverse_kin(Waypoint_35_p, qnear=Waypoint_35_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 527 "Waypoint_36" "breakAfter"
    movej(get_inverse_kin(Waypoint_36_p, qnear=Waypoint_36_q), a=1.3962634015954636, v=1.0471975511965976)
  end
  def Corner_Homing_45():
    $ 528 "Corner_Homing_45" "noBreak"
    $ 529 "'Use this program when tool is already positioned close to corner at 45deg'"
    # 'Use this program when tool is already positioned close to corner at 45deg'
    $ 530 "'tool flange will seek all 3 sides. will save those 5 locs in p__'"
    # 'tool flange will seek all 3 sides. will save those 5 locs in p__'
    $ 531 "Set"
    set_tcp(p[1.4000000000000001E-4,-0.01751,0.284,0.0,0.0,0.0])
    $ 540 "Wait: 1.0"
    sleep(1.0)
    $ 541 "tp≔get_actual_tcp_pose()"
    global tp= get_actual_tcp_pose ()
    $ 545 "path_pre≔get_corner_homing_45_pathpoints(tp,tcp_pose_top)"
    global path_pre=get_corner_homing_45_pathpoints(tp,tcp_pose_top)
    $ 546 "ph1≔path_pre[0]"
    global ph1=path_pre[0]
    $ 547 "ph2≔path_pre[1]"
    global ph2=path_pre[1]
    $ 548 "ph3≔path_pre[2]"
    global ph3=path_pre[2]
    $ 549 "ph4≔path_pre[3]"
    global ph4=path_pre[3]
    $ 550 "ph5≔path_pre[4]"
    global ph5=path_pre[4]
    $ 551 "ph6≔path_pre[5]"
    global ph6=path_pre[5]
    $ 552 "ph7≔path_pre[6]"
    global ph7=path_pre[6]
    $ 553 "ph2up≔path_pre[7]"
    global ph2up=path_pre[7]
    $ 554 "ph4up≔path_pre[8]"
    global ph4up=path_pre[8]
    $ 555 "MoveL"
    $ 556 "ph1" "breakAfter"
    movel(ph1, a=0.2, v=0.25)
    $ 557 "ph2" "breakAfter"
    movel(ph2, a=0.2, v=0.25)
    $ 558 "Wait: 0.5"
    sleep(0.5)
    $ 559 "MoveL"
    $ 560 "Direction: Base"
    global move_thread_flag_560=0
    thread move_thread_560():
      enter_critical
      move_thread_flag_560 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1,-1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.02)
      move_thread_flag_560 = 2
      exit_critical
    end
    move_thread_flag_560 = 0
    move_thread_han_560 = run move_thread_560()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_560
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 561 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 562 "p11≔get_actual_tcp_pose()"
    global p11= get_actual_tcp_pose ()
    $ 563 "MoveJ"
    $ 564 "ph2" "breakAfter"
    movej(ph2, a=1.3962634015954636, v=1.0471975511965976)
    $ 565 "ph2up" "breakAfter"
    movej(ph2up, a=1.3962634015954636, v=1.0471975511965976)
    $ 566 "Wait: 0.5"
    sleep(0.5)
    $ 567 "MoveL"
    $ 568 "Direction: Base"
    global move_thread_flag_568=0
    thread move_thread_568():
      enter_critical
      move_thread_flag_568 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1,-1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.02)
      move_thread_flag_568 = 2
      exit_critical
    end
    move_thread_flag_568 = 0
    move_thread_han_568 = run move_thread_568()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_568
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 569 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 570 "p13≔get_actual_tcp_pose()"
    global p13= get_actual_tcp_pose ()
    $ 571 "MoveJ"
    $ 572 "ph2up" "breakAfter"
    movej(ph2up, a=1.3962634015954636, v=1.0471975511965976)
    $ 573 "ph3" "breakAfter"
    movej(ph3, a=1.3962634015954636, v=1.0471975511965976)
    $ 574 "Wait: 0.5"
    sleep(0.5)
    $ 575 "MoveL"
    $ 576 "Direction: Base"
    global move_thread_flag_576=0
    thread move_thread_576():
      enter_critical
      move_thread_flag_576 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1,-1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.02)
      move_thread_flag_576 = 2
      exit_critical
    end
    move_thread_flag_576 = 0
    move_thread_han_576 = run move_thread_576()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_576
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 577 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 578 "p12≔get_actual_tcp_pose()"
    global p12= get_actual_tcp_pose ()
    $ 582 "MoveL"
    $ 583 "ph3" "breakAfter"
    movel(ph3, a=1.2, v=0.25)
    $ 584 "ph1" "breakAfter"
    movel(ph1, a=1.2, v=0.25)
    $ 589 "MoveL"
    $ 590 "ph4" "breakAfter"
    movel(ph4, a=1.2, v=0.25)
    $ 591 "Wait: 0.5"
    sleep(0.5)
    $ 592 "MoveL"
    $ 593 "Direction: Base"
    global move_thread_flag_593=0
    thread move_thread_593():
      enter_critical
      move_thread_flag_593 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.02)
      move_thread_flag_593 = 2
      exit_critical
    end
    move_thread_flag_593 = 0
    move_thread_han_593 = run move_thread_593()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_593
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 594 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 595 "p21≔get_actual_tcp_pose()"
    global p21= get_actual_tcp_pose ()
    $ 596 "MoveL"
    $ 597 "ph4" "breakAfter"
    movel(ph4, a=1.2, v=0.25)
    $ 598 "ph4up" "breakAfter"
    movel(ph4up, a=1.2, v=0.25)
    $ 599 "Wait: 0.5"
    sleep(0.5)
    $ 600 "MoveL"
    $ 601 "Direction: Base"
    global move_thread_flag_601=0
    thread move_thread_601():
      enter_critical
      move_thread_flag_601 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.02)
      move_thread_flag_601 = 2
      exit_critical
    end
    move_thread_flag_601 = 0
    move_thread_han_601 = run move_thread_601()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_601
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 602 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 603 "p23≔get_actual_tcp_pose()"
    global p23= get_actual_tcp_pose ()
    $ 604 "MoveL"
    $ 605 "ph4up" "breakAfter"
    movel(ph4up, a=1.2, v=0.25)
    $ 606 "ph5" "breakAfter"
    movel(ph5, a=1.2, v=0.25)
    $ 607 "Wait: 0.5"
    sleep(0.5)
    $ 608 "MoveL"
    $ 609 "Direction: Base"
    global move_thread_flag_609=0
    thread move_thread_609():
      enter_critical
      move_thread_flag_609 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.02)
      move_thread_flag_609 = 2
      exit_critical
    end
    move_thread_flag_609 = 0
    move_thread_han_609 = run move_thread_609()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_609
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 610 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 611 "p22≔get_actual_tcp_pose()"
    global p22= get_actual_tcp_pose ()
    $ 622 "MoveJ"
    $ 623 "ph5" "breakAfter"
    movej(ph5, a=1.3962634015954636, v=1.0471975511965976)
    $ 624 "MoveL"
    $ 625 "ph4" "breakAfter"
    movel(ph4, a=1.2, v=0.25)
    $ 626 "ph1" "breakAfter"
    movel(ph1, a=1.2, v=0.25)
    $ 627 "MoveJ"
    $ 628 "Waypoint_4" "breakAfter"
    movej(get_inverse_kin(Waypoint_4_p, qnear=Waypoint_4_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 629 "Waypoint_13" "breakAfter"
    movej(get_inverse_kin(Waypoint_13_p, qnear=Waypoint_13_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 631 "ph6" "breakAfter"
    movej(ph6, a=1.3962634015954636, v=1.0471975511965976)
    $ 632 "ph7" "breakAfter"
    movej(ph7, a=1.3962634015954636, v=1.0471975511965976)
    $ 633 "Wait: 1.0"
    sleep(1.0)
    $ 637 "MoveL"
    $ 638 "Direction: Base Z+"
    global move_thread_flag_638=0
    thread move_thread_638():
      enter_critical
      move_thread_flag_638 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.02)
      move_thread_flag_638 = 2
      exit_critical
    end
    move_thread_flag_638 = 0
    move_thread_han_638 = run move_thread_638()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_638
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 639 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 640 "p3≔get_actual_tcp_pose()"
    global p3= get_actual_tcp_pose ()
    $ 641 "MoveJ"
    $ 642 "ph7" "breakAfter"
    movej(ph7, a=1.3962634015954636, v=1.0471975511965976)
    $ 643 "ph6" "breakAfter"
    movej(ph6, a=1.3962634015954636, v=1.0471975511965976)
    $ 644 "Waypoint_14" "breakAfter"
    movej(get_inverse_kin(Waypoint_14_p, qnear=Waypoint_14_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 645 "Waypoint_4" "breakAfter"
    movej(get_inverse_kin(Waypoint_4_p, qnear=Waypoint_4_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 646 "Waypoint_41" "breakAfter"
    movej(get_inverse_kin(Waypoint_41_p, qnear=Waypoint_41_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 647 "'above waypoint is home'"
    # 'above waypoint is home'
    $ 649 "Comment"
    # Comment
    $ 650 "Comment"
    # Comment
    $ 651 "Comment"
    # Comment
    $ 652 "Comment"
    # Comment
    $ 653 "Comment"
    # Comment
    $ 654 "Comment"
    # Comment
  end
  $ 2 "BeforeStart"
  $ 3 "Safe Home Folder"
  $ 4 "'if robot is not at home, send it back to home safely'"
  # 'if robot is not at home, send it back to home safely'
  $ 5 "'make sure the tcp is welder'"
  # 'make sure the tcp is welder'
  $ 6 "Set"
  set_tcp(p[-0.011699999999999999,-0.328,0.105,1.2092,-1.2092,1.2092])
  $ 7 "sp≔get_actual_tcp_pose()"
  global sp= get_actual_tcp_pose ()
  $ 8 "MoveL"
  $ 9 "sp" "breakAfter"
  movel(sp, a=1.2, v=0.25)
  $ 10 "'if first move is to a variable, skip automove'"
  # 'if first move is to a variable, skip automove'
  $ 11 "'turn off welder'"
  # 'turn off welder'
  # begin: URCap Program Node
  #   Source: WireTank Serial, 4.9.0, WireTank, LLC
  #   Type: WireTank Serial
  $ 12 "Serial Bridge uR0"
  SerialResponse = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", [252,82,48], False)
  # end: URCap Program Node
  $ 13 "Set DO[0]=Off"
  set_standard_digital_out(0, False)
  $ 14 "jp≔get_actual_joint_positions()"
  global jp= get_actual_joint_positions ()
  $ 15 "If sp[0]>0.600"
  if (sp[0]>0.600):
    $ 16 "'if x > 600 then above then home'"
    # 'if x > 600 then above then home'
    $ 17 "MoveJ"
    $ 19 "Waypoint_76" "breakAfter"
    movej(get_inverse_kin(Waypoint_76_p, qnear=Waypoint_76_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 20 "Home"
    movej([-3.266929759358355, -1.2139462677784536, 1.5878387874396154, 1.1069165929565088, -0.0023738326664366483, -1.7891447305770605], a=1.3962634015954636, v=1.0471975511965976)
  else:
    $ 21 "Else" "noBreak"
    $ 22 "Popup: retreating to home"
    popup("retreating to home", "Message", False, False, blocking=True)
    $ 23 "'for rules 2-8, finish with oldhome then above then home'"
    # 'for rules 2-8, finish with oldhome then above then home'
    $ 24 "If -1.74<jp[4] and jp[4]<1.05 and -1.74<jp[3] and jp[3]<1.74"
    if (-1.74<jp[4]  and  jp[4]<1.05  and  -1.74<jp[3]  and  jp[3]<1.74):
      $ 25 "'if oldhome, test teach, then go straight to oldhome'"
      # 'if oldhome, test teach, then go straight to oldhome'
    else:
      $ 26 "ElseIf sp[0]<-.5 and jp[3]>3.14 and -2.62<jp[4] and jp[4]<-0.87"
      if (sp[0]<-.5  and  jp[3]>3.14  and  -2.62<jp[4]  and  jp[4]<-0.87):
        $ 27 "'if left side weld approach, left weld approach in reverse'"
        # 'if left side weld approach, left weld approach in reverse'
        $ 28 "MoveJ"
        $ 29 "Waypoint_50" "breakAfter"
        movej(get_inverse_kin(Waypoint_50_p, qnear=Waypoint_50_q), a=1.3962634015954636, v=1.0471975511965976)
        $ 30 "Waypoint_51" "breakAfter"
        movej(get_inverse_kin(Waypoint_51_p, qnear=Waypoint_51_q), a=1.3962634015954636, v=1.0471975511965976)
        $ 31 "Waypoint_52" "breakAfter"
        movej(get_inverse_kin(Waypoint_52_p, qnear=Waypoint_52_q), a=1.3962634015954636, v=1.0471975511965976)
        $ 32 "Waypoint_53" "breakAfter"
        movej(get_inverse_kin(Waypoint_53_p, qnear=Waypoint_53_q), a=1.3962634015954636, v=1.0471975511965976)
      else:
        $ 33 "ElseIf sp[0]<0 and 0<jp[3] and jp[3]<1.74 and 0.87<jp[4] and jp[4]<2.62"
        if (sp[0]<0  and  0<jp[3]  and  jp[3]<1.74  and  0.87<jp[4]  and  jp[4]<2.62):
          $ 34 "'if right side around, move back then wapoint 24 then oldhome'"
          # 'if right side around, move back then wapoint 24 then oldhome'
          $ 35 "If sp[0]<-1.0"
          if (sp[0]<-1.0):
            $ 36 "xback≔p[-1.0,sp[1],sp[2],sp[3],sp[4],sp[5]]"
            global xback=p[-1.0,sp[1],sp[2],sp[3],sp[4],sp[5]]
            $ 37 "MoveJ"
            $ 38 "xback" "breakAfter"
            movej(xback, a=1.3962634015954636, v=1.0471975511965976)
          end
          $ 39 "MoveJ"
          $ 40 "Waypoint_54" "breakAfter"
          movej(get_inverse_kin(Waypoint_54_p, qnear=Waypoint_54_q), a=1.3962634015954636, v=1.0471975511965976)
        else:
          $ 41 "ElseIf jp[3]>2.62 and jp[4]<-3.84"
          if (jp[3]>2.62  and  jp[4]<-3.84):
            $ 42 "'if left side second half, then left weld ending sequence'"
            # 'if left side second half, then left weld ending sequence'
            $ 43 "If jp[5]<0.35"
            if (jp[5]<0.35):
              $ 44 "MoveJ"
              $ 45 "Waypoint_65" "breakAfter"
              movej(get_inverse_kin(Waypoint_65_p, qnear=Waypoint_65_q), a=1.3962634015954636, v=1.0471975511965976)
            end
            $ 46 "MoveJ"
            $ 51 "'above is testing, below is real'"
            # 'above is testing, below is real'
            $ 52 "Waypoint_55" "breakAfter"
            movej(get_inverse_kin(Waypoint_55_p, qnear=Waypoint_55_q), a=1.3962634015954636, v=1.0471975511965976)
            $ 54 "Waypoint_59" "breakAfter"
            movej(get_inverse_kin(Waypoint_59_p, qnear=Waypoint_59_q), t=2.0)
            $ 55 "Waypoint_71" "breakAfter"
            movej(get_inverse_kin(Waypoint_71_p, qnear=Waypoint_71_q), a=1.3962634015954636, v=1.0471975511965976)
            $ 56 "Waypoint_58" "breakAfter"
            movej(get_inverse_kin(Waypoint_58_p, qnear=Waypoint_58_q), a=1.3962634015954636, v=1.0471975511965976)
            $ 57 "Waypoint_56" "breakAfter"
            movej(get_inverse_kin(Waypoint_56_p, qnear=Waypoint_56_q), a=1.3962634015954636, v=1.0471975511965976)
            $ 58 "Waypoint_57" "breakAfter"
            movej(get_inverse_kin(Waypoint_57_p, qnear=Waypoint_57_q), a=1.3962634015954636, v=1.0471975511965976)
          else:
            $ 59 "ElseIf jp[3]<-2.09"
            if (jp[3]<-2.09):
              $ 60 "'bottom homing'"
              # 'bottom homing'
              $ 61 "MoveJ"
              $ 63 "Comment"
              # Comment
              $ 64 "If sp[0]<-0.95"
              if (sp[0]<-0.95):
                $ 65 "xback≔p[-0.95,sp[1],sp[2],sp[3],sp[4],sp[5]]"
                global xback=p[-0.95,sp[1],sp[2],sp[3],sp[4],sp[5]]
                $ 66 "MoveL"
                $ 67 "xback" "breakAfter"
                movel(xback, a=1.2, v=0.25)
              end
              $ 68 "Waypoint_67" "breakAfter"
              movej(get_inverse_kin(Waypoint_67_p, qnear=Waypoint_67_q), a=1.3962634015954636, v=1.0471975511965976)
            else:
              $ 69 "ElseIf jp[3]<0 and jp[4]<-3.14"
              if (jp[3]<0  and  jp[4]<-3.14):
                $ 70 "'if left side homing, special unspin'"
                # 'if left side homing, special unspin'
                $ 71 "MoveJ"
                $ 73 "Comment"
                # Comment
                $ 74 "Waypoint_69" "breakAfter"
                movej(get_inverse_kin(Waypoint_69_p, qnear=Waypoint_69_q), a=1.3962634015954636, v=1.0471975511965976)
                $ 75 "Waypoint_70" "breakAfter"
                movej(get_inverse_kin(Waypoint_70_p, qnear=Waypoint_70_q), a=1.3962634015954636, v=1.0471975511965976)
              else:
                $ 76 "ElseIf (sp[4]<-3 or sp[4]>3) and -0.02<sp[5] and sp[5]<0.02"
                if ((sp[4]<-3  or  sp[4]>3)  and  -0.02<sp[5]  and  sp[5]<0.02):
                  $ 77 "'go straight to home'"
                  # 'go straight to home'
                else:
                  $ 78 "ElseIf 2>1"
                  if (2>1):
                    $ 79 "'if none of the other options, then error continuously'"
                    # 'if none of the other options, then error continuously'
                    $ 80 "Loop 2>1"
                    while (2>1):
                      $ 81 "Popup: Unknown Position. Find Calvin for Assistance"
                      popup("Unknown Position. Find Calvin for Assistance", "Message", False, False, blocking=True)
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    $ 82 "'insert logic for how to get back to oldhome'"
    # 'insert logic for how to get back to oldhome'
    $ 83 "'finish with oldhome then above then home'"
    # 'finish with oldhome then above then home'
    $ 84 "MoveJ"
    $ 85 "Waypoint_49" "breakAfter"
    movej(get_inverse_kin(Waypoint_49_p, qnear=Waypoint_49_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 87 "Waypoint_75" "breakAfter"
    movej(get_inverse_kin(Waypoint_75_p, qnear=Waypoint_75_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 88 "Home"
    movej([-3.266929759358355, -1.2139462677784536, 1.5878387874396154, 1.1069165929565088, -0.0023738326664366483, -1.7891447305770605], a=1.3962634015954636, v=1.0471975511965976)
    # begin: URCap Program Node
    #   Source: MachineLogic for Universal Robots, 3.1.7, Vention Inc.
    #   Type: MachineLogic for Universal Robots
    $ 89 "MachineLogic Homing"
    while isVentionMovementBusyMachineMotion1==True:
    sleep(0.05)
    end
    if(isVentionMovementBusyMachineMotion1 == False):
    isVentionMovementBusyMachineMotion1 = True
    socket_send_string("estop/status;", "MachineMotion1")
    temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
    while(temp_estop_var_vention=="estop/status true"):
    if temp_estop_var_vention=="estop/status true":
    sendStringWithTimeout("estop/systemreset/request","Ack estop/systemreset/request;","MachineMotion1")
    end
    socket_send_string("estop/status;", "MachineMotion1")
    temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
    if temp_estop_var_vention=="estop/status true":
    popup("MachineMotion in estop, make sure you have all emergency modules released manually. If you continue the system will try to reset MachineMotion automatically.",blocking=True)
    end
    end
    else:
    popup("resource is being used already: MachineMotion1")
    halt
    end
    isVentionMovementBusyMachineMotion1 = True
    sendString("im_home_axis_1", "MachineMotion im_home_axis_1 = completed", "MachineMotion1")
    isVentionMovementBusyMachineMotion1 = False
    sendString("SET im_set_encoder_pos_aux_1 0.000", "Ack", "MachineMotion1")
    isVentionMovementBusyMachineMotion1 = False
    sleep(0.03)
    # end: URCap Program Node
  end
  $ 655 "Thread_1"
  thread Thread_1():
    $ 656 "Loop  True "
    while (  True  ):
      $ 657 "If freedrive_m_var≟ True "
      if (freedrive_m_var ==   True  ):
        $ 658 "freedrive_mode()"
        freedrive_mode()
        $ 659 "free_dr_already≔ True "
        global free_dr_already=  True  
      else:
        $ 660 "Else" "noBreak"
        $ 661 "If free_dr_already"
        if (free_dr_already):
          $ 662 "end_freedrive_mode()"
          end_freedrive_mode()
        end
      end
      $ 663 "sync()"
      sync()
    end
  end
  threadId_Thread_1 = run Thread_1()
  $ 90 "Robot Program"
  $ 91 "'start of main program'"
  # 'start of main program'
  $ 92 "Set"
  set_tcp(p[-0.011699999999999999,-0.328,0.105,1.2092,-1.2092,1.2092])
  $ 93 "Home"
  movej([-3.266929759358355, -1.2139462677784536, 1.5878387874396154, 1.1069165929565088, -0.0023738326664366483, -1.7891447305770605], a=1.3962634015954636, v=1.0471975511965976)
  $ 94 "Script: common_math.script"
  # this file contains math equations and operations, not specific to any one feature
  
  # define pi
  pi = 3.1415926535
  
  # given 3 points, this finds the plane and its equation
  # rereturns ax + by + cz + d = 0 in a list of [a, b, c, d]
  def findplane(p11, p12, p13):
      # extract coordinates
      x1 = p11[0]
      y1 = p11[1]
      z1 = p11[2]
      x2 = p12[0]
      y2 = p12[1]
      z2 = p12[2]
      x3 = p13[0]
      y3 = p13[1]
      z3 = p13[2]
      # create vectors from the points
      v1x = x2-x1
      v1y = y2-y1
      v1z = z2-z1
      v2x = x3-x1
      v2y = y3-y1
      v2z = z3-z1
      #calculate the normal vector using the cross product
      nx = v1y*v2z - v1z*v2y # i component
      ny = v1z*v2x - v1x*v2z # j component
      nz = v1x*v2y - v1y*v2x # k component
      # calculate d in the plane equation
      d = -1 * (nx*x1 + ny*y1 + nz*z1)
      ret = [nx, ny, nz, d]
      return ret
  end
  
  # this function finds the intersection point between two lines in the xy plane
  # takes 4 arguments: m1, b1, m2, b2
  # returns a list of [x,y] (the point of intersection)
  def find_intersection(m1, b1, m2, b2):
    # m1x+b1 = m2x+b2
    # m1x - m2x = b2 - b1
    # x = (b2-b1) / (m1-m2)
    x = (b2-b1) / (m1-m2)
    y = m1 * x + b1
    ret = [x, y]
    return ret
  end
  
  # this function finds the distance between 2 points in 3d space
  # it takes 6 arguments: x1, y1, z1, x2, y2, z2
  # it returns a distance
  def distance_between(x1, y1, z1, x2, y2, z2):
    distsquared = (x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)+(z2-z1)*(z2-z1)
    dist = sqrt(distsquared)
    return dist
  end
  
  # this function takes a point, a unit vector, and a distance, and adds the distance to the point in the direction of the unit vector (3d space)
  # it returns a point as a list of coordinates
  def add_vectordistance_to_point(xi, yi, zi, uvx, uvy, uvz, delta):
    xf = xi + uvx * delta
    yf = yi + uvy * delta
    zf = zi + uvz * delta
    ret = [xf, yf, zf]
    return ret
  end
  
  # this function takes two rotation matrices, and multiplies them together, returning one matrix.
  # all matrices are in the form of a list.
  # all matrix values have constant values (no variables)
  def multiply_matrix(matrix1, matrix2):
      # retrieve values
      a11 = matrix1[0]
      a12 = matrix1[1]
      a13 = matrix1[2]
      a21 = matrix1[3]
      a22 = matrix1[4]
      a23 = matrix1[5]
      a31 = matrix1[6]
      a32 = matrix1[7]
      a33 = matrix1[8]
      b11 = matrix2[0]
      b12 = matrix2[1]
      b13 = matrix2[2]
      b21 = matrix2[3]
      b22 = matrix2[4]
      b23 = matrix2[5]
      b31 = matrix2[6]
      b32 = matrix2[7]
      b33 = matrix2[8]
      #calculate c values
      c11 = a11*b11 + a12*b21 + a13*b31
      c12 = a11*b12 + a12*b22 + a13*b32
      c13 = a11*b13 + a12*b23 + a13*b33
      c21 = a21*b11 + a22*b21 + a23*b31
      c22 = a21*b12 + a22*b22 + a23*b32
      c23 = a21*b13 + a22*b23 + a23*b33
      c31 = a31*b11 + a32*b21 + a33*b31
      c32 = a31*b12 + a32*b22 + a33*b32
      c33 = a31*b13 + a32*b23 + a33*b33
      # return resulting matrix
      ret = [c11, c12, c13, c21, c22, c23, c31, c32, c33]
      return ret
  end
  
  # this function converts a matrix to axis angle representations
  # this matrix is usually a resulting matrix (result of matrix multiplication) in normal use, given as a list
  # returns a list of [rx,ry,rz]
  def convert_matrix_to_axang(matrix1):
      # retrieve values
      a11 = matrix1[0]
      a12 = matrix1[1]
      a13 = matrix1[2]
      a21 = matrix1[3]
      a22 = matrix1[4]
      a23 = matrix1[5]
      a31 = matrix1[6]
      a32 = matrix1[7]
      a33 = matrix1[8]
  
      # First Half: find the angle
      # find the trace
      # using the formula: trace = a11 + a22 + a33
      trace = a11 + a22 + a33
      # find the angle using the formula: trace(matrix) = 1 + 2 cos(angle)
      angle = acos((trace - 1.0)/2.0)
  
      # Second Half: calculate the rotation axis
      axisxraw = a32 - a23
      axisyraw = a13 - a31
      axiszraw = a21 - a12
      # normalize axis
      magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
      axisxunit = axisxraw / magnitude
      axisyunit = axisyraw / magnitude
      axiszunit = axiszraw / magnitude
  
      # combine axis and angle into rxryrz representation
      rxout = axisxunit * angle
      ryout = axisyunit * angle
      rzout = axiszunit * angle
      return [rxout, ryout, rzout]
  end
  
  # this function takes a rotation and calculates the corresponding rotation matrix
  # input is (axis, direction, angle in radians)
  # example is ("x", 1, pi/6) = a 30 degree turn around the x axis in the positive direction (right hand rule)
  # returns a matrix (a list of 9 values)
  def get_rotation_matrix_from_description(axis, direction, angle):
      # get the angle
      a = angle * direction
      # get the axis
      if axis == "x" or axis == "X":
          matrix = [1, 0, 0, 0, cos(a), -1 * sin(a), 0, sin(a), cos(a)]
          return matrix
      end
      if axis == "y" or axis == "Y":
          matrix = [cos(a), 0, sin(a), 0, 1, 0, -1*sin(a), 0, cos(a)]
          return matrix
      end
      if axis == "z" or axis == "Z":
          matrix = [cos(a), -1*sin(a), 0, sin(a), cos(a), 0, 0, 0, 1]
          return matrix
      end
      # bad
      popuptext = "Error in get_rotation_matrix_from_description. "
      # infinite loop
      while 1==1:
        popup(popuptext, title="Code Error",blocking=True)
      end
  end
  
  # given a round over distance (in mm), calculate (based on 90 degrees) the distance from corner (line intersection) to midpoint of arc
  # returns a value (in mm) that you need to move from line intersection to midpoint (actual distance will be this times sqrt(2))
  def calc_rod_midpoint_90deg(rod):
      # the factor is (1- 1/sqrt(2))
      factor = 0.292893
      ret = rod * factor
      return ret
  end
  
  def crossproduct(vec1, vec2):
      nx = vec1[1]*vec2[2] - vec1[2]*vec2[1]
      ny = vec1[2]*vec2[0] - vec1[0]*vec2[2]
      nz = vec1[0]*vec2[1] - vec1[1]*vec2[0]
      ret = [nx, ny, nz]
      return ret
  end
  
  # Section: headings, angles, slopes conversions
  
  # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
  # this will point the gun in this heading with the bottom side of the gun facing up.
  # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
  def convert_heading_to_axang(heading):
   axisxraw = -1 * sin(heading)
   axisyraw = cos(heading) + 1
   axiszraw = sin(heading)
  
   magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
  
   axisxunit = axisxraw / magnitude
   axisyunit = axisyraw / magnitude
   axiszunit = axiszraw / magnitude
  
   angle = acos( (cos(heading) - 1) / 2 )
  
   rxout = axisxunit * angle
   ryout = axisyunit * angle
   rzout = axiszunit * angle
  
   return [rxout, ryout, rzout]
  end
  
  # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
  # this will point the gun in this heading with the preheat side of the gun tip facing up. Used for welding in a vertical path.
  # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
  def convert_heading_to_axang_preheatup(heading):
   axisxraw = -sin(heading) + 1
   axisyraw = cos(heading)
   axiszraw = cos(heading)
  
   magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
  
   axisxunit = axisxraw / magnitude
   axisyunit = axisyraw / magnitude
   axiszunit = axiszraw / magnitude
  
   angle = acos( (-sin(heading) - 1) / 2 )
  
   rxout = axisxunit * angle
   ryout = axisyunit * angle
   rzout = axiszunit * angle
  
   return [rxout, ryout, rzout]
  end
  
  # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
  # this will point the gun in this heading with the preheat side of the gun tip facing down. Used for welding in a vertical path downwards.
  # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
  def convert_heading_to_axang_preheatdown(heading):
   axisxraw = -sin(heading) - 1
   axisyraw = cos(heading)
   axiszraw = -cos(heading)
  
   magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
  
   axisxunit = axisxraw / magnitude
   axisyunit = axisyraw / magnitude
   axiszunit = axiszraw / magnitude
  
   angle = acos( (sin(heading) - 1) / 2 )
  
   rxout = axisxunit * angle
   ryout = axisyunit * angle
   rzout = axiszunit * angle
  
   return [rxout, ryout, rzout]
  end
  
  # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
  # this will point the gun in this heading with the preheat side of the gun tip facing right. Used for welding counterclockwise around the box.
  # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
  def convert_heading_to_axang_ccw(heading):
   axisxraw = -sin(heading)
   axisyraw = cos(heading) - 1
   axiszraw = -sin(heading)
  
   magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
  
   axisxunit = axisxraw / magnitude
   axisyunit = axisyraw / magnitude
   axiszunit = axiszraw / magnitude
  
   angle = acos( (-cos(heading) - 1) / 2 )
  
   rxout = axisxunit * angle
   ryout = axisyunit * angle
   rzout = axiszunit * angle
  
   return [rxout, ryout, rzout]
  end
  
  # given a heading, (ccw from +x axis), find the mx+b slope
  # fails if exactly vertical
  def get_slope_from_heading(heading):
      return tan(heading)
  end
  
  # this function converts a unit vector to its heading angle ccw from x+ axis
  # takes uvx and uvy
  # returns heading in radians
  def convert_uv_to_heading(uvx, uvy):
    baseang = atan(uvy/uvx)
    if uvx < 0:
      ang = baseang + pi
    elif uvy < 0:
      ang = baseang + pi * 2
    else:
      ang = baseang
    end
    return ang
  end
  
  # this function finds the equation of a line, perpendicular to a given line, and going through a given point
  # takes 3 arguments: m (the original line's slope), x (point's x coord), y (point's y coord). the b of the original line is not needed
  # returns a list of [m,b] (the slope and intercept of the new line)
  def find_perpendicular_line(origm, x, y):
    m = (1/origm) * -1
    b = y - m*x
    ret = [m, b]
    return ret
  end
  
  # returns the absolute value of a number
  def absolute(x):
      ret = x
      if x < 0:
          ret = -1 * x
      end
      return ret
  end
  $ 95 "Script: common_io.script"
  # common_io.script
  # this file contains IO (input/output) commands, commonly used by robot programs
  # includes rs232 commands, lift column commands, and calls to native universal robots functions (like get_inverse_kin_has_solution())
  
  
  # Section: rs232 commands ###############################
  
  # this function sends a signal to turn extrusion on
  def turn_extrusion_on():
    # flush the channel
    resp0 = send_serial_signal(["u", "r", "?"])
    # send the signal
    resp1 = send_serial_signal(["u", "R", "1"])
    # if resp <> "uR1"
    if resp1 != [252,82,49]:
      # turn off extrusion and heating. inform calvin
      resp2 = send_serial_signal(["u", "R", "0"])
      resp3 = send_serial_signal(["u", "H", "0"])
      popuptext = "Error code encountered while trying to start extrusion. Find Calvin. "
      while 1==1:
        popup(popuptext, title="Extrusion Error Code",blocking=True)
        popup(resp1, blocking=True)
      end
    end
  end
  
  # this function sends a signal and receives a response
  # signal is a list of 3 strings, 1 character each. first is u. second is the next character. third is final character
  def send_serial_signal(signal):
    signal2char = signal[1]
    signal3char = signal[2]
    listsignal = [252, get_corr_number(signal2char), get_corr_number(signal3char)]
    resp1 = WTSerialBridge.send_command("/dev/ttyUSB0",1200, 8, "None", "One", "None", 1000, "None", "None", listsignal, True)
    return resp1
  end
  
  # this function converts a letter into its ascii number
  def get_corr_number(letter):
    if letter == "A":
      return 65
    elif letter == "H":
      return 72
    elif letter == "R":
      return 82
    elif letter == "M":
      return 77
    elif letter == "E":
      return 69
    elif letter == "a":
      return 97
    elif letter == "b":
      return 98
    elif letter == "h":
      return 104
    elif letter == "r":
      return 114
    elif letter == "s":
      return 115
    elif letter == "m":
      return 109
    elif letter == "0":
      return 48
    elif letter == "1":
      return 49
    elif letter == "2":
      return 50
    elif letter == "3":
      return 51
    elif letter == "4":
      return 52
    elif letter == "5":
      return 53
    elif letter == "6":
      return 54
    elif letter == "7":
      return 55
    elif letter == "8":
      return 56
    elif letter == "9":
      return 57
    elif letter == "?":
      return 63
    end
  end
  
  # this function checks whether the welder is in the ready state.
  # to be called at the beginning of Main Program
  def welder_state_ready():
    # flush the channel
    resp0 = send_serial_signal(["u", "s", "?"])
    # send the signal
    resp1 = send_serial_signal(["u", "s", "?"])
    # if resp1 == [252,115,49] (us1) then it is ready. otherwise, it is not
    if resp1 != [252,115,49]:
      popuptext = "Welder is not ready for extrusion. Follow the instructions to start heating welder. "
      while 1==1:
        popup(popuptext, title="Welder Not Ready",blocking=True)
      end
    end
  
  end
  
  
  # Section: lift column commands ##################################
  
  # initialize a lift column extension needed of 0.0
  global liftcolumnzneeded = 0.0 # set this variable in mm
  
  def get_lift_column_height():
    # begin: URCap Program Node
    #   Source: MachineLogic for Universal Robots, 3.1.7, Vention Inc.
    #   Type: MachineLogic for Universal Robots
    #$ 5 "MachineLogic Get Position"
    while isVentionMovementBusyMachineMotion1==True:
      sleep(0.05)
    end
    if(isVentionMovementBusyMachineMotion1 == False):
      isVentionMovementBusyMachineMotion1 = True
      socket_send_string("estop/status;", "MachineMotion1")
      temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
      while(temp_estop_var_vention=="estop/status true"):
        if temp_estop_var_vention=="estop/status true":
          sendStringWithTimeout("estop/systemreset/request","Ack estop/systemreset/request;","MachineMotion1")
        end
        socket_send_string("estop/status;", "MachineMotion1")
        temp_estop_var_vention = socket_read_string("MachineMotion1",timeout=15)
        if temp_estop_var_vention=="estop/status true":
          popup("MachineMotion in estop, make sure you have all emergency modules released manually. If you continue the system will try to reset MachineMotion automatically.",blocking=True)
        end
      end
    else:
      popup("resource is being used already: MachineMotion1")
      halt
    end
    socket_send_string("GET im_get_controller_pos_axis_1;", "MachineMotion1")
    temp_drive = socket_read_ascii_float(1, "MachineMotion1",timeout=15)
    global var_1 = temp_drive[1]
    isVentionMovementBusyMachineMotion1 = False
    sleep(0.03)
    # end: URCap Program Node
  end
  
  
  def get_lift_column_height_condensed():
    socket_send_string("GET im_get_controller_pos_axis_1;", "MachineMotion1")
    temp_drive = socket_read_ascii_float(1, "MachineMotion1",timeout=15)
    ret = temp_drive[1]
    return ret
  end
  
  
  # Section: Native UR commands ###################################
  
  # this function takes a struct of points as an argument, and checks whether every point in the list is reachable using get_inverse_kin_has_solution()
  # this function does NOT check for weird twists or joint limits
  # inputstruct must contain only points
  # it returns true if all points are valid. it returns false if any points are valid
  # a list of length 0 indicates that all points are valid
  def check_structofpoints_validity(inputstruct):
    # next, check whether the touchpoints are reachable
    structlength = length(inputstruct)
    i = 0
    allvalid = True
    while i < structlength:
      curr = inputstruct[i]
      valid = get_inverse_kin_has_solution(curr)
      if not valid:
        return False
      end
      i = i + 1
    end
    return True
  end
  
  
  # this function takes in a struct of only points. it checks those points for validity.
  # if one of them is not valid, it throws a popup loop
  def check_validity_only(struct2):
    validity = check_structofpoints_validity(struct2)
    if not validity:
      # bad
      popuptext = "Not all weldpoints are valid. "
      # infinite loop
      while 1==1:
        popup(popuptext, title="Position Error",blocking=True)
      end
    end
  end
  
  
  # this function calculates whether a given pose can be reached, and if it can, whether it requires a wrist twist (from the seed joint angles)
  # arguments are target pose (p[x,y,z,rx,ry,rz]) and orig_joints which is the 6 joint angles of a pose that is close by the target pose and has the desired joint angles
  # returns true if the pose is valid and requires no twist. If pose is valid but requires a twist, returns false. If pose is invalid, returns false.
  def can_pose_be_reached_without_twist(pose, orig_joints):
    # first, determine if the pose is valid
    valid = get_inverse_kin_has_solution(pose)
    if not valid:
      return False
    end
    valid = get_inverse_kin_has_solution(pose, orig_joints)
    if not valid:
      return False
    else:
      joints_1 = get_inverse_kin(pose, orig_joints)
      #iterate through the 6 joints
      allGood = True
      i = 0
      structlength = 6
      while i < structlength:
        joint_curr = joints_1[i]
        # check for anything that exceeds joint limits
        degreesmax = 360 * pi / 180
        if joint_curr > degreesmax or joint_curr < degreesmax * -1:
          allGood = False
        end
        # check for anything that is significantly different than the aligned approach. could indicate a twist is needed. we dont want that
        maxdifference = 150 * pi / 180
        difference = joint_curr - orig_joints[i]
        if difference > maxdifference or difference * -1 > maxdifference:
          allGood = False
        end
        i = i + 1
      end
      return allGood
    end
  end
  $ 96 "Script: analyze_floor_corner.script"
  # this file creates the function for analyzing touchpoints
  
  # this is the main entry point for calculations.
  # it takes in the 5 points, analyzes the shape of the box, and then calculates path points and returns them
  # specifically for Down, Over, then Around (DOtA)
  # specifically for right-sided boxes (vertical weld on right side of edge)
  def main_calculate_right(p11, p12, p21, p22, p3, p13, p23, chamferover):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      list1 = analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3)
      struct2 = calculate_DOtA_points_right(struct1, list1, chamferover)
      validity = check_validity_right(struct1, struct2, False)
      return struct2
  end
  
  # this is the main entry point for calculations.
  # it takes in the 5 points, analyzes the shape of the box, and then calculates path points and returns them
  # specifically for Down, Over, then Around (DOtA)
  # specifically for left-sided boxes (vertical weld on left side of edge)
  def main_calculate_left(p11, p12, p21, p22, p3, p13, p23, chamferover):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      list1 = analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3)
      struct2 = calculate_DOtA_points_left(struct1, list1, chamferover)
      validity = check_validity_left(struct1, struct2, False)
      return struct2
  end
  
  # this is the main entry point for calculations, for Floor Corner Extended.
  # it takes in the 7 touchpoints, analyzes the shape of the box.
  # takes in the user defined point for the top of the weld (tcp_pose_top) and then calculates path points
  # loopingly tries to calculate the extension along the sidewall that fulfills get_inverse_kin_has_solution() and provides the farthest extension possible
  # returns the pathpoints
  # specifically for Down, Over, then Around (DOtA)
  # specifically for right-sided boxes (vertical weld on right side of edge)
  def main_calculate_right_extended(p11, p12, p21, p22, p3, p13, p23, chamferover, chamferup, tcp_pose_top):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      list1 = analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3)
      struct2 = calculate_DOtA_points_right_extended(struct1, list1, chamferover, chamferup, tcp_pose_top)
      struct3 = check_validity_right(struct1, struct2, False)
      return struct3
  end
  
  # this is the main entry point for calculations, for Floor Corner Extended.
  # it takes in the 7 touchpoints, analyzes the shape of the box.
  # takes in the user defined point for the top of the weld (tcp_pose_top) and then calculates path points
  # loopingly tries to calculate the extension along the sidewall that fulfills get_inverse_kin_has_solution() and provides the farthest extension possible
  # returns the pathpoints
  # specifically for Down, Over, then Around (DOtA)
  # specifically for left-sided boxes (vertical weld on left side of edge)
  def main_calculate_left_extended(p11, p12, p21, p22, p3, p13, p23, chamferover, chamferup, tcp_pose_top):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      list1 = analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3)
      struct2 = calculate_DOtA_points_left_extended(struct1, list1, chamferover, chamferup, tcp_pose_top)
      struct3 = check_validity_left(struct1, struct2, False)
      return struct3
  end
  
  # this is the main entry point for calculations, for Floor Corner Extended, but on a step so tilt back and ride both of the two exits.
  # it takes in the 7 touchpoints, analyzes the shape of the box.
  # takes in the user defined point for the top of the weld (tcp_pose_top) and then calculates path points
  # returns the pathpoints
  # specifically for Down, Over, then Around (DOtA)
  # specifically for right-sided boxes (vertical weld on right side of edge)
  # the only difference is adding the extra points in struct2, and passing them in check validity
  def main_calculate_right_step_extended(p11, p12, p21, p22, p3, p13, p23, chamferover, chamferup, tcp_pose_top):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      list1 = analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3)
      struct2 = calculate_DOtA_points_right_step_extended(struct1, list1, chamferover, chamferup, tcp_pose_top)
      struct3 = check_validity_right(struct1, struct2, True)
      return struct3
  end
  
  # this is the main entry point for calculations, for Floor Corner Extended, but on a step so tilt back and ride both of the two exits.
  # it takes in the 7 touchpoints, analyzes the shape of the box.
  # takes in the user defined point for the top of the weld (tcp_pose_top) and then calculates path points
  # returns the pathpoints
  # specifically for Down, Over, then Around (DOtA)
  # specifically for left-sided boxes (vertical weld on left side of edge)
  def main_calculate_left_step_extended(p11, p12, p21, p22, p3, p13, p23, chamferover, chamferup, tcp_pose_top):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      list1 = analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3)
      struct2 = calculate_DOtA_points_left_step_extended(struct1, list1, chamferover, chamferup, tcp_pose_top)
      struct3 = check_validity_left(struct1, struct2, True)
      return struct3
  end
  
  # like step_extended(), but includes functionality for starting the program with the lift column already raised
  def main_calculate_right_step_extended2(p11, p12, p21, p22, p3, p13, p23, chamferover, chamferup, tcp_pose_top):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      list1 = analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3)
      struct1 = at_adjust_lch(struct1)
      tcp_pose_top = adjust_tcptop(tcp_pose_top)
      struct2 = calculate_DOtA_points_right_step_extended(struct1, list1, chamferover, chamferup, tcp_pose_top)
      struct3 = check_validity_right(struct1, struct2, True)
      return struct3
  end
  
  # this is the main entry point for calculations, for Floor Corner Extended, but on a step so tilt back and ride both of the two exits.
  # it takes in the 7 touchpoints, analyzes the shape of the box.
  # takes in the user defined point for the top of the weld (tcp_pose_top) and then calculates path points
  # returns the pathpoints
  # specifically for Down, Over, then Around (DOtA)
  # specifically for left-sided boxes (vertical weld on left side of edge)
  def main_calculate_left_step_extended2(p11, p12, p21, p22, p3, p13, p23, chamferover, chamferup, tcp_pose_top):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      list1 = analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3)
      struct1 = at_adjust_lch(struct1)
      tcp_pose_top = adjust_tcptop(tcp_pose_top)
      struct2 = calculate_DOtA_points_left_step_extended(struct1, list1, chamferover, chamferup, tcp_pose_top)
      struct3 = check_validity_left(struct1, struct2, True)
      return struct3
  end
  
  # it takes 5 arguments as points
  # it returns a struct containing: (pointintersect, pointapproach1, pointapproach2, point1, point2, point3, point4, point5, pointreturn1, heading1, heading2, heading3, path2r1, path2r2, path2l1, path2l2)
  # specifically for Around then Up (AtU)
  def analyze_touchpoints(p11, p12, p21, p22, p3):
    # FIND THE INTERSECTION
    # comment get the z
    zcoord=p3[2]
  
    # get the raw points from the first line
    l1p1x=p11[0]
    l1p1y=p11[1]
    l1p2x=p12[0]
    l1p2y=p12[1]
  
    # equate the first line in 2d space
    ml1 = (l1p2y-l1p1y) / (l1p2x-l1p1x)
  
    # b = y - mx
    bl1 = l1p1y - ml1 * l1p1x
  
    # get the raw points from the second line
    l2p1x=p21[0]
    l2p1y=p21[1]
    l2p2x=p22[0]
    l2p2y=p22[1]
  
    # equate the second line in 2d space
    ml2 = (l2p2y-l2p1y) / (l2p2x-l2p1x)
  
    # b = y - mx
    bl2 = l2p1y - ml2 * l2p1x
  
  
    # find the intersection of the two lines
    # m1x+b1 = m2x+b2
    # m1x - m2x = b2 - b1
    # x = (b2-b1) / (m1-m2)
    xintersect = (bl2-bl1) / (ml1-ml2)
    yintersect = ml1 * xintersect + bl1
  
    #FIND THE VECTORS
    #define a vector from the intersection to the second point on the first line
    l1delxfull = l1p2x - xintersect
    l1delyfull = l1p2y - yintersect
  
    l1delmag = sqrt(l1delxfull*l1delxfull + l1delyfull*l1delyfull)
  
    l1delxunit = l1delxfull / l1delmag
    l1delyunit = l1delyfull / l1delmag
  
    #define a vector from the intersection to the second point on the second line
    l2delxfull = l2p2x - xintersect
    l2delyfull = l2p2y - yintersect
  
    l2delmag = sqrt(l2delxfull*l2delxfull + l2delyfull*l2delyfull)
  
    l2delxunit = l2delxfull / l2delmag
    l2delyunit = l2delyfull / l2delmag
  
    # FIND THE FOUR POINTS ON THE LINES
    # find locations 8 inches away from  intersect point
    # CONST
    welddistance = 8
    roundoverdistance = 0.05
    zup = .375
    # inches
    wd = welddistance * 25.4 / 1000
    rod = roundoverdistance * 25.4 / 1000
    zup = zup * 25.4 / 1000
  
    # now we have the unit vector. extend the weld distance from the intersection
    x = xintersect + l1delxunit * wd
    y = yintersect + l1delyunit * wd
    z = zcoord + zup
  
    point1 = p[x,y,z,1.570796,0,0] # dummy orientation for now
  
    x = xintersect + l1delxunit * rod
    y = yintersect + l1delyunit * rod
  
    point2 = p[x,y,z,1.570796,0,0]
  
    # now we have the unit vector. extend the weld distance from the intersection
    x = xintersect + l2delxunit * wd
    y = yintersect + l2delyunit * wd
  
    point5 = p[x,y,z,0,-1.570796,0]
  
    x = xintersect + l2delxunit * rod
    y = yintersect + l2delyunit * rod
  
    point4 = p[x,y,z,0,-1.570796,0]
  
    #DEFINE APPROACH POINTS
    pointintersect = p[xintersect,yintersect,zcoord,0,0,0]
    pointapproach1 = p[xintersect+0.1,yintersect+0.1,z,1.570796,0,0]
    pointapproach2 = p[point1[0], point1[1]+0.1, point1[2], point1[3], point1[4], point1[5]]
    pointreturn1 = p[point5[0]+0.1, point5[1], point5[2], point5[3], point5[4], point5[5]]
  
    #FIND HEADINGS
    #for each heading, find the angle of the line with respect to the pos x axis. then add/subtract 90 degrees because you want to be perpendicular to that
    headingvector1 = convert_uv_to_heading(l1delxunit, l1delyunit)
    headingvector2 = convert_uv_to_heading(l2delxunit, l2delyunit)
    # find halfway heading
    heading2 = (headingvector1 + headingvector2)/2
    # find headings that the robot should face while traveling, perpendicular to the vectors of the sides of the box
    heading1 = headingvector1 + pi/2
    heading3 = headingvector2 - pi/2
  
    #FIND POINT 3
    #see if we have to / can find point 3
    findpoint3 = True
    if roundoverdistance == 0:
      findpoint3 = False
    end
    if findpoint3:
      # i need to find the point3 such that the arc from p2 to p3 to p4 is tangent to p1-p2 and p4-p5. making this a smooth path will be good
      # the direction of movement is from pointintersect in the direction of heading2
      # how much movement though? this will depend on whether it is actually a 90 degree angle or not.
      # first, find the perpendicular lines through points 2 and 4
      perp2 = find_perpendicular_line(ml1, point2[0], point2[1])
      perp4 = find_perpendicular_line(ml2, point4[0], point4[1])
      # next, find the intersection of those two lines
      perpintersect = find_intersection(perp2[0], perp2[1], perp4[0], perp4[1])
      radiusofcircle = distance_between(perpintersect[0], perpintersect[1], 0, point2[0], point2[1], 0)
      # find a vector the direction of heading2
      uvx = cos(heading2)
      uvy = sin(heading2)
      # compute point3. pass in negative radius because the direction is into the tank but we want to move from the intersection out to the rounded edge
      point3coords = add_vectordistance_to_point(perpintersect[0], perpintersect[1], z, uvx, uvy, 0, -1 * radiusofcircle)
      point3 = p[point3coords[0], point3coords[1], point3coords[2], 0, 0, 0]
    end
  
    #APPLY ACTUAL RXRYRZ TO POINTS
    # convert the headings to rxryrz and insert those values into the relevant points
    rxryrz = convert_heading_to_axang(heading1)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    pointapproach1 = p[pointapproach1[0], pointapproach1[1], pointapproach1[2], rx, ry, rz]
    pointapproach2 = p[pointapproach2[0], pointapproach2[1], pointapproach2[2], rx, ry, rz]
    point1 = p[point1[0], point1[1], point1[2], rx, ry, rz]
    point2 = p[point2[0], point2[1], point2[2], rx, ry, rz]
    rxryrz = convert_heading_to_axang(heading2)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    if findpoint3:
      point3 = p[point3[0], point3[1], point3[2], rx, ry, rz]
    else:
      point3 = point2
    end
    rxryrz = convert_heading_to_axang(heading3)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    point4 = p[point4[0], point4[1], point4[2], rx, ry, rz]
    point5 = p[point5[0], point5[1], point5[2], rx, ry, rz]
    pointreturn1 = p[pointreturn1[0], pointreturn1[1], pointreturn1[2], rx, ry, rz]
  
    #find path2 (the part that goes up)
    four_vertical_points = find_vertical_points(pointintersect, l1delxunit, l1delyunit, l2delxunit, l2delyunit, zup, wd, heading1, heading3)
    path2r1 = four_vertical_points[0]
    path2r2 = four_vertical_points[1]
    path2l1 = four_vertical_points[2]
    path2l2 = four_vertical_points[3]
  
    #RETURN STRUCT
    ret = struct(pointintersect=pointintersect, pointapproach1=pointapproach1, pointapproach2=pointapproach2, point1=point1, point2=point2, point3=point3, point4=point4, point5=point5, pointreturn1=pointreturn1, heading1=heading1, heading2=heading2, heading3=heading3, path2r1=path2r1, path2r2=path2r2, path2l1=path2l1, path2l2=path2l2)
    return ret
  end
  
  # this function finds the points (and rxryrz) of the 2 points (start and end) of vertical weld section
  # used in original analyze_touchpoints() function
  def find_vertical_points(pointintersect, l1delxunit, l1delyunit, l2delxunit, l2delyunit, offset, wd, heading1, heading3):
  
    # find right side stuff
    # find the point in 3d space that is .375 up and .375 over
    x = pointintersect[0] + l1delxunit * offset
    y = pointintersect[1] + l1delyunit * offset
    z = pointintersect[2] + offset
    # find rxryrz
    rxryrz = convert_heading_to_axang_preheatup(heading1)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    path2r1 = p[x, y, z, rx, ry, rz]
    path2r2 = p[x, y, z + wd, rx, ry, rz]
  
    # find left side
    # find the point in 3d space that is .375 up and .375 over
    x = pointintersect[0] + l2delxunit * offset
    y = pointintersect[1] + l2delyunit * offset
    z = pointintersect[2] + offset
    # find rxryrz
    rxryrz = convert_heading_to_axang_preheatup(heading3)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    path2l1 = p[x, y, z, rx, ry, rz]
    path2l2 = p[x, y, z + wd, rx, ry, rz]
  
    ret = struct(path2r1=path2r1, path2r2=path2r2, path2l1=path2l1, path2l2=path2l2)
    return ret
  end
  
  # it takes 5 arguments as points
  # it returns a struct containing: (pointintersect, heading1, heading2, heading3, l1delxunit, l1delyunit, l2delxunit, l2delyunit)
  def analyze_touchpoints_only(p11, p12, p21, p22, p3):
    # FIND THE INTERSECTION
    # comment get the z
    zcoord=p3[2]
  
    # get the raw points from the first line
    l1p1x=p11[0]
    l1p1y=p11[1]
    l1p2x=p12[0]
    l1p2y=p12[1]
  
    # equate the first line in 2d space
    ml1 = (l1p2y-l1p1y) / (l1p2x-l1p1x)
  
    # b = y - mx
    bl1 = l1p1y - ml1 * l1p1x
  
    # get the raw points from the second line
    l2p1x=p21[0]
    l2p1y=p21[1]
    l2p2x=p22[0]
    l2p2y=p22[1]
  
    # equate the second line in 2d space
    ml2 = (l2p2y-l2p1y) / (l2p2x-l2p1x)
  
    # b = y - mx
    bl2 = l2p1y - ml2 * l2p1x
  
  
    # find the intersection of the two lines
    # m1x+b1 = m2x+b2
    # m1x - m2x = b2 - b1
    # x = (b2-b1) / (m1-m2)
    xintersect = (bl2-bl1) / (ml1-ml2)
    yintersect = ml1 * xintersect + bl1
  
    pointintersect = p[xintersect,yintersect,zcoord,0,0,0]
  
    #FIND THE VECTORS
    #define a vector from the intersection to the second point on the first line
    l1delxfull = l1p2x - xintersect
    l1delyfull = l1p2y - yintersect
  
    l1delmag = sqrt(l1delxfull*l1delxfull + l1delyfull*l1delyfull)
  
    l1delxunit = l1delxfull / l1delmag
    l1delyunit = l1delyfull / l1delmag
  
    #define a vector from the intersection to the second point on the second line
    l2delxfull = l2p2x - xintersect
    l2delyfull = l2p2y - yintersect
  
    l2delmag = sqrt(l2delxfull*l2delxfull + l2delyfull*l2delyfull)
  
    l2delxunit = l2delxfull / l2delmag
    l2delyunit = l2delyfull / l2delmag
  
    #FIND HEADINGS
    #for each heading, find the angle of the line with respect to the pos x axis. then add/subtract 90 degrees because you want to be perpendicular to that
    headingvector1 = convert_uv_to_heading(l1delxunit, l1delyunit)
    headingvector2 = convert_uv_to_heading(l2delxunit, l2delyunit)
    # find halfway heading
    heading2 = (headingvector1 + headingvector2)/2
    # find headings that the robot should face while traveling, perpendicular to the vectors of the sides of the box
    heading1 = headingvector1 + pi/2
    heading3 = headingvector2 - pi/2
  
    #RETURN STRUCT
    ret = struct(pointintersect=pointintersect, heading1=heading1, heading2=heading2, heading3=heading3, l1delxunit=l1delxunit, l1delyunit=l1delyunit, l2delxunit=l2delxunit, l2delyunit=l2delyunit)
    return ret
  end
  
  # given a struct from analyze_touchpoints_only(), calculate the points
  # for right, for non-extended
  def calculate_DOtA_points_right(struct1, listleans, chamferover):
      # get the stuff from the struct
      pointintersect = struct1[0]
      heading1 = struct1[1]
      heading2 = struct1[2]
      heading3 = struct1[3]
      l1delxunit = struct1[4]
      l1delyunit = struct1[5]
      l2delxunit = struct1[6]
      l2delyunit = struct1[7]
  
      # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
      # find locations 8 inches away from  intersect point
      # CONST
      welddistance1 = 8 # vertical weld distance
      welddistance2 = 6 # first path second leg
      welddistance3 = 8 # second path second leg
      zup = .375
      # inches
      wd1 = welddistance1 * 25.4 / 1000
      wd2 = welddistance2 * 25.4 / 1000
      wd3 = welddistance3 * 25.4 / 1000
      zup = zup * 25.4 / 1000
      chamferovermm =  chamferover * 25.4 / 1000
  
      x = pointintersect[0] + l1delxunit * chamferovermm
      y = pointintersect[1] + l1delyunit * chamferovermm
      z = pointintersect[2] + zup
  
      #apply actual rxryrz to points
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_preheatdown(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point1 = p[x + wd1*listleans[0], y + wd1*listleans[1], z + wd1, rx, ry, rz] # add in the listleans factor to follow the face of the box as we move up
      point2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point4 = p[x, y, z, rx, ry, rz]
      x = x + l1delxunit * wd2
      y = y + l1delyunit * wd2
      point5 = p[x, y, z, rx, ry, rz]
  
      # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
      roundoverdistance = 0.05
      rod = roundoverdistance * 25.4 / 1000
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l1delxunit * chamferovermm
      y = pointintersect[1] + l1delyunit * chamferovermm
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_1 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l1delxunit * rod
      y = pointintersect[1] + l1delyunit * rod
      point_2 = p[x, y, z, rx, ry, rz]
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l2delxunit * wd3
      y = pointintersect[1] + l2delyunit * wd3
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_5 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l2delxunit * rod
      y = pointintersect[1] + l2delyunit * rod
      point_4 = p[x, y, z, rx, ry, rz]
  
      #FIND POINT 3
      # by calling analyze_touchpoints()
      atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
      point_3 = atret[5]
  
  
      struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5)
      return struct2
  end
  
  # given a struct from analyze_touchpoints_only(), calculate the points
  # for left, for non-extended
  def calculate_DOtA_points_left(struct1, listleans, chamferover):
      # get the stuff from the struct
      pointintersect = struct1[0]
      heading1 = struct1[1]
      heading2 = struct1[2]
      heading3 = struct1[3]
      l1delxunit = struct1[4]
      l1delyunit = struct1[5]
      l2delxunit = struct1[6]
      l2delyunit = struct1[7]
  
      # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
      # find locations 8 inches away from  intersect point
      # CONST
      welddistance1 = 8 # vertical weld distance
      welddistance2 = 6 # first path second leg
      welddistance3 = 8 # second path second leg
      zup = .375
      # inches
      wd1 = welddistance1 * 25.4 / 1000
      wd2 = welddistance2 * 25.4 / 1000
      wd3 = welddistance3 * 25.4 / 1000
      zup = zup * 25.4 / 1000
      chamferovermm =  chamferover * 25.4 / 1000
  
      x = pointintersect[0] + l2delxunit * chamferovermm
      y = pointintersect[1] + l2delyunit * chamferovermm
      z = pointintersect[2] + zup
  
      #apply actual rxryrz to points
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_preheatdown(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point1 = p[x + wd1*listleans[0], y + wd1*listleans[1], z + wd1, rx, ry, rz]
      point2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point4 = p[x, y, z, rx, ry, rz]
      x = x + l2delxunit * wd2
      y = y + l2delyunit * wd2
      point5 = p[x, y, z, rx, ry, rz]
  
      # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
      roundoverdistance = 0.05
      rod = roundoverdistance * 25.4 / 1000
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l2delxunit * chamferovermm
      y = pointintersect[1] + l2delyunit * chamferovermm
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_1 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l2delxunit * rod
      y = pointintersect[1] + l2delyunit * rod
      point_2 = p[x, y, z, rx, ry, rz]
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l1delxunit * wd3
      y = pointintersect[1] + l1delyunit * wd3
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_5 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l1delxunit * rod
      y = pointintersect[1] + l1delyunit * rod
      point_4 = p[x, y, z, rx, ry, rz]
  
      #FIND POINT 3
      # by calling analyze_touchpoints()
      atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
      point_3 = atret[5]
      #point 3 will not have the correct rxryrz though because now the gun needs to be face up.
      rxryrz = convert_heading_to_axang_ccw(heading2)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_3 = p[point_3[0], point_3[1], point_3[2], rx, ry, rz]
  
      struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5)
      return struct2
  end
  
  # given a struct from analyze_touchpoints_only(), calculate the points
  # for right, for extended
  def calculate_DOtA_points_right_extended(struct1, listleans, chamferover, chamferup, tcp_pose_top):
      # get the stuff from the struct
      pointintersect = struct1[0]
      heading1 = struct1[1]
      heading2 = struct1[2]
      heading3 = struct1[3]
      l1delxunit = struct1[4]
      l1delyunit = struct1[5]
      l2delxunit = struct1[6]
      l2delyunit = struct1[7]
  
      # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
      # find locations 8 inches away from  intersect point
      # CONST
      # welddistance1 = 8 # vertical weld distance
      welddistance2 = 5 # first path second leg
      welddistance3 = 5 # second path second leg
  
      # inches
      # wd1 = welddistance1 * 25.4 / 1000
      wd2 = welddistance2 * 25.4 / 1000
      wd3 = welddistance3 * 25.4 / 1000
      zup = chamferup * 25.4 / 1000
      chamferovermm =  chamferover * 25.4 / 1000
  
      # weld distance is the distance that it will weld. this will make it start at the z height that the user specified
      wd1 = tcp_pose_top[2] - pointintersect[2] - zup
  
      x = pointintersect[0] + l1delxunit * chamferovermm
      y = pointintersect[1] + l1delyunit * chamferovermm
      z = pointintersect[2] + zup
  
      #apply actual rxryrz to points
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_preheatdown(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point1 = p[x + wd1*listleans[0], y + wd1*listleans[1], z + wd1, rx, ry, rz] # add in the listleans factor to follow the face of the box as we move up
      point2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point4 = p[x, y, z, rx, ry, rz]
      x = x + l1delxunit * wd2
      y = y + l1delyunit * wd2
      point5 = p[x, y, z, rx, ry, rz]
  
      # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
      roundoverdistance = 0.05
      rod = roundoverdistance * 25.4 / 1000
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l1delxunit * chamferovermm
      y = pointintersect[1] + l1delyunit * chamferovermm
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_1 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l1delxunit * rod
      y = pointintersect[1] + l1delyunit * rod
      point_2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      x = pointintersect[0] + l2delxunit * rod
      y = pointintersect[1] + l2delyunit * rod
      point_4 = p[x, y, z, rx, ry, rz]
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l2delxunit * wd3
      y = pointintersect[1] + l2delyunit * wd3
      point_5 = p[x, y, z, rx, ry, rz]
  
      #FIND POINT 3
      # by calling analyze_touchpoints()
      atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
      atret5 = atret[5]
      point_3 = p[atret5[0], atret5[1], z, atret5[3], atret5[4], atret5[5]]
  
  
      struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5)
      return struct2
  end
  
  # given a struct from analyze_touchpoints_only(), calculate the points
  # for left, for extended
  def calculate_DOtA_points_left_extended(struct1, listleans, chamferover, chamferup, tcp_pose_top):
      # get the stuff from the struct
      pointintersect = struct1[0]
      heading1 = struct1[1]
      heading2 = struct1[2]
      heading3 = struct1[3]
      l1delxunit = struct1[4]
      l1delyunit = struct1[5]
      l2delxunit = struct1[6]
      l2delyunit = struct1[7]
  
      # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
      # find locations 8 inches away from  intersect point
      # CONST
      # welddistance1 = 8 # vertical weld distance
      welddistance2 = 5 # first path second leg
      welddistance3 = 5 # second path second leg
  
      # inches
      # wd1 = welddistance1 * 25.4 / 1000
      wd2 = welddistance2 * 25.4 / 1000
      wd3 = welddistance3 * 25.4 / 1000
      zup = chamferup * 25.4 / 1000
      chamferovermm =  chamferover * 25.4 / 1000
  
      # weld distance is the distance that it will weld. this will make it start at the z height that the user specified
      wd1 = tcp_pose_top[2] - pointintersect[2] - zup
  
      x = pointintersect[0] + l2delxunit * chamferovermm
      y = pointintersect[1] + l2delyunit * chamferovermm
      z = pointintersect[2] + zup
  
      #apply actual rxryrz to points
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_preheatdown(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point1 = p[x + wd1*listleans[0], y + wd1*listleans[1], z + wd1, rx, ry, rz]
      point2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point4 = p[x, y, z, rx, ry, rz]
      x = x + l2delxunit * wd2
      y = y + l2delyunit * wd2
      point5 = p[x, y, z, rx, ry, rz]
  
      # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
      roundoverdistance = 0.05
      rod = roundoverdistance * 25.4 / 1000
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l2delxunit * chamferovermm
      y = pointintersect[1] + l2delyunit * chamferovermm
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_1 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l2delxunit * rod
      y = pointintersect[1] + l2delyunit * rod
      point_2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      x = pointintersect[0] + l1delxunit * rod
      y = pointintersect[1] + l1delyunit * rod
      point_4 = p[x, y, z, rx, ry, rz]
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l1delxunit * wd3
      y = pointintersect[1] + l1delyunit * wd3
      point_5 = p[x, y, z, rx, ry, rz]
  
      #FIND POINT 3
      # by calling analyze_touchpoints()
      atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
      point_3 = atret[5]
      #point 3 will not have the correct rxryrz though because now the gun needs to be face up
      rxryrz = convert_heading_to_axang_ccw(heading2)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_3 = p[point_3[0], point_3[1], z, rx, ry, rz]
  
      struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5)
      return struct2
  end
  
  # this function analyzes the vertical points
  # calculates the slope of the edge in question
  # specifically, for each inch up in the z direction, what is the change in x and change in y direction
  # returns a list of [nx, ny]
  def analyze_vertical_touchpoints(p11, p12, p13, p21, p22, p23, p3):
      # first, find the equations of the planes from the 6 points
      plane1 = findplane(p11, p12, p13)
      plane2 = findplane(p21, p22, p23)
      # Find the Direction Vector of the Line: The direction vector d of the line of intersection can be found by taking the cross product of the normal vectors of each plane (a, b, and c)
      nx = plane1[1]*plane2[2] - plane1[2]*plane2[1]
      ny = plane1[2]*plane2[0] - plane1[0]*plane2[2]
      nz = plane1[0]*plane2[1] - plane1[1]*plane2[0]
      # normalize the vector so the z length is 1
      multiplier = 1 / nz
      nx = nx * multiplier
      ny = ny * multiplier
      nz = nz * multiplier # should become equal to 1
      ret = [nx, ny]
      return ret
  end
  
  # this function is for getting the points along the path of the corner homing 45
  # point0 is the point where they touched
  def get_corner_homing_45_pathpoints(point0, pointtop = p[0,0,0,0,0,0]):
    p0x = point0[0]
    p0y = point0[1]
    p0z = point0[2]
    p0rx = point0[3]
    p0ry = point0[4]
    p0rz = point0[5]
  
    #constants
    #distances of how far away from point the touchpoints are
    d0 = 0.10 # how far from the box to retreat and approach
    d1 = 0.06 # first distance from init point
    d2 = 0.15 # second distance from init point
    d3 = 0.125 #vertical distance from first point
    sqrt2 = 0.707106781 # 1/sqrt(2) , the inverse of the sqrt(2)
  
    ph1 = p[p0x + d0, p0y, p0z + d1, p0rx, p0ry, p0rz] #approach point for turn
  
    ph2 = p[p0x+d0-d0*0.5-sqrt2*d1, p0y+d0*0.5+sqrt2*d1, p0z+d1, 1.446, -0.8, -0.733]
    ph3 = p[p0x+d0-d0*0.5-sqrt2*d2, p0y+d0*0.5+sqrt2*d2, p0z+d1, 1.446, -0.8, -0.733]
    ph4 = p[p0x+d0-d0*0.5-sqrt2*d1, p0y-d0*0.5-sqrt2*d1, p0z+d1, 0.626, -1.993, -1.813]
    ph5 = p[p0x+d0-d0*0.5-sqrt2*d2, p0y-d0*0.5-sqrt2*d2, p0z+d1, 0.626, -1.993, -1.813]
  
    # go back to ph1
    ph6 = p[p0x + d0, p0y, p0z -0.05, 0, 0, 0] # approach point for under turn
    # moveL from ph1 to ph6
    ph7 = p[p0x-d1, p0y, p0z-0.05, 0, 0, 0]
  
    # add the vertical touch points
    if pointtop[2] == 0:
      ph2up = p[ph2[0], ph2[1], ph2[2]+d3, ph2[3], ph2[4], ph2[5]]
      ph4up = p[ph4[0], ph4[1], ph4[2]+d3, ph4[3], ph4[4], ph4[5]]
    elif (pointtop[2] > p0z + 0.614) and (pointtop[2] > 0.914): # 0.914m = 36 inches
      ph2up = p[ph2[0], ph2[1], 0.914, ph2[3], ph2[4], ph2[5]]
      ph4up = p[ph4[0], ph4[1], 0.914, ph4[3], ph4[4], ph4[5]]
    else:
      ph2up = p[ph2[0], ph2[1], pointtop[2], ph2[3], ph2[4], ph2[5]]
      ph4up = p[ph4[0], ph4[1], pointtop[2], ph4[3], ph4[4], ph4[5]]
    end
    ret = struct(ph1=ph1, ph2=ph2, ph3=ph3, ph4=ph4, ph5=ph5, ph6=ph6, ph7=ph7, ph2up=ph2up, ph4up=ph4up)
    is_robot_at_reachable_spot(point0, ret)
    is_robot_position_likely_invalid(point0)
    return ret
  end
  
  # this function checks whether the touchpoints are reachable AKA is the robot positioned in the right spot
  # if everything looks good, it continues.
  # if it detects a problem, it infinite loops a popup
  def is_robot_at_reachable_spot(point0, struct_touchpoints, structlength = 9):
    # first, check whether the corner is too low to the ground that the bottom homing will hit the ground (z < -400)
    lc_height = get_lift_column_height_condensed()
    # total height = zeroed lift column height (41.25 inches) (1.04775 m) plus lift column height plus robot relative height
    totalheight = 1.04775 + lc_height + point0[2]
    if totalheight < 1.04775 - 0.400:
      # bad
      popuptext = "Tank Corner is too low to the ground. Collisions will occur. Stop Program and raise tank. "
      # infinite loop
      while 1==1:
        popup(popuptext, title="Robot Positioning Warning",blocking=True)
      end
    end
  
    # next, check whether the touchpoints are reachable
    allvalid = check_structofpoints_validity(struct_touchpoints)
    if not allvalid:
  
      # then unreachable
      # generate message
      listproblems = ""
      listnames = ["ph1", "ph2", "ph3", "ph4", "ph5", "ph6", "ph7", "ph2up", "ph4up"]
      i = 0
      # structlength = 9 # used to be a declare statement here. now it is a parameter. floor corner has 9. other features have less
      while i < structlength:
        curr = struct_touchpoints[i]
        valid = get_inverse_kin_has_solution(curr)
        if not valid:
          listproblems = listproblems + listnames[i]
        end
        i = i + 1
      end
      # display
      popuptext = "Robot is too far from tank corner. Cannot reach some necessary positions. Stop Program and move robot closer. " + listproblems
      # infinite loop
      while 1==1:
        popup(popuptext, title="Robot Positioning Warning",blocking=True)
      end
    end
  end
  
  # checks the validity of all points during a left weld
  # takes 2 arguments: struct1 (struct1[0] has to contain pointintersect) and struct2 (contains all the points (9) of the weld path)
  # third argument is boolean. does struct2 have additional points because of step weld tiltback and ride?
  def check_validity_left(struct1, struct2, stepyesno):
    #first, check whether robot is too close
    pointintersect = struct1[0]
    toocloseleftweld = False # init value
    # next, check if the z is low or high. use the old formula for tooclose if z is low, but use new more lax formula is z is high
    if pointintersect[2] < 0.250:
      # next, check if the corner is too close to the robot to do a left around weld (complex but approximately X > -1300)
      # if y < 0, then x < -1300. if y < 480, then y > (1300+x)*8. if y > 480, then y > (1235+x)*4 + 500
  
      if pointintersect[1] < 0:
        if pointintersect[0] > -1.300:
          toocloseleftweld = True
        end
      elif pointintersect[1] < 0.480:
        if pointintersect[1] < (1.300 + pointintersect[0])*8:
          toocloseleftweld = True
        end
      else:
        if pointintersect[1] < (1.235 + pointintersect[0])*4 + 0.500:
          toocloseleftweld = True
        end
      end
      #popup("low corner")
    else:
      if pointintersect[0] > -1.100:
        toocloseleftweld = True
        #popup("high corner fail")
      end
      #popup("high corner")
    end
  
    if toocloseleftweld:
      # bad
      popuptext = "Robot is too close to tank corner. Collisions may occur. Stop Program and move robot farther. "
      # infinite loop
      while 1==1:
        popup(popuptext, title="Robot Positioning Warning",blocking=True)
      end
    end
  
    #next, check whether all the points in the weldpath are valid
    structlength = 9
    i = 0
    allvalid = True
    listproblems = ""
    listnames = ["point1", "point2", "point4", "point5", "point_1", "point_2", "point_3", "point_4", "point_5"]
    while i < structlength:
      curr = struct2[i]
      valid = get_inverse_kin_has_solution(curr)
      if not valid:
        if i > 0: # skip the first point, because if it's not valid it can become valid by lifting.
          allvalid = False
          listproblems = listproblems + listnames[i]
        end
      end
      i = i + 1
    end
  
    if not allvalid:
      # display
      popuptext = "Robot is too far from tank corner. Cannot reach some necessary positions. Stop Program and move robot closer. " + listproblems
      # infinite loop
      while 1==1:
        popup(popuptext, title="Robot Positioning Warning",blocking=True)
      end
    end
  
    # check whether the path involves weird turns or joint limits. currently just checks the first position
    p_prev = [-0.021118, -1.26292, 2.43578, 5.07088, -2.29912, 1.53362] #last point of left weld prerotate
    p1valid = get_inverse_kin_has_solution(struct2[0])
    if p1valid:
        joints_1 = get_inverse_kin(struct2[0], p_prev) # struct2[0] is point1
    else:
        joints_1 = [0, 0, 0, 0, 0, 100] # if invalid, force correction without throwing an error
    end
    allGood = True
    i = 0
    structlength = 6
    while i < structlength:
      joint_curr = joints_1[i]
      # check for anything that exceeds joint limits
      degreesmax = 360 * pi / 180
      if joint_curr > degreesmax or joint_curr < degreesmax * -1:
        allGood = False
      end
      # check for anything that is significantly different than the aligned approach. could indicate a twist is needed. we dont want that
      maxdifference = 150 * pi / 180
      difference = joint_curr - p_prev[i]
      if difference > maxdifference or difference * -1 > maxdifference:
        allGood = False
      end
      i = i + 1
    end
  
    if not allGood:
      # call lift column extend function
      if stepyesno:
          struct2 = floor_corner_lift_column_extend_left_tilt(struct2)
      else:
          struct2 = floor_corner_lift_column_extend_left(struct2)
      end
  
  
    end
  
    # return struct2 back
    return struct2
  end
  
  # checks the validity of all points during a right weld
  def check_validity_right(struct1, struct2, stepyesno):
    # first, check whether the right pivot will bonk itself
    pointintersect = struct1[0]
    heading1 = struct1[1] # this is the direction that the welder will face when doing the right side of the box
  
    #first, check whether the heading is just too far offset
    # more than 15 degrees off of 45 is too much
    # normal heading is 216 degrees
    #201 degrees to 231 degrees
    heading1degrees = heading1 * 180 / pi
    if heading1degrees < 186 or heading1degrees > 246 :
      # then out of range
      popuptext = "Robot is not aligned at a 45 degree angle of corner (15 degree leeway). Collisions may occur. Stop Program and align robot. heading1degrees=" + str_cat("",heading1degrees)
      # infinite loop
      while 1==1:
        popup(popuptext, title="Robot Positioning Warning",blocking=True)
      end
      # popup(popuptext, title="Robot Positioning Warning",blocking=True)
    end
  
    #TODO: add the checks for whether x is too close, given the heading
    # add checks for whether x is too close, given the heading
    # different equations for whether heading offset > 5 degrees or less (inc. negative)
    headingoffset = heading1degrees - 216
    if headingoffset < 5:
      # then calculate a and b
      a = 0.4584 + -0.02369 * headingoffset
      b = (-1151.4 + 13.83 * headingoffset) / 1000
      # check whether x > a*y+b
      if pointintersect[0] > a * pointintersect[1] + b:
        # bad
        popuptext = "Robot is too close to tank corner or not at the right angle. Collisions may occur. Stop Program and align robot. "
        # infinite loop
        while 1==1:
          popup(popuptext, title="Robot Positioning Warning",blocking=True)
        end
      end
    else:
      # headingoffset > 5 degrees
      if pointintersect[1] < 0:
        if pointintersect[0] > -1150.0 / 1000.0:
          #bad
          popuptext = "Robot is too close to tank corner. Collisions may occur. Stop Program and align robot. "
          # infinite loop
          while 1==1:
            popup(popuptext, title="Robot Positioning Warning",blocking=True)
          end
        end
      else:
        # if x > .7736 y - 1101.9 then bad
        if pointintersect[0] > 0.7736 * pointintersect[1] - 1101.9 / 1000:
          popuptext = "Robot is too close to tank corner. Collisions may occur. Stop Program and align robot. "
          # infinite loop
          while 1==1:
            popup(popuptext, title="Robot Positioning Warning",blocking=True)
          end
        end
      end
    end
  
    #next, check whether all the points in the weldpath are valid
    structlength = 9
    i = 0
    allvalid = True
    listproblems = ""
    listnames = ["point1", "point2", "point4", "point5", "point_1", "point_2", "point_3", "point_4", "point_5"]
    while i < structlength:
      curr = struct2[i]
      valid = get_inverse_kin_has_solution(curr)
      if not valid:
        if i > 0:
          allvalid = False
          listproblems = listproblems + listnames[i]
        end
      end
      i = i + 1
    end
  
    if not allvalid:
      # display
      popuptext = "Robot is too far from tank corner. Cannot reach some necessary positions. Stop Program and move robot closer. " + listproblems
      # infinite loop
      while 1==1:
        popup(popuptext, title="Robot Positioning Warning",blocking=True)
      end
    end
  
    # check whether the path involves weird turns or joint limits. first position
    p_prev = [-1.13307, -1.48911, 2.84785, 4.92357, -4.89059, 1.57184] #last point of right weld prerotate
    p1valid = get_inverse_kin_has_solution(struct2[0])
    if p1valid:
        joints_1 = get_inverse_kin(struct2[0], p_prev) # struct2[0] is point1
    else:
        joints_1 = [0, 0, 0, 0, 0, 100] # force correction, without throwing an error
    end
    allGood = True
    i = 0
    structlength = 6
    while i < structlength:
      joint_curr = joints_1[i]
      # check for anything that exceeds joint limits
      degreesmax = 360 * pi / 180
      if joint_curr > degreesmax or joint_curr < degreesmax * -1:
        allGood = False
      end
      # check for anything that is significantly different than the aligned approach. could indicate a twist is needed. we dont want that
      maxdifference = 150 * pi / 180
      difference = joint_curr - p_prev[i]
      if difference > maxdifference or difference * -1 > maxdifference:
        allGood = False
      end
      i = i + 1
    end
  
    if not allGood:
      if stepyesno:
          struct2 = floor_corner_lift_column_extend_right(struct2, True)
      else:
          struct2 = floor_corner_lift_column_extend_right(struct2, False)
      end
    end
  
    if not stepyesno:
        # check whether the path involves weird turns or joint limits. final position (end of leg 3)
        joints_raa4 = [-0.8909156958209437, -1.3431089532426377, 2.273750130330221, 0.7266384798237304, 1.5611975193023682, 1.8127720355987549]
        joints_p_3 = get_inverse_kin(struct2[6], joints_raa4) # struct2[6] is p_3
        joints_p_4 = get_inverse_kin(struct2[7], joints_p_3) # struct2[7] is p_4
        joints_p_5 = get_inverse_kin(struct2[8], joints_p_4) # struct2[8] is p_5
        joints_1 = joints_p_5
        p_prev = joints_p_4
        allGood = True
        i = 0
        structlength = 6
        while i < structlength:
          joint_curr = joints_1[i]
          # check for anything that exceeds joint limits
          degreesmax = 360 * pi / 180
          if joint_curr > degreesmax or joint_curr < degreesmax * -1:
            allGood = False
          end
          # check for anything that is significantly different than the aligned approach. could indicate a twist is needed. we dont want that
          maxdifference = 150 * pi / 180
          difference = joint_curr - p_prev[i]
          if difference > maxdifference or difference * -1 > maxdifference:
            allGood = False
          end
          i = i + 1
        end
  
        if not allGood:
          struct2 = floor_corner_right_p_3_reduce(struct2)
        end
    end
    # return struct2 back
    return struct2
  end
  
  def floor_corner_lift_column_extend_right(struct2, stepyesno):
    # we know that p1 cannot be accessed without a twist
    # calculate the height needed to get to p1
    liftcolumnincrement = 2.0 # mm
    enoughHeightAdded = False
    liftColumnHeightTest = 0
    while not enoughHeightAdded:
      liftColumnHeightTest = liftColumnHeightTest + liftcolumnincrement
      # set the orig_joints for p1. p1 demo was joint angles of [-0.45, -31.79, 56.47, 333.06, -130.98, 87.87] (degrees)
      # which equals [-0.007853981633974475, -0.5548401692089968, 0.985587428601197, 5.812993606692308, -2.28603225426217, 1.5336208137274159]
      orig_joints = [-0.007853981633974475, -0.5548401692089968, 0.985587428601197, 5.812993606692308, -2.28603225426217, 1.5336208137274159]
      # get the modified point:
      origp1 = struct2[0]
      testp1 = p[origp1[0], origp1[1], origp1[2] - liftColumnHeightTest / 1000.0, origp1[3], origp1[4], origp1[5]]
      testpa1 = p[origp1[0]+0.05, origp1[1]+0.05, origp1[2] - liftColumnHeightTest / 1000, origp1[3], origp1[4], origp1[5]]
      enoughHeightAdded = can_pose_be_reached_without_twist(testp1, orig_joints) and can_pose_be_reached_without_twist(testpa1, orig_joints)
    end
  
    liftcolumnzneeded = liftColumnHeightTest
  
    origp2 = struct2[1]
    testp2 = p[origp2[0], origp2[1], origp2[2] - liftColumnHeightTest / 1000.0, origp2[3], origp2[4], origp2[5]]
    origp4 = struct2[2]
    testp4 = p[origp4[0], origp4[1], origp4[2] - liftColumnHeightTest / 1000, origp4[3], origp4[4], origp4[5]]
    origp5 = struct2[3]
    testp5 = p[origp5[0], origp5[1], origp5[2] - liftColumnHeightTest / 1000, origp5[3], origp5[4], origp5[5]]
    if stepyesno:
      origp6 = struct2[9]
      testp6 = p[origp6[0], origp6[1], origp6[2] - liftColumnHeightTest / 1000, origp6[3], origp6[4], origp6[5]]
      origp7 = struct2[10]
      testp7 = p[origp7[0], origp7[1], origp7[2] - liftColumnHeightTest / 1000, origp7[3], origp7[4], origp7[5]]
      origp8 = struct2[11]
      testp8 = p[origp8[0], origp8[1], origp8[2] - liftColumnHeightTest / 1000, origp8[3], origp8[4], origp8[5]]
      p_6 = struct2[12]
      p_7 = struct2[13]
      p_8 = struct2[14]
      ret = struct(point1=testp1,point2=testp2,point4=testp4,point5=testp5,point_1=struct2[4],point_2=struct2[5],point_3=struct2[6],point_4=struct2[7],point_5=struct2[8], point6=testp6, point7=testp7, point8=testp8, point_6=p_6, point_7=p_7, point_8=p_8)
      return ret
    end
  
  
  
    ret = struct(point1=testp1,point2=testp2,point4=testp4,point5=testp5,point_1=struct2[4],point_2=struct2[5],point_3=struct2[6],point_4=struct2[7],point_5=struct2[8])
    return ret
  
  end
  
  # this function gets called if you are doing a left floor corner extended, and the top is too high to reach (twists, etc.)
  # this function takes the struct2 of weld points and modifies them (by subtracting from z) until the first weld point is reachable.
  # it determines the height that the lift column needs to raise to make the first point reachable
  # it then checks whether that height will allow the other points to be reachable
  # if its all good, it sets the global variable liftcolumnzneeded, modifies struct2's points, and returns struct2
  # if its not all good, then it displays an error message popup.
  def floor_corner_lift_column_extend_left(struct2):
    # we know that p1 cannot be accessed without a twist
    # calculate the height needed to get to p1
    liftcolumnincrement = 2 # mm
    enoughHeightAdded = False
    liftColumnHeightTest = 0
    while not enoughHeightAdded:
      liftColumnHeightTest = liftColumnHeightTest + liftcolumnincrement
      # set the orig_joints for p1. p1 demo was joint angles of [-0.45, -31.79, 56.47, 333.06, -130.98, 87.87] (degrees)
      # which equals [-0.007853981633974475, -0.5548401692089968, 0.985587428601197, 5.812993606692308, -2.28603225426217, 1.5336208137274159]
      orig_joints = [-0.007853981633974475, -0.5548401692089968, 0.985587428601197, 5.812993606692308, -2.28603225426217, 1.5336208137274159]
      # get the modified point:
      origp1 = struct2[0]
      testp1 = p[origp1[0], origp1[1], origp1[2] - liftColumnHeightTest / 1000, origp1[3], origp1[4], origp1[5]]
      enoughHeightAdded = can_pose_be_reached_without_twist(testp1, orig_joints)
    end
  
  
    # check whether the other 3 points are valid
    valid = True
    # get the modified point
    origp2 = struct2[1]
    testp2 = p[origp2[0], origp2[1], origp2[2] - liftColumnHeightTest / 1000, origp2[3], origp2[4], origp2[5]]
    # p2 demo was joint angles of [-0.45, -21.2, 56.98, 321.95, -130.97, 87.85] (degrees)
    # which equals [-0.007853981633974475, -0.3700098014227975, 0.9944886077863679, 5.619087526795738, -2.285857721336971, 1.5332717478770168]
    orig_joints = [-0.007853981633974475, -0.3700098014227975, 0.9944886077863679, 5.619087526795738, -2.285857721336971, 1.5332717478770168]
    valid = valid and can_pose_be_reached_without_twist(testp2, orig_joints)
    # get the modified point
    origp4 = struct2[2]
    testp4 = p[origp4[0], origp4[1], origp4[2] - liftColumnHeightTest / 1000, origp4[3], origp4[4], origp4[5]]
    # p4 demo was joint angles of [-8.62, -43.23, 99.53, 213.86, -89.19, 40.78] (degrees)
    # which equals [-0.15044738152191103, -0.7545058356371478, 1.7371262045099545, 3.7325611383150696, -1.556659159853741, 0.7117452689632868]
    orig_joints = [-0.15044738152191103, -0.7545058356371478, 1.7371262045099545, 3.7325611383150696, -1.556659159853741, 0.7117452689632868]
    valid = valid and can_pose_be_reached_without_twist(testp4, orig_joints)
    # get the modified point
    origp5 = struct2[3]
    testp5 = p[origp5[0], origp5[1], origp5[2] - liftColumnHeightTest / 1000, origp5[3], origp5[4], origp5[5]]
    # p5 demo was joint angles of [-0.59, -34.36, 77.71, 226.7, -89.18, 48.81] (degrees)
    # which equals [-0.010297442586766533, -0.5996951309852511, 1.356295361724792, 3.9566614142711405, -1.5564846269285415, 0.8518952078984314]
    orig_joints = [-0.010297442586766533, -0.5996951309852511, 1.356295361724792, 3.9566614142711405, -1.5564846269285415, 0.8518952078984314]
    valid = valid and can_pose_be_reached_without_twist(testp5, orig_joints)
  
    if not valid:
      # display
      popuptext = "Top of Weld is too high above robot. Cannot reach some necessary positions. Stop Program and try again with a lower top point. "
      # infinite loop
      while 1==1:
        popup(popuptext, title="Robot Positioning Warning",blocking=True)
      end
    else:
      liftcolumnzneeded = liftColumnHeightTest
      ret = struct(point1=testp1,point2=testp2,point4=testp4,point5=testp5,point_1=struct2[4],point_2=struct2[5],point_3=struct2[6],point_4=struct2[7],point_5=struct2[8])
      return ret
    end
  end
  
  # the same as floor_corner_lift_column_extend_left() but includes additional modifies for the additional points
  def floor_corner_lift_column_extend_left_tilt(struct2):
    # we know that p1 cannot be accessed without a twist
    # calculate the height needed to get to p1
    liftcolumnincrement = 2 # mm
    enoughHeightAdded = False
    liftColumnHeightTest = 0
    while not enoughHeightAdded:
      liftColumnHeightTest = liftColumnHeightTest + liftcolumnincrement
      # set the orig_joints for p1. p1 demo was joint angles of [-0.45, -31.79, 56.47, 333.06, -130.98, 87.87] (degrees)
      # which equals [-0.007853981633974475, -0.5548401692089968, 0.985587428601197, 5.812993606692308, -2.28603225426217, 1.5336208137274159]
      orig_joints = [-0.007853981633974475, -0.5548401692089968, 0.985587428601197, 5.812993606692308, -2.28603225426217, 1.5336208137274159]
      # get the modified point:
      origp1 = struct2[0]
      testp1 = p[origp1[0], origp1[1], origp1[2] - liftColumnHeightTest / 1000, origp1[3], origp1[4], origp1[5]]
      enoughHeightAdded = can_pose_be_reached_without_twist(testp1, orig_joints)
    end
  
  
    # check whether the other 3 points are valid
    valid = True
    # get the modified point
    origp2 = struct2[1]
    testp2 = p[origp2[0], origp2[1], origp2[2] - liftColumnHeightTest / 1000, origp2[3], origp2[4], origp2[5]]
    # p2 demo was joint angles of [-0.45, -21.2, 56.98, 321.95, -130.97, 87.85] (degrees)
    # which equals [-0.007853981633974475, -0.3700098014227975, 0.9944886077863679, 5.619087526795738, -2.285857721336971, 1.5332717478770168]
    orig_joints = [-0.007853981633974475, -0.3700098014227975, 0.9944886077863679, 5.619087526795738, -2.285857721336971, 1.5332717478770168]
    valid = valid and can_pose_be_reached_without_twist(testp2, orig_joints)
    # get the modified point
    origp4 = struct2[2]
    testp4 = p[origp4[0], origp4[1], origp4[2] - liftColumnHeightTest / 1000, origp4[3], origp4[4], origp4[5]]
    # p4 demo was joint angles of [-8.62, -43.23, 99.53, 213.86, -89.19, 40.78] (degrees)
    # which equals [-0.15044738152191103, -0.7545058356371478, 1.7371262045099545, 3.7325611383150696, -1.556659159853741, 0.7117452689632868]
    orig_joints = [-0.15044738152191103, -0.7545058356371478, 1.7371262045099545, 3.7325611383150696, -1.556659159853741, 0.7117452689632868]
    valid = valid and can_pose_be_reached_without_twist(testp4, orig_joints)
    # get the modified point
    origp5 = struct2[3]
    testp5 = p[origp5[0], origp5[1], origp5[2] - liftColumnHeightTest / 1000, origp5[3], origp5[4], origp5[5]]
    # p5 demo was joint angles of [-0.59, -34.36, 77.71, 226.7, -89.18, 48.81] (degrees)
    # which equals [-0.010297442586766533, -0.5996951309852511, 1.356295361724792, 3.9566614142711405, -1.5564846269285415, 0.8518952078984314]
    orig_joints = [-0.010297442586766533, -0.5996951309852511, 1.356295361724792, 3.9566614142711405, -1.5564846269285415, 0.8518952078984314]
    valid = valid and can_pose_be_reached_without_twist(testp5, orig_joints)
  
    # also modify the 3 other points
    origp6 = struct2[9]
    origp7 = struct2[10]
    origp8 = struct2[11]
    testp6 = p[origp6[0], origp6[1], origp6[2] - liftColumnHeightTest / 1000, origp6[3], origp6[4], origp6[5]]
    testp7 = p[origp7[0], origp7[1], origp7[2] - liftColumnHeightTest / 1000, origp7[3], origp7[4], origp7[5]]
    testp8 = p[origp8[0], origp8[1], origp8[2] - liftColumnHeightTest / 1000, origp8[3], origp8[4], origp8[5]]
  
    if not valid:
      # display
      popuptext = "Top of Weld is too high above robot. Cannot reach some necessary positions. Stop Program and try again with a lower top point. "
      # infinite loop
      while 1==1:
        popup(popuptext, title="Robot Positioning Warning",blocking=True)
      end
    else:
      liftcolumnzneeded = liftColumnHeightTest
      ret = struct(point1=testp1,point2=testp2,point4=testp4,point5=testp5,point_1=struct2[4],point_2=struct2[5],point_3=struct2[6],point_4=struct2[7],point_5=struct2[8], point6=testp6, point7=testp7, point8=testp8, point_6=struct2[12], point_7=struct2[13], point_8=struct2[14])
      return ret
    end
  end
  
  def floor_corner_right_p_3_reduce(struct2, orig_joints):
    # we know that p_5 cannot be accessed without a twist
    # calculate the distance p_5 needs to be changed (in the direction of p_4)
  
    #calculate unit vector from p_5 towards p_4
    point_4 = struct2[7]
    point_5 = struct2[8]
    vecx = point_4[0] - point_5[0]
    vecy = point_4[1] - point_5[1]
    vecz = point_4[2] - point_5[2]
    mag = sqrt(vecx*vecx + vecy*vecy + vecz*vecz)
    uvx = vecx / mag
    uvy = vecy / mag
    uvz = vecz / mag
  
    moveincrement = 2.0 # mm
    enoughMoveAdded = False
    movement = 0
  
    while not enoughMoveAdded:
      movement = movement + moveincrement
      # set the orig_joints for p_4. p1 was calculated and passed into this function
      # get the modified point:
      testp_5 = p[point_5[0] + uvx*movement, point_5[1] + uvy*movement, point_5[2] + uvz*movement, point_5[3], point_5[4], point_5[5]]
      enoughMoveAdded = can_pose_be_reached_without_twist(testp_5, orig_joints)
    end
  
    ret = struct(point1=struct2[0],point2=struct2[1],point4=struct2[2],point5=struct2[3],point_1=struct2[4],point_2=struct2[5],point_3=struct2[6],point_4=struct2[7],point_5=testp_5)
    return ret
  end
  
  
  # given a struct from analyze_touchpoints_only(), calculate the points
  # for right, for extended
  def calculate_DOtA_points_right_step_extended(struct1, listleans, chamferover, chamferup, tcp_pose_top):
      # get the stuff from the struct
      pointintersect = struct1[0]
      heading1 = struct1[1]
      heading2 = struct1[2]
      heading3 = struct1[3]
      l1delxunit = struct1[4]
      l1delyunit = struct1[5]
      l2delxunit = struct1[6]
      l2delyunit = struct1[7]
  
      # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
      # find locations 8 inches away from  intersect point
      # CONST
      # welddistance1 = 8 # vertical weld distance
      welddistance2 = 4.0 # first path second leg actual distance to top end of ramp
      welddistance3 = 4.75 # second path second leg
  
      # inches
      # wd1 = welddistance1 * 25.4 / 1000
      wd2 = welddistance2 * 25.4 / 1000
      wd3 = welddistance3 * 25.4 / 1000
      zup = chamferup * 25.4 / 1000
      chamferovermm =  chamferover * 25.4 / 1000
  
      # weld distance is the distance that it will weld. this will make it start at the z height that the user specified
      wd1 = tcp_pose_top[2] - pointintersect[2] - zup
  
      x = pointintersect[0] + l1delxunit * chamferovermm
      y = pointintersect[1] + l1delyunit * chamferovermm
      z = pointintersect[2] + zup
  
      #apply actual rxryrz to points
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_preheatdown(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point1 = p[x + wd1*listleans[0], y + wd1*listleans[1], z + wd1, rx, ry, rz] # add in the listleans factor to follow the face of the box as we move up
      point2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point4 = p[x, y, z, rx, ry, rz]
      x = x + l1delxunit * wd2
      y = y + l1delyunit * wd2
      point5 = p[x, y, z, rx, ry, rz]
  
      # in order to find the tilt back and ride points like the floor straight, i first need to calculate the rxryrz of the tilt back
      # and i also need to calculate the v3 and v4 unit vectors. v3 points parallel with the path. v4 points perpendicular, out from box
      v3 = [l1delxunit, l1delyunit, 0]
      # to get v4 i will use v3 and rotate that vector 90 degrees
      # to rotate a 2d vector (x, y) 90 degrees, the simplest method is to swap the components and negate one. clockwise gives (y, -x)
      v4 = [l1delyunit, -1 * l1delxunit, 0]
      # heading 1 is the heading from +x axis to pushing in to the right side of the box. that is the heading we need to turn to get rxryrz
      # from the 0 position, we need to rotate -90 deg about y axis. then rotate heading1 - 180 deg about the +z axis. then 10 degrees less for the tiltback.
      # first rotation is 90 degrees about y axis. positive direction. gun is now pointing in the x+ direction with preheat facing +y direction
      m1 = get_rotation_matrix_from_description("y", 1, -90 * pi / 180)
      # second rotation is about 225 degrees about the z axis. heading1 minus 90 degrees plus 10 degrees.
      m2 = get_rotation_matrix_from_description("z", 1, heading1 - 180*pi/180- 10*pi/180)
      m4 = multiply_matrix(m2, m1)
      rxryrzt = convert_matrix_to_axang(m4)
      rxt = rxryrzt[0]
      ryt = rxryrzt[1]
      rzt = rxryrzt[2]
  
      # point 6 is the start of the tilt back
      # 1.5 inches in from end
      dist = -1.5 * 25.4 / 1000.0
      p6x = x + v3[0] * dist
      p6y = y + v3[1] * dist
      p6z = z + v3[2] * dist
      point6 = p[p6x, p6y, p6z, rx, ry, rz]
  
      # point 7 is the end of the tilt back
      tiltraise = 0.006 # 6 mm raise needed for the tip to clear the plane during tiltback
      dist = -0.5 * 25.4 / 1000.0
      p7x = x + v3[0] * dist + v4[0] * tiltraise
      p7y = y + v3[1] * dist + v4[1] * tiltraise
      p7z = z + v3[2] * dist
      point7 = p[p7x, p7y, p7z, rxt, ryt, rzt]
  
      # point 8 is the end of smear
      dist = 2 * 25.4 / 1000.0
      p8x = x + v3[0] * dist + v4[0] * tiltraise
      p8y = y + v3[1] * dist + v4[1] * tiltraise
      p8z = z + v3[2] * dist
      point8 = p[p8x, p8y, p8z, rxt, ryt, rzt]
  
      # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
      roundoverdistance = 0.05
      rod = roundoverdistance * 25.4 / 1000
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l1delxunit * chamferovermm
      y = pointintersect[1] + l1delyunit * chamferovermm
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_1 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l1delxunit * rod
      y = pointintersect[1] + l1delyunit * rod
      point_2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      x = pointintersect[0] + l2delxunit * rod
      y = pointintersect[1] + l2delyunit * rod
      point_4 = p[x, y, z, rx, ry, rz]
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l2delxunit * 0.5 * 25.4/1000.0
      y = pointintersect[1] + l2delyunit * 0.5 * 25.4/1000.0
      point_5 = p[x, y, z, rx, ry, rz]
  
      # in order to find the tilt back and ride points like the floor straight, i first need to calculate the rxryrz of the tilt back
      # and i also need to calculate the v3 and v4 unit vectors. v3 points parallel with the path. v4 points perpendicular, out from box
      v3 = [l2delxunit, l2delyunit, 0]
      # to get v4 i will use v3 and rotate that vector 90 degrees
      # to rotate a 2d vector (x, y) 90 degrees, the simplest method is to swap the components and negate one. counter clockwise gives (-y, x)
      v4 = [-1 * l2delyunit, l2delxunit, 0]
      # heading 3 is the heading from +x axis to pushing in to the left side of the box. that is the heading we need to turn to get rxryrz
      # from the 0 position, we need to rotate +90 deg about y axis. then rotate heading3 deg about the +z axis. then 10 degrees more for the tiltback.
      # first rotation is 90 degrees about y axis. positive direction. gun is now pointing in the x+ direction with preheat facing +y direction
      m1 = get_rotation_matrix_from_description("y", 1, 90 * pi / 180)
      # second rotation is about 165 degrees about the z axis. heading3 plus 10 degrees.
      m2 = get_rotation_matrix_from_description("z", 1, heading3 + 10*pi/180)
      m4 = multiply_matrix(m2, m1)
      rxryrzt = convert_matrix_to_axang(m4)
      rxt = rxryrzt[0]
      ryt = rxryrzt[1]
      rzt = rxryrzt[2]
  
      # set the "where dist from" point
      x = pointintersect[0]
      y = pointintersect[1]
      z = z
  
      x = x + v3[0] * wd3
      y = y + v3[1] * wd3
  
      # point _6 is the start of the tilt back
      # 1.5 inches in from end
      dist = -1.5 * 25.4 / 1000.0
      p_6x = x + v3[0] * dist
      p_6y = y + v3[1] * dist
      p_6z = z + v3[2] * dist
      point_6 = p[p_6x, p_6y, p_6z, rx, ry, rz]
  
      # point _7 is the end of the tilt back
      tiltraise = 0.006 # 6 mm raise needed for the tip to clear the plane during tiltback
      dist = -0.5 * 25.4 / 1000.0
      p_7x = x + v3[0] * dist + v4[0] * tiltraise
      p_7y = y + v3[1] * dist + v4[1] * tiltraise
      p_7z = z + v3[2] * dist
      point_7 = p[p_7x, p_7y, p_7z, rxt, ryt, rzt]
  
      # point _8 is the end of smear
      dist = 2 * 25.4 / 1000.0
      p_8x = x + v3[0] * dist + v4[0] * tiltraise
      p_8y = y + v3[1] * dist + v4[1] * tiltraise
      p_8z = z + v3[2] * dist
      point_8 = p[p_8x, p_8y, p_8z, rxt, ryt, rzt]
  
      #FIND POINT 3
      # by calling analyze_touchpoints()
      atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
      atret5 = atret[5]
      point_3 = p[atret5[0], atret5[1], z, atret5[3], atret5[4], atret5[5]]
  
  
      struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5, point6=point6, point7=point7, point8=point8, point_6=point_6, point_7=point_7, point_8=point_8)
      return struct2
  end
  
  # given a struct from analyze_touchpoints_only(), calculate the points
  # for left, for extended
  def calculate_DOtA_points_left_step_extended(struct1, listleans, chamferover, chamferup, tcp_pose_top):
      # get the stuff from the struct
      pointintersect = struct1[0]
      heading1 = struct1[1]
      heading2 = struct1[2]
      heading3 = struct1[3]
      l1delxunit = struct1[4]
      l1delyunit = struct1[5]
      l2delxunit = struct1[6]
      l2delyunit = struct1[7]
  
      # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
      # find locations 8 inches away from  intersect point
      # CONST
      # welddistance1 = 8 # vertical weld distance
      welddistance2 = 4.0 # first path second leg actual distance to top end of ramp from midline of vertical chamfer
      welddistance3 = 4.75 # second path actual distance to top end of ramp from pointintersect
  
      # inches
      # wd1 = welddistance1 * 25.4 / 1000
      wd2 = welddistance2 * 25.4 / 1000
      wd3 = welddistance3 * 25.4 / 1000
      zup = chamferup * 25.4 / 1000
      chamferovermm =  chamferover * 25.4 / 1000
  
      # weld distance is the distance that it will weld. this will make it start at the z height that the user specified
      wd1 = tcp_pose_top[2] - pointintersect[2] - zup
  
      x = pointintersect[0] + l2delxunit * chamferovermm
      y = pointintersect[1] + l2delyunit * chamferovermm
      z = pointintersect[2] + zup
  
      #apply actual rxryrz to points
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_preheatdown(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point1 = p[x + wd1*listleans[0], y + wd1*listleans[1], z + wd1, rx, ry, rz]
      point2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point4 = p[x, y, z, rx, ry, rz]
      x = x + l2delxunit * wd2
      y = y + l2delyunit * wd2
      point5 = p[x, y, z, rx, ry, rz]
  
      # in order to find the tilt back and ride points like the floor straight, i first need to calculate the rxryrz of the tilt back
      # and i also need to calculate the v3 and v4 unit vectors. v3 points parallel with the path. v4 points perpendicular, out from box
      v3 = [l2delxunit, l2delyunit, 0]
      # to get v4 i will use v3 and rotate that vector 90 degrees
      # to rotate a 2d vector (x, y) 90 degrees, the simplest method is to swap the components and negate one. counter clockwise gives (-y, x)
      v4 = [-1 * l2delyunit, l2delxunit, 0]
      # heading 3 is the heading from +x axis to pushing in to the left side of the box. that is the heading we need to turn to get rxryrz
      # from the 0 position, we need to rotate +90 deg about y axis. then rotate heading3 deg about the +z axis. then 10 degrees more for the tiltback.
      # first rotation is 90 degrees about y axis. positive direction. gun is now pointing in the x+ direction with preheat facing +y direction
      m1 = get_rotation_matrix_from_description("y", 1, 90 * pi / 180)
      # second rotation is about 165 degrees about the z axis. heading3 plus 10 degrees.
      m2 = get_rotation_matrix_from_description("z", 1, heading3 + 10*pi/180)
      m4 = multiply_matrix(m2, m1)
      rxryrzt = convert_matrix_to_axang(m4)
      rxt = rxryrzt[0]
      ryt = rxryrzt[1]
      rzt = rxryrzt[2]
  
      # point 6 is the start of the tilt back
      # 1.5 inches in from end
      dist = -1.5 * 25.4 / 1000.0
      p6x = x + v3[0] * dist
      p6y = y + v3[1] * dist
      p6z = z + v3[2] * dist
      point6 = p[p6x, p6y, p6z, rx, ry, rz]
  
      # point 7 is the end of the tilt back
      tiltraise = 0.006 # 6 mm raise needed for the tip to clear the plane during tiltback
      dist = -0.5 * 25.4 / 1000.0
      p7x = x + v3[0] * dist + v4[0] * tiltraise
      p7y = y + v3[1] * dist + v4[1] * tiltraise
      p7z = z + v3[2] * dist
      point7 = p[p7x, p7y, p7z, rxt, ryt, rzt]
  
      # point 8 is the end of smear
      dist = 2 * 25.4 / 1000.0
      p8x = x + v3[0] * dist + v4[0] * tiltraise
      p8y = y + v3[1] * dist + v4[1] * tiltraise
      p8z = z + v3[2] * dist
      point8 = p[p8x, p8y, p8z, rxt, ryt, rzt]
  
      # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
      roundoverdistance = 0.05
      rod = roundoverdistance * 25.4 / 1000
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l2delxunit * chamferovermm
      y = pointintersect[1] + l2delyunit * chamferovermm
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_1 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l2delxunit * rod
      y = pointintersect[1] + l2delyunit * rod
      point_2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      x = pointintersect[0] + l1delxunit * rod
      y = pointintersect[1] + l1delyunit * rod
      point_4 = p[x, y, z, rx, ry, rz]
  
      # now we have the unit vector. extend the weld distance from the intersection
      p_5x = pointintersect[0] + l1delxunit * 0.5 * 25.4/1000.0
      p_5y = pointintersect[1] + l1delyunit * 0.5 * 25.4/1000.0
      point_5 = p[p_5x, p_5y, z, rx, ry, rz]
  
      # in order to do the tilt back and ride on this side, i need to switch back to tcp=pretend_welder at some point.
      # it needs to be in backofhole for the around part.
      # 11.7 + 4.51 = 16.21 mm is the difference between those tcps.
      # so if i finish the around at point_4, move half an inch to point_5, then set tcp to pretend_welder, go straight another 25 mm.
      # then i can
      # in order to find the tilt back and ride points like the floor straight, i first need to calculate the rxryrz of the tilt back
      # and i also need to calculate the v3 and v4 unit vectors. v3 points parallel with the path. v4 points perpendicular, out from box
      v3 = [l1delxunit, l1delyunit, 0]
      # to get v4 i will use v3 and rotate that vector 90 degrees
      # to rotate a 2d vector (x, y) 90 degrees, the simplest method is to swap the components and negate one. clockwise gives (y, -x)
      v4 = [l1delyunit, -1 * l1delxunit, 0]
      # heading 1 is the heading from +x axis to pushing in to the right side of the box. that is the heading we need to turn to get rxryrz
      # from the 0 position, we need to rotate -90 deg about y axis. then rotate heading1 - 180 deg about the +z axis. then 10 degrees less for the tiltback.
      # first rotation is 90 degrees about y axis. positive direction. gun is now pointing in the x+ direction with preheat facing +y direction
      m1 = get_rotation_matrix_from_description("y", 1, -90 * pi / 180)
      # second rotation is about 225 degrees about the z axis. heading1 minus 90 degrees plus 10 degrees.
      m2 = get_rotation_matrix_from_description("z", 1, heading1 - 180*pi/180- 10*pi/180)
      m4 = multiply_matrix(m2, m1)
      rxryrzt = convert_matrix_to_axang(m4)
      rxt = rxryrzt[0]
      ryt = rxryrzt[1]
      rzt = rxryrzt[2]
  
      # set the "where dist from" point
      x = pointintersect[0]
      y = pointintersect[1]
      z = z
  
      x = x + v3[0] * wd3
      y = y + v3[1] * wd3
  
      # point _6 is the start of the tilt back
      # 1.5 inches in from end
      dist = -1.5 * 25.4 / 1000.0
      p_6x = x + v3[0] * dist
      p_6y = y + v3[1] * dist
      p_6z = z + v3[2] * dist
      point_6 = p[p_6x, p_6y, p_6z, rx, ry, rz]
  
      # point _7 is the end of the tilt back
      tiltraise = 0.006 # 6 mm raise needed for the tip to clear the plane during tiltback
      dist = -0.5 * 25.4 / 1000.0
      p_7x = x + v3[0] * dist + v4[0] * tiltraise
      p_7y = y + v3[1] * dist + v4[1] * tiltraise
      p_7z = z + v3[2] * dist
      point_7 = p[p_7x, p_7y, p_7z, rxt, ryt, rzt]
  
      # point _8 is the end of smear
      dist = 2 * 25.4 / 1000.0
      p_8x = x + v3[0] * dist + v4[0] * tiltraise
      p_8y = y + v3[1] * dist + v4[1] * tiltraise
      p_8z = z + v3[2] * dist
      point_8 = p[p_8x, p_8y, p_8z, rxt, ryt, rzt]
  
      #FIND POINT 3
      # by calling analyze_touchpoints()
      atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
      point_3 = atret[5]
      #point 3 will not have the correct rxryrz though because now the gun needs to be face up
      rxryrz = convert_heading_to_axang_ccw(heading2)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_3 = p[point_3[0], point_3[1], z, rx, ry, rz]
  
      struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5, point6=point6, point7=point7, point8=point8, point_6=point_6, point_7=point_7, point_8=point_8)
      return struct2
  end
  
  # analyze touchpoints adjust for lift column height
  # this function adjusts the struct1 returned by analyze_touchpoints_only and modifies it based on if the lift column was raised when the points were found
  # returns struct1 back, but with pointintersect modified
  # based on a struct1 with _ elements
  def at_adjust_lch(struct1):
      lch = get_lift_column_height_condensed() # this returns a value in mm
      lch2 = lch / 1000.0 # convert to meters
      #popup(lch2, blocking=True)
      pio = struct1[0] #pointintersect old
      oldz = pio[2]
      newz = oldz + lch2
      pointintersect = p[pio[0], pio[1], newz, pio[3], pio[4], pio[5]]
      ret = struct(pointintersect=pointintersect, heading1=struct1[1], heading2=struct1[2], heading3=struct1[3], l1delxunit=struct1[4], l1delyunit=struct1[5], l2delxunit=struct1[6], l2delyunit=struct1[7])
      return ret
  
  end
  
  # this function takes the tcp_pose_top gathered by the teach, and adjusts it if there was a lift column active when it was collected
  # returns the tcp_pose, with added z to account for lift column
  def adjust_tcptop(tcp_pose_top):
      lch = get_lift_column_height_condensed() # this returns a value in mm
      lch2 = lch / 1000.0 # convert to meters
  
      oldz = tcp_pose_top[2]
      newz = oldz + lch2
      ret = p[tcp_pose_top[0], tcp_pose_top[1], newz, tcp_pose_top[3], tcp_pose_top[4], tcp_pose_top[5]]
      return ret
  end
  
  # this function checks if the robot cart is not aligned, to give early warning that the positioning will not allow the weld to be completed.
  # it is a pain to teach the points, have it go through its homing, and THEN tell you the cart is positioned wrong.
  def is_robot_position_likely_invalid(point0):
  
  end
  $ 98 "leftchoice≔'Select Yes for a Left side weld, or select No for a Right Side weld.'"
  global leftchoice=request_boolean_from_primary_client("Select Yes for a Left side weld, or select No for a Right Side weld.")
  $ 99 "sidewallchoice≔'Is the sidewall 3/4 inch?'"
  global sidewallchoice=request_boolean_from_primary_client("Is the sidewall 3/4 inch?")
  $ 100 "If sidewallchoice"
  if (sidewallchoice):
    $ 101 "sidewall≔0.628"
    global sidewall=0.628
  else:
    $ 102 "Else" "noBreak"
    $ 103 "sidewall≔0.375"
    global sidewall=0.375
  end
  $ 104 "floorchoice≔'Is the floor 3/4 inch?'"
  global floorchoice=request_boolean_from_primary_client("Is the floor 3/4 inch?")
  $ 105 "If floorchoice"
  if (floorchoice):
    $ 106 "floorthick≔0.628"
    global floorthick=0.628
  else:
    $ 107 "Else" "noBreak"
    $ 108 "floorthick≔0.375"
    global floorthick=0.375
  end
  $ 109 "Set"
  set_tcp(p[-0.0095,-0.328,0.105,1.2092,-1.2092,1.2092])
  $ 110 "MoveJ"
  $ 111 "Waypoint_46" "breakAfter"
  movej(get_inverse_kin(Waypoint_46_p, qnear=Waypoint_46_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 112 "Set"
  set_tcp(p[1.4000000000000001E-4,-0.01751,0.284,0.0,0.0,0.0])
  $ 113 "Test_Teach_Position()"
  Test_Teach_Position()
  $ 114 "Set"
  set_tcp(p[1.4000000000000001E-4,-0.01751,0.284,0.0,0.0,0.0])
  $ 115 "kill threadId_Thread_1"
  kill threadId_Thread_1
  $ 116 "Corner_Homing_45()"
  Corner_Homing_45()
  $ 117 "Set"
  set_tcp(p[-0.011699999999999999,-0.328,0.105,1.2092,-1.2092,1.2092])
  $ 122 "If leftchoice≟ True "
  if (leftchoice ==   True  ):
    $ 123 "pathturn≔main_calculate_left_extended(p11,p12,p21,p22,p3,p13,p23,sidewall,floorthick,tcp_pose_top)"
    global pathturn=main_calculate_left_extended(p11,p12,p21,p22,p3,p13,p23,sidewall,floorthick,tcp_pose_top)
    $ 124 "extrude_knife3()"
    extrude_knife3()
    $ 126 "move_path_3left()"
    move_path_3left()
  else:
    $ 127 "Else" "noBreak"
    $ 128 "pathturn≔main_calculate_right_extended(p11,p12,p21,p22,p3,p13,p23,sidewall,floorthick,tcp_pose_top)"
    global pathturn=main_calculate_right_extended(p11,p12,p21,p22,p3,p13,p23,sidewall,floorthick,tcp_pose_top)
    $ 129 "extrude_knife3()"
    extrude_knife3()
    $ 130 "move_path_3right()"
    move_path_3right()
  end
  $ 132 "MoveJ"
  $ 134 "Waypoint_20" "breakAfter"
  movej(get_inverse_kin(Waypoint_20_p, qnear=Waypoint_20_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 135 "Home"
  movej([-3.266929759358355, -1.2139462677784536, 1.5878387874396154, 1.1069165929565088, -0.0023738326664366483, -1.7891447305770605], a=1.3962634015954636, v=1.0471975511965976)
end
