def Main_Program_Left():
  global _hidden_verificationVariable=0
  set_gravity([0.0, 0.0, 9.82])
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(0)
  set_target_payload(2.760000, [0.004000, -0.022000, 0.072000], [0.008360, 0.008360, 0.008360, 0.000000, 0.000000, 0.000000])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_tcp(p[0.00838539968723857,-0.33324903375023873,0.07852362563148635,1.2092,-1.2092,1.2092])
  set_safety_mode_transition_hardness(1)
  global Plane_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global Point_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  # begin: URCap Installation Node
  #   Source: MachineLogic for Universal Robots, 3.1.7, Vention Inc.
  #   Type: MachineLogic for Universal Robots
  def waitForResponse(expected_response_vention, cname_vention):
  response_vention = socket_read_string(cname_vention,timeout=15)
  while response_vention != expected_response_vention:
  sleep(0.01)
  response_vention = socket_read_string(cname_vention,timeout=15)
  end
  sleep(0.01)
  sync()
  end
  def sendString(string_vention, expected_response_vention, cname_vention):
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  while response_vention != expected_response_vention:
  sleep(0.01)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  end
  sleep(0.01)
  sync()
  end
  def sendStringNAck(string_vention, expected_response_vention, cname_vention):
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  while(response_vention != expected_response_vention and response_vention != "nAck"):
  sleep(0.01)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received",blocking=True)
  end
  end
  sleep(0.01)
  sync()
  end
  def sendStringWithTimeout(string_vention, expected_response_vention, cname_vention):
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=10)
  if(response_vention == "nAck"):
  popup("nAck received"+string_vention)
  end
  sleep(0.01)
  sync()
  end
  def pollString(string_vention, expected_response_vention, cname_vention):
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  while response_vention != expected_response_vention:
  sleep(1)
  socket_send_string(str_cat(string_vention,";"), cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  end
  sleep(0.01)
  sync()
  end
  def sendVariable(var_vention, data_vention, expected_response_vention, cname_vention):
  socket_set_var(var_vention, data_vention, cname_vention)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  while response_vention != expected_response_vention:
  sleep(0.01)
  response_vention = socket_read_string(cname_vention,timeout=15)
  if(response_vention == "nAck"):
  popup("nAck received")
  end
  end
  sleep(0.01)
  sync()
  end
  def intToString(integer_vention,cname_vention):
  stringFix=""
  multiplier_vention123=1
  if integer_vention<0:
  stringFix="-"
  multiplier_vention123=-1
  end
  socket_set_var("GetString",integer_vention*multiplier_vention123,cname_vention)
  string_vention=""
  while string_vention=="":
  sleep(0.01)
  string_vention=socket_read_string(cname_vention,timeout=15)
  end
  sleep(0.01)
  sync()
  string_vention=stringFix+string_vention
  return string_vention
  end
  string_vention=""
  isVentionMovementBusy = False
  isVentionParallelMovementSendingScript = False
  ventionThreadHandle = 1
  isVentionMovementBusyMachineMotion1 = False
  isVentionParallelMovementSendingScriptMachineMotion1 = False
  socket_vention = socket_open("192.168.3.52", 9999, "MachineMotion1")
  if socket_vention==False:
  popup("Check configuration, can't connect to MachineMotion")
  end
  waitForResponse("MachineMotion connection established", "MachineMotion1")
  sendString("isReady", "MachineMotion isReady = true", "MachineMotion1")
  sendStringWithTimeout("setURCapVersion2", "setURCapVersion loaded", "MachineMotion1")
  sendString("SET speed_v2 1000000", "Ack", "MachineMotion1")
  sendString("SET acceleration_v2 100000", "Ack", "MachineMotion1")
  sendString("SET de_axis_1_microsteps_config 8", "Ack", "MachineMotion1")
  sendString("SET de_axis_1_mechanical_gain_config_v2 150000.0", "Ack", "MachineMotion1")
  sendString("SET de_axis_1_direction_config 1", "Ack", "MachineMotion1")
  sendString("SET de_axis_1_type_config Custom Actuator ", "Ack", "MachineMotion1")
  sendString("de_axis_1_config_exec", "Ack", "MachineMotion1")
  # end: URCap Installation Node
  step_count_7874a79c_0a2a_4171_ba02_5a59847e4fd2 = 0.0
  thread Step_Counter_Thread_f54a7e5f_ec86_4eba_9df5_d12722c4c6bb():
    while (True):
      step_count_7874a79c_0a2a_4171_ba02_5a59847e4fd2 = step_count_7874a79c_0a2a_4171_ba02_5a59847e4fd2 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_f54a7e5f_ec86_4eba_9df5_d12722c4c6bb()
  global freedrive_m_var=  False  
  global Waypoint_1_p=p[-.161036555831, .970524399959, .722042384791, -.554954311189, .106465018540, .328580879483]
  global Waypoint_1_q=[-1.3071630636798304, -1.3366777312806626, 2.2083633581744593, 3.7187773424335937, -2.9519384543048304, 0.9132363796234131]
  global Waypoint_7_p=p[-.689650873132, .138963273545, .230691387978, -.851994598965, -1.645998530536, 1.646007616333]
  global Waypoint_7_q=[-0.9414032141314905, -1.501500443821289, 2.801856819783346, 4.981602895050802, -4.698942009602682, 1.571649193763733]
  global Waypoint_8_p=p[-.568724745609, .230601805298, .220208295176, -1.519097711196, -.535155391172, .573964121010]
  global Waypoint_8_q=[-0.04883271852602178, -1.2753942471793671, 2.4771457354175013, 5.041022258787908, -2.326899592076437, 1.532160997390747]
  global Waypoint_9_p=p[-.568724745609, .230601805298, .220208295176, -1.519097711196, -.535155391172, .573964121010]
  global Waypoint_9_q=[-0.04883271852602178, -1.2753942471793671, 2.4771457354175013, 5.041022258787908, -2.326899592076437, 1.532160997390747]
  global Waypoint_22_p=p[-.853851193668, .133266829906, .060418082908, -.274178222953, -2.359710051999, .046821166283]
  global Waypoint_22_q=[-0.608560864125387, -1.0122360748103638, 2.787060801182882, 3.7283646303364257, -4.940747324620382, 0.3777344226837158]
  global Waypoint_23_p=p[-.979398188272, -.259625449453, .211289397035, -.673010443572, -1.459355862765, -.640164958946]
  global Waypoint_23_q=[0.36968713998794556, -0.5732358259013672, 2.138303581868307, 3.1253925996967773, -4.70385724702944, -1.2100523153888147]
  global Waypoint_24_p=p[-.826865752305, .369357632284, .043113676955, .574997346548, -1.492225541214, .597128135378]
  global Waypoint_24_q=[-1.0355513731585901, -0.33930082738909917, 2.126244846974508, 2.9386045175739746, -4.711197797452108, 1.7860286235809326]
  global Waypoint_2_p=p[-.548957282596, .386284559177, .143710178207, 1.570800598292, -.000025190822, .000004803470]
  global Waypoint_2_q=[-1.0516188780414026, -1.010990933781006, 2.1562450567828577, -1.143702046280243, -1.0526168982135218, -0.0017235914813440445]
  def calculate_point_to_move_towards(feature, direction, position_distance):
    local posDir=[direction[0], direction[1], direction[2]]
    if (norm(posDir) < 1e-6):
      return get_target_waypoint()
    end
    local direction_vector_normalized=normalize(posDir)
    local displacement_pose=p[direction_vector_normalized[0] * position_distance,direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,0,0,0]
    local wanted_displacement_in_base_frame=pose_sub(pose_trans(feature, displacement_pose), feature)
    return pose_add(get_target_waypoint(), wanted_displacement_in_base_frame)
  end
  global Waypoint_3_p=p[.432120633847, .373496143704, .463992564600, -.000014136521, -3.141567738104, -.000014867905]
  global Waypoint_3_q=[-2.7853482405291956, -1.8143698177733363, 2.4549508730517786, -2.210560461083883, -1.5711315313922327, 1.9254603385925293]
  global Waypoint_4_p=p[.432136735069, .373501596410, .340883510249, -.000031606225, -3.141589553529, -.000013823620]
  global Waypoint_4_q=[-2.785483185444967, -1.6431261501707972, 2.568024222050802, -2.49489750484609, -1.5709694067584437, 1.9253177642822266]
  global Waypoint_5_p=p[.432160287104, .281352183882, .340893061994, .000015375091, 3.141574034920, .000032661568]
  global Waypoint_5_q=[-2.9616554419146937, -1.7250400982298792, 2.631975237523214, -2.4769565067686976, -1.5710294882403772, 1.7491776943206787]
  global Waypoint_6_p=p[.432128063058, .281346135716, .478493221894, .000013346378, -3.141574975494, -.000002942308]
  global Waypoint_6_q=[-2.961463991795675, -1.9219290218748988, 2.4929660002337855, -2.141019483605856, -1.571230713521139, 1.7493857145309448]
  global Waypoint_10_p=p[-.658264763546, .299530128456, .030909835036, .426821001551, -1.621505068649, .437070885767]
  global Waypoint_10_q=[-1.350241486226217, -0.9702387017062684, 2.492185179387228, -1.7834822140135707, -0.33723670641054326, 1.8489984273910522]
  global Waypoint_11_p=p[-.448862677341, .524599667441, -.175967040878, 2.473330473302, -1.874382924863, .205319206046]
  global Waypoint_11_q=[-1.1354392210589808, -1.0039964479259034, 2.441021744404928, -2.875528474847311, -1.6043828169452112, 1.7329596281051636]
  global Waypoint_12_p=p[-.542919433581, .212782147188, .086749705211, -.745950140780, -1.570054240894, -.808284086705]
  global Waypoint_12_q=[-0.26738197008241826, -1.11244489372287, 2.793460194264547, -1.547202582736947, -4.00090462366213, 1.5620925426483154]
  global Waypoint_13_p=p[-.542919433581, .212782147188, .086749705211, -.745950140780, -1.570054240894, -.808284086705]
  global Waypoint_13_q=[-0.26738197008241826, -1.11244489372287, 2.793460194264547, -1.547202582736947, -4.00090462366213, 1.5620925426483154]
  global Waypoint_14_p=p[-.448862677341, .524599667441, -.175967040878, 2.473330473302, -1.874382924863, .205319206046]
  global Waypoint_14_q=[-1.1354392210589808, -1.0039964479259034, 2.441021744404928, -2.875528474847311, -1.6043828169452112, 1.7329596281051636]
  global Waypoint_15_p=p[-.658264763546, .299530128456, .030909835036, .426821001551, -1.621505068649, .437070885767]
  global Waypoint_15_q=[-1.350241486226217, -0.9702387017062684, 2.492185179387228, -1.7834822140135707, -0.33723670641054326, 1.8489984273910522]
  global Waypoint_16_p=p[-.343952006273, .632142227752, .615174722549, -.025948978133, -.008794819136, -.567469912202]
  global Waypoint_16_q=[-1.350241486226217, -0.9702451390079041, 2.492171827946798, -3.0669099293150843, 1.575993537902832, 2.355180025100708]
  global Waypoint_17_p=p[-.343952006273, .632142227752, .615174722549, -.025948978133, -.008794819136, -.567469912202]
  global Waypoint_17_q=[-1.350241486226217, -0.9702451390079041, 2.492171827946798, -3.0669099293150843, 1.575993537902832, 2.355180025100708]
  global Waypoint_18_p=p[-.658264763546, .299530128456, .030909835036, .426821001551, -1.621505068649, .437070885767]
  global Waypoint_18_q=[-1.350241486226217, -0.9702387017062684, 2.492185179387228, -1.7834822140135707, -0.33723670641054326, 1.8489984273910522]
  def move_path_3left():
    $ 20 "move_path_3left" "noBreak"
    $ 21 "'this is the path for Down, Over, then Back Around'"
    # 'this is the path for Down, Over, then Back Around'
    $ 22 "Comment"
    # Comment
    $ 23 "Home"
    movej([-3.5235366372186707, -1.9259070680664099, 2.3525050044875555, 0.20454112128959331, -0.22302944588515938, -0.6277049025321748], a=1.3962634015954636, v=1.0471975511965976)
    $ 24 "MoveJ"
    $ 25 "Waypoint_1" "breakAfter"
    movej(get_inverse_kin(Waypoint_1_p, qnear=Waypoint_1_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 26 "Waypoint_7" "breakAfter"
    movej(get_inverse_kin(Waypoint_7_p, qnear=Waypoint_7_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 27 "Waypoint_8" "breakAfter"
    movej(get_inverse_kin(Waypoint_8_p, qnear=Waypoint_8_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 32 "Comment"
    # Comment
    $ 33 "p1≔pathturn[0]"
    global p1=pathturn[0]
    $ 34 "p2≔pathturn[1]"
    global p2=pathturn[1]
    $ 35 "p4≔pathturn[2]"
    global p4=pathturn[2]
    $ 36 "p5≔pathturn[3]"
    global p5=pathturn[3]
    $ 37 "MoveJ"
    $ 38 "p1" "breakAfter"
    movej(p1, a=1.3962634015954636, v=1.0471975511965976)
    $ 39 "Wait: 1.0"
    sleep(1.0)
    $ 40 "MoveL"
    $ 41 "p2" "breakAfter"
    movel(p2, a=0.1, v=0.05)
    $ 42 "Wait: 1.0"
    sleep(1.0)
    $ 43 "MoveL"
    $ 44 "p4" "breakAfter"
    movel(p4, a=0.005, v=0.02)
    $ 45 "MoveL"
    $ 46 "p5" "breakAfter"
    movel(p5, a=0.1, v=0.05)
    $ 47 "Comment"
    # Comment
    $ 48 "pret1≔p[p5[0]+.1,p5[1],p5[2],p5[3],p5[4],p5[5]]"
    global pret1=p[p5[0]+.1,p5[1],p5[2],p5[3],p5[4],p5[5]]
    $ 49 "p_1≔pathturn[4]"
    global p_1=pathturn[4]
    $ 50 "p_2≔pathturn[5]"
    global p_2=pathturn[5]
    $ 51 "p_3≔pathturn[6]"
    global p_3=pathturn[6]
    $ 52 "p_4≔pathturn[7]"
    global p_4=pathturn[7]
    $ 53 "p_5≔pathturn[8]"
    global p_5=pathturn[8]
    $ 54 "MoveJ"
    $ 55 "pret1" "breakAfter"
    movej(pret1, a=1.3962634015954636, v=0.3490658503988659)
    $ 56 "Waypoint_9" "breakAfter"
    movej(get_inverse_kin(Waypoint_9_p, qnear=Waypoint_9_q), a=1.3962634015954636, v=0.3490658503988659)
    $ 57 "'now go into the ccw weld position'"
    # 'now go into the ccw weld position'
    $ 58 "Waypoint_7" "breakAfter"
    movej(get_inverse_kin(Waypoint_7_p, qnear=Waypoint_7_q), a=1.3962634015954636, v=0.3490658503988659)
    $ 59 "Comment"
    # Comment
    $ 60 "Waypoint_22" "breakAfter"
    movej(get_inverse_kin(Waypoint_22_p, qnear=Waypoint_22_q), a=1.3962634015954636, v=0.3490658503988659)
    $ 61 "Waypoint_23" "breakAfter"
    movej(get_inverse_kin(Waypoint_23_p, qnear=Waypoint_23_q), a=1.3962634015954636, v=0.3490658503988659)
    $ 70 "MoveJ"
    $ 71 "p_1" "breakAfter"
    movej(p_1, a=1.3962634015954636, v=1.0471975511965976)
    $ 72 "MoveL"
    $ 73 "p_2" "breakAfter"
    movel(p_2, a=1.2, v=0.012)
    $ 74 "MoveP"
    $ 75 "CircleMove"
    $ 76 "p_3" "noBreak"
    $ 77 "p_4" "breakAfter"
    movec(p_3, p_4, a=0.01, v=5.0E-4, r=0.0, mode=1)
    $ 78 "MoveL"
    $ 79 "p_5" "breakAfter"
    movel(p_5, a=1.2, v=0.012)
    $ 84 "MoveJ"
    $ 85 "Waypoint_24" "breakAfter"
    movej(get_inverse_kin(Waypoint_24_p, qnear=Waypoint_24_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 86 "Waypoint_7" "breakAfter"
    movej(get_inverse_kin(Waypoint_7_p, qnear=Waypoint_7_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 87 "Comment"
    # Comment
    $ 88 "Comment"
    # Comment
    $ 89 "Comment"
    # Comment
    $ 90 "Comment"
    # Comment
    $ 91 "Comment"
    # Comment
    $ 92 "Comment"
    # Comment
    $ 93 "Comment"
    # Comment
    $ 94 "Home"
    movej([-3.5235366372186707, -1.9259070680664099, 2.3525050044875555, 0.20454112128959331, -0.22302944588515938, -0.6277049025321748], a=1.3962634015954636, v=1.0471975511965976)
  end
  def Test_Teach_Position():
    $ 95 "Test_Teach_Position" "noBreak"
    $ 96 "Home"
    movej([-3.5235366372186707, -1.9259070680664099, 2.3525050044875555, 0.20454112128959331, -0.22302944588515938, -0.6277049025321748], a=1.3962634015954636, v=1.0471975511965976)
    $ 100 "MoveJ"
    $ 101 "Waypoint_2" "breakAfter"
    set_tcp(p[0.0,0.0,0.019,0.0,0.0,0.0])
    movej(get_inverse_kin(Waypoint_2_p, qnear=Waypoint_2_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 102 "freedrive_m_var≔ False "
    global freedrive_m_var=  False  
    $ 103 "freedrive_m_var≔ True "
    global freedrive_m_var=  True  
    $ 104 "Popup: Move the robot to the peg center, then click 'Continue'"
    popup("Move the robot to the peg center, then click 'Continue'", "Message", False, False, blocking=True)
    $ 105 "freedrive_m_var≔ False "
    global freedrive_m_var=  False  
    $ 106 "Wait: 0.25"
    sleep(0.25)
    $ 107 "sync()"
    sync()
    $ 108 "tcp_pose≔get_actual_joint_positions()"
    global tcp_pose= get_actual_joint_positions ()
  end
  def Corner_Homing_BRB():
    $ 151 "Corner_Homing_BRB" "noBreak"
    $ 152 "'Use this program when tool is already positioned close to corner (back right bottom corner)'"
    # 'Use this program when tool is already positioned close to corner (back right bottom corner)'
    $ 153 "'tool flange will seek all 3 sides. will save those 5 locs in p__'"
    # 'tool flange will seek all 3 sides. will save those 5 locs in p__'
    $ 154 "align_tcp_left()"
    align_tcp_left()
    $ 155 "'right side'"
    # 'right side'
    $ 156 "MoveL"
    $ 157 "Direction: Base X-"
    global move_thread_flag_157=0
    thread move_thread_157():
      enter_critical
      move_thread_flag_157 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,0.0,0.0], 0.05)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_157 = 2
      exit_critical
    end
    move_thread_flag_157 = 0
    move_thread_han_157 = run move_thread_157()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_157 > 1):
        join move_thread_han_157
        $ 158 "Until (distance)"
        break
      end
      sync()
    end
    $ 159 "MoveL"
    $ 160 "Direction: Base Y-"
    global move_thread_flag_160=0
    thread move_thread_160():
      enter_critical
      move_thread_flag_160 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,-1.0,0.0], 1000.0)
      movel(towardsPos, a=1.2, v=0.05)
      move_thread_flag_160 = 2
      exit_critical
    end
    move_thread_flag_160 = 0
    move_thread_han_160 = run move_thread_160()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_160
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 161 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 162 "p11≔get_actual_tcp_pose()"
    global p11= get_actual_tcp_pose ()
    $ 163 "MoveL"
    $ 164 "Direction: Base Y+"
    global move_thread_flag_164=0
    thread move_thread_164():
      enter_critical
      move_thread_flag_164 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,1.0,0.0], 0.05)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_164 = 2
      exit_critical
    end
    move_thread_flag_164 = 0
    move_thread_han_164 = run move_thread_164()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_164 > 1):
        join move_thread_han_164
        $ 165 "Until (distance)"
        break
      end
      sync()
    end
    $ 166 "MoveL"
    $ 167 "Direction: Base X-"
    global move_thread_flag_167=0
    thread move_thread_167():
      enter_critical
      move_thread_flag_167 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,0.0,0.0], 0.15)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_167 = 2
      exit_critical
    end
    move_thread_flag_167 = 0
    move_thread_han_167 = run move_thread_167()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_167 > 1):
        join move_thread_han_167
        $ 168 "Until (distance)"
        break
      end
      sync()
    end
    $ 169 "MoveL"
    $ 170 "Direction: Base Y-"
    global move_thread_flag_170=0
    thread move_thread_170():
      enter_critical
      move_thread_flag_170 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,-1.0,0.0], 1000.0)
      movel(towardsPos, a=1.2, v=0.05)
      move_thread_flag_170 = 2
      exit_critical
    end
    move_thread_flag_170 = 0
    move_thread_han_170 = run move_thread_170()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_170
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 171 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 172 "p12≔get_actual_tcp_pose()"
    global p12= get_actual_tcp_pose ()
    $ 173 "MoveL"
    $ 174 "Direction: Base Y+"
    global move_thread_flag_174=0
    thread move_thread_174():
      enter_critical
      move_thread_flag_174 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,1.0,0.0], 0.05)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_174 = 2
      exit_critical
    end
    move_thread_flag_174 = 0
    move_thread_han_174 = run move_thread_174()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_174 > 1):
        join move_thread_han_174
        $ 175 "Until (distance)"
        break
      end
      sync()
    end
    $ 176 "MoveL"
    $ 177 "Direction: Base X+"
    global move_thread_flag_177=0
    thread move_thread_177():
      enter_critical
      move_thread_flag_177 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [1.0,0.0,0.0], 0.3)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_177 = 2
      exit_critical
    end
    move_thread_flag_177 = 0
    move_thread_han_177 = run move_thread_177()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_177 > 1):
        join move_thread_han_177
        $ 178 "Until (distance)"
        break
      end
      sync()
    end
    $ 179 "align_tcp_forward()"
    align_tcp_forward()
    $ 180 "'back side'"
    # 'back side'
    $ 181 "MoveL"
    $ 182 "Direction: Base Y-"
    global move_thread_flag_182=0
    thread move_thread_182():
      enter_critical
      move_thread_flag_182 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,-1.0,0.0], 0.1)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_182 = 2
      exit_critical
    end
    move_thread_flag_182 = 0
    move_thread_han_182 = run move_thread_182()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_182 > 1):
        join move_thread_han_182
        $ 183 "Until (distance)"
        break
      end
      sync()
    end
    $ 184 "MoveL"
    $ 185 "Direction: Base X-"
    global move_thread_flag_185=0
    thread move_thread_185():
      enter_critical
      move_thread_flag_185 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,0.0,0.0], 1000.0)
      movel(towardsPos, a=1.2, v=0.05)
      move_thread_flag_185 = 2
      exit_critical
    end
    move_thread_flag_185 = 0
    move_thread_han_185 = run move_thread_185()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_185
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 186 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 187 "p21≔get_actual_tcp_pose()"
    global p21= get_actual_tcp_pose ()
    $ 188 "MoveL"
    $ 189 "Direction: Base X+"
    global move_thread_flag_189=0
    thread move_thread_189():
      enter_critical
      move_thread_flag_189 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [1.0,0.0,0.0], 0.05)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_189 = 2
      exit_critical
    end
    move_thread_flag_189 = 0
    move_thread_han_189 = run move_thread_189()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_189 > 1):
        join move_thread_han_189
        $ 190 "Until (distance)"
        break
      end
      sync()
    end
    $ 191 "MoveL"
    $ 192 "Direction: Base Y-"
    global move_thread_flag_192=0
    thread move_thread_192():
      enter_critical
      move_thread_flag_192 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,-1.0,0.0], 0.15)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_192 = 2
      exit_critical
    end
    move_thread_flag_192 = 0
    move_thread_han_192 = run move_thread_192()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_192 > 1):
        join move_thread_han_192
        $ 193 "Until (distance)"
        break
      end
      sync()
    end
    $ 194 "MoveL"
    $ 195 "Direction: Base X-"
    global move_thread_flag_195=0
    thread move_thread_195():
      enter_critical
      move_thread_flag_195 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,0.0,0.0], 1000.0)
      movel(towardsPos, a=1.2, v=0.05)
      move_thread_flag_195 = 2
      exit_critical
    end
    move_thread_flag_195 = 0
    move_thread_han_195 = run move_thread_195()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_195
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 196 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 197 "p22≔get_actual_tcp_pose()"
    global p22= get_actual_tcp_pose ()
    $ 198 "MoveL"
    $ 199 "Direction: Base X+"
    global move_thread_flag_199=0
    thread move_thread_199():
      enter_critical
      move_thread_flag_199 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [1.0,0.0,0.0], 0.05)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_199 = 2
      exit_critical
    end
    move_thread_flag_199 = 0
    move_thread_han_199 = run move_thread_199()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_199 > 1):
        join move_thread_han_199
        $ 200 "Until (distance)"
        break
      end
      sync()
    end
    $ 201 "'regroup for up turn'"
    # 'regroup for up turn'
    $ 202 "MoveL"
    $ 203 "Direction: Base X+"
    global move_thread_flag_203=0
    thread move_thread_203():
      enter_critical
      move_thread_flag_203 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [1.0,0.0,0.0], 0.2)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_203 = 2
      exit_critical
    end
    move_thread_flag_203 = 0
    move_thread_han_203 = run move_thread_203()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_203 > 1):
        join move_thread_han_203
        $ 204 "Until (distance)"
        break
      end
      sync()
    end
    $ 205 "Direction: Base Y+"
    global move_thread_flag_205=0
    thread move_thread_205():
      enter_critical
      move_thread_flag_205 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,1.0,0.0], 0.5)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_205 = 2
      exit_critical
    end
    move_thread_flag_205 = 0
    move_thread_han_205 = run move_thread_205()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_205 > 1):
        join move_thread_han_205
        $ 206 "Until (distance)"
        break
      end
      sync()
    end
    $ 207 "MoveL"
    $ 208 "Direction: Base Z-"
    global move_thread_flag_208=0
    thread move_thread_208():
      enter_critical
      move_thread_flag_208 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_208 = 2
      exit_critical
    end
    move_thread_flag_208 = 0
    move_thread_han_208 = run move_thread_208()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_208 > 1):
        join move_thread_han_208
        $ 209 "Until (distance)"
        break
      end
      sync()
    end
    $ 210 "align_tcp_up()"
    align_tcp_up()
    $ 211 "MoveL"
    $ 212 "Direction: Base X-"
    global move_thread_flag_212=0
    thread move_thread_212():
      enter_critical
      move_thread_flag_212 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,0.0,0.0], 0.25)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_212 = 2
      exit_critical
    end
    move_thread_flag_212 = 0
    move_thread_han_212 = run move_thread_212()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_212 > 1):
        join move_thread_han_212
        $ 213 "Until (distance)"
        break
      end
      sync()
    end
    $ 214 "Direction: Base Y-"
    global move_thread_flag_214=0
    thread move_thread_214():
      enter_critical
      move_thread_flag_214 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,-1.0,0.0], 0.34)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_214 = 2
      exit_critical
    end
    move_thread_flag_214 = 0
    move_thread_han_214 = run move_thread_214()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_214 > 1):
        join move_thread_han_214
        $ 215 "Until (distance)"
        break
      end
      sync()
    end
    $ 216 "'bottom side'"
    # 'bottom side'
    $ 217 "MoveL"
    $ 218 "Direction: Base Z+"
    global move_thread_flag_218=0
    thread move_thread_218():
      enter_critical
      move_thread_flag_218 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 1000.0)
      movel(towardsPos, a=1.2, v=0.05)
      move_thread_flag_218 = 2
      exit_critical
    end
    move_thread_flag_218 = 0
    move_thread_han_218 = run move_thread_218()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_218
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 219 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 220 "p3≔get_actual_tcp_pose()"
    global p3= get_actual_tcp_pose ()
    $ 221 "MoveL"
    $ 222 "Direction: Base Z-"
    global move_thread_flag_222=0
    thread move_thread_222():
      enter_critical
      move_thread_flag_222 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,-1.0], 0.05)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_222 = 2
      exit_critical
    end
    move_thread_flag_222 = 0
    move_thread_han_222 = run move_thread_222()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_222 > 1):
        join move_thread_han_222
        $ 223 "Until (distance)"
        break
      end
      sync()
    end
    $ 224 "MoveL"
    $ 225 "Direction: Base X+"
    global move_thread_flag_225=0
    thread move_thread_225():
      enter_critical
      move_thread_flag_225 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [1.0,0.0,0.0], 0.1)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_225 = 2
      exit_critical
    end
    move_thread_flag_225 = 0
    move_thread_han_225 = run move_thread_225()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_225 > 1):
        join move_thread_han_225
        $ 226 "Until (distance)"
        break
      end
      sync()
    end
    $ 227 "Direction: Base Y+"
    global move_thread_flag_227=0
    thread move_thread_227():
      enter_critical
      move_thread_flag_227 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,1.0,0.0], 0.1)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_227 = 2
      exit_critical
    end
    move_thread_flag_227 = 0
    move_thread_han_227 = run move_thread_227()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_227 > 1):
        join move_thread_han_227
        $ 228 "Until (distance)"
        break
      end
      sync()
    end
  end
  def extrude_knife():
    $ 229 "extrude_knife" "noBreak"
    $ 230 "'Move to bucket'"
    # 'Move to bucket'
    $ 231 "MoveJ"
    $ 232 "Waypoint_3" "breakAfter"
    movej(get_inverse_kin(Waypoint_3_p, qnear=Waypoint_3_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 233 "MoveL"
    $ 234 "Waypoint_4" "breakAfter"
    movel(Waypoint_4_p, a=1.2, v=0.25)
    $ 235 "'extrude out a foot'"
    # 'extrude out a foot'
    $ 236 "Wait: 6.0"
    sleep(6.0)
    $ 237 "MoveL"
    $ 238 "'slice over knife'"
    # 'slice over knife'
    $ 239 "Waypoint_5" "breakAfter"
    movel(Waypoint_5_p, a=1.2, v=0.04)
    $ 240 "MoveL"
    $ 241 "Waypoint_6" "breakAfter"
    movel(Waypoint_6_p, a=1.2, v=0.25)
    $ 242 "'raise up away from knife'"
    # 'raise up away from knife'
    $ 243 "Home"
    movej([-3.5235366372186707, -1.9259070680664099, 2.3525050044875555, 0.20454112128959331, -0.22302944588515938, -0.6277049025321748], a=1.3962634015954636, v=1.0471975511965976)
  end
  def align_tcp_left():
    $ 244 "align_tcp_left" "noBreak"
    $ 245 "'this program aligns the tcp parallel to the y direction'"
    # 'this program aligns the tcp parallel to the y direction'
    $ 246 "cp≔get_actual_tcp_pose()"
    global cp= get_actual_tcp_pose ()
    $ 247 "aligned_y_pose≔p[cp[0],cp[1],cp[2],1.570796,0,0]"
    global aligned_y_pose=p[cp[0],cp[1],cp[2],1.570796,0,0]
    $ 248 "MoveJ"
    $ 249 "aligned_y_pose" "breakAfter"
    movej(aligned_y_pose, a=1.3962634015954636, v=1.0471975511965976)
  end
  def align_tcp_forward():
    $ 250 "align_tcp_forward" "noBreak"
    $ 251 "'this program aligns the tcp parallel to the y direction'"
    # 'this program aligns the tcp parallel to the y direction'
    $ 252 "cp≔get_actual_tcp_pose()"
    global cp= get_actual_tcp_pose ()
    $ 253 "aligned_y_pose≔p[cp[0],cp[1],cp[2],0,-1.570796,0]"
    global aligned_y_pose=p[cp[0],cp[1],cp[2],0,-1.570796,0]
    $ 254 "MoveJ"
    $ 255 "aligned_y_pose" "breakAfter"
    movej(aligned_y_pose, a=1.3962634015954636, v=1.0471975511965976)
  end
  def align_tcp_up():
    $ 256 "align_tcp_up" "noBreak"
    $ 257 "'this program aligns the tcp parallel to the y direction'"
    # 'this program aligns the tcp parallel to the y direction'
    $ 258 "cp≔get_actual_tcp_pose()"
    global cp= get_actual_tcp_pose ()
    $ 259 "aligned_y_pose≔p[cp[0],cp[1],cp[2],0,0,0]"
    global aligned_y_pose=p[cp[0],cp[1],cp[2],0,0,0]
    $ 260 "MoveJ"
    $ 261 "aligned_y_pose" "breakAfter"
    movej(aligned_y_pose, a=1.3962634015954636, v=1.0471975511965976)
  end
  def Corner_Homing_45():
    $ 262 "Corner_Homing_45" "noBreak"
    $ 263 "'Use this program when tool is already positioned close to corner at 45deg'"
    # 'Use this program when tool is already positioned close to corner at 45deg'
    $ 264 "'tool flange will seek all 3 sides. will save those 5 locs in p__'"
    # 'tool flange will seek all 3 sides. will save those 5 locs in p__'
    $ 265 "Set"
    set_tcp(p[0.0035133086975220607,-0.05007958866001844,0.23127815776365185,0.0,0.0,0.0])
    $ 266 "'dummy move below for debug'"
    # 'dummy move below for debug'
    $ 271 "Wait: 1.0"
    sleep(1.0)
    $ 272 "tp≔get_actual_tcp_pose()"
    global tp= get_actual_tcp_pose ()
    $ 273 "Script: analyze_touchpoints.script"
    # this file creates the function for analyzing touchpoints
    # define pi
    pi = 3.1415926535
    
    # this is the main entry point for calculations.
    # it takes in the 5 points, analyzes the shape of the box, and then calculates path points and returns them
    # specifically for Down, Over, then Around (DOtA)
    # specifically for right-sided boxes (vertical weld on right side of edge)
    def main_calculate_right(p11, p12, p21, p22, p3):
        struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
        struct2 = calculate_DOtA_points_right(struct1)
        return struct2
    end
    
    # this is the main entry point for calculations.
    # it takes in the 5 points, analyzes the shape of the box, and then calculates path points and returns them
    # specifically for Down, Over, then Around (DOtA)
    # specifically for left-sided boxes (vertical weld on left side of edge)
    def main_calculate_left(p11, p12, p21, p22, p3):
        struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
        struct2 = calculate_DOtA_points_left(struct1)
        return struct2
    end
    
    # it takes 5 arguments as points
    # it returns a struct containing: (pointintersect, pointapproach1, pointapproach2, point1, point2, point3, point4, point5, pointreturn1, heading1, heading2, heading3, path2r1, path2r2, path2l1, path2l2)
    # specifically for Around then Up (AtU)
    def analyze_touchpoints(p11, p12, p21, p22, p3):
      # FIND THE INTERSECTION
      # comment get the z
      zcoord=p3[2]
    
      # get the raw points from the first line
      l1p1x=p11[0]
      l1p1y=p11[1]
      l1p2x=p12[0]
      l1p2y=p12[1]
    
      # equate the first line in 2d space
      ml1 = (l1p2y-l1p1y) / (l1p2x-l1p1x)
    
      # b = y - mx
      bl1 = l1p1y - ml1 * l1p1x
    
      # get the raw points from the second line
      l2p1x=p21[0]
      l2p1y=p21[1]
      l2p2x=p22[0]
      l2p2y=p22[1]
    
      # equate the second line in 2d space
      ml2 = (l2p2y-l2p1y) / (l2p2x-l2p1x)
    
      # b = y - mx
      bl2 = l2p1y - ml2 * l2p1x
    
    
      # find the intersection of the two lines
      # m1x+b1 = m2x+b2
      # m1x - m2x = b2 - b1
      # x = (b2-b1) / (m1-m2)
      xintersect = (bl2-bl1) / (ml1-ml2)
      yintersect = ml1 * xintersect + bl1
    
      #FIND THE VECTORS
      #define a vector from the intersection to the second point on the first line
      l1delxfull = l1p2x - xintersect
      l1delyfull = l1p2y - yintersect
    
      l1delmag = sqrt(l1delxfull*l1delxfull + l1delyfull*l1delyfull)
    
      l1delxunit = l1delxfull / l1delmag
      l1delyunit = l1delyfull / l1delmag
    
      #define a vector from the intersection to the second point on the second line
      l2delxfull = l2p2x - xintersect
      l2delyfull = l2p2y - yintersect
    
      l2delmag = sqrt(l2delxfull*l2delxfull + l2delyfull*l2delyfull)
    
      l2delxunit = l2delxfull / l2delmag
      l2delyunit = l2delyfull / l2delmag
    
      # FIND THE FOUR POINTS ON THE LINES
      # find locations 8 inches away from  intersect point
      # CONST
      welddistance = 8
      roundoverdistance = 0.05
      zup = .375
      # inches
      wd = welddistance * 25.4 / 1000
      rod = roundoverdistance * 25.4 / 1000
      zup = zup * 25.4 / 1000
    
      # now we have the unit vector. extend the weld distance from the intersection
      x = xintersect + l1delxunit * wd
      y = yintersect + l1delyunit * wd
      z = zcoord + zup
    
      point1 = p[x,y,z,1.570796,0,0] # dummy orientation for now
    
      x = xintersect + l1delxunit * rod
      y = yintersect + l1delyunit * rod
    
      point2 = p[x,y,z,1.570796,0,0]
    
      # now we have the unit vector. extend the weld distance from the intersection
      x = xintersect + l2delxunit * wd
      y = yintersect + l2delyunit * wd
    
      point5 = p[x,y,z,0,-1.570796,0]
    
      x = xintersect + l2delxunit * rod
      y = yintersect + l2delyunit * rod
    
      point4 = p[x,y,z,0,-1.570796,0]
    
      #DEFINE APPROACH POINTS
      pointintersect = p[xintersect,yintersect,zcoord,0,0,0]
      pointapproach1 = p[xintersect+0.1,yintersect+0.1,z,1.570796,0,0]
      pointapproach2 = p[point1[0], point1[1]+0.1, point1[2], point1[3], point1[4], point1[5]]
      pointreturn1 = p[point5[0]+0.1, point5[1], point5[2], point5[3], point5[4], point5[5]]
    
      #FIND HEADINGS
      #for each heading, find the angle of the line with respect to the pos x axis. then add/subtract 90 degrees because you want to be perpendicular to that
      headingvector1 = convert_uv_to_heading(l1delxunit, l1delyunit)
      headingvector2 = convert_uv_to_heading(l2delxunit, l2delyunit)
      # find halfway heading
      heading2 = (headingvector1 + headingvector2)/2
      # find headings that the robot should face while traveling, perpendicular to the vectors of the sides of the box
      heading1 = headingvector1 + pi/2
      heading3 = headingvector2 - pi/2
    
      #FIND POINT 3
      #see if we have to / can find point 3
      findpoint3 = True
      if roundoverdistance == 0:
        findpoint3 = False
      end
      if findpoint3:
        # i need to find the point3 such that the arc from p2 to p3 to p4 is tangent to p1-p2 and p4-p5. making this a smooth path will be good
        # the direction of movement is from pointintersect in the direction of heading2
        # how much movement though? this will depend on whether it is actually a 90 degree angle or not.
        # first, find the perpendicular lines through points 2 and 4
        perp2 = find_perpendicular_line(ml1, point2[0], point2[1])
        perp4 = find_perpendicular_line(ml2, point4[0], point4[1])
        # next, find the intersection of those two lines
        perpintersect = find_intersection(perp2[0], perp2[1], perp4[0], perp4[1])
        radiusofcircle = distance_between(perpintersect[0], perpintersect[1], 0, point2[0], point2[1], 0)
        # find a vector the direction of heading2
        uvx = cos(heading2)
        uvy = sin(heading2)
        # compute point3. pass in negative radius because the direction is into the tank but we want to move from the intersection out to the rounded edge.
        point3coords = add_vectordistance_to_point(perpintersect[0], perpintersect[1], z, uvx, uvy, 0, -1 * radiusofcircle)
        point3 = p[point3coords[0], point3coords[1], point3coords[2], 0, 0, 0]
      end
    
      #APPLY ACTUAL RXRYRZ TO POINTS
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      pointapproach1 = p[pointapproach1[0], pointapproach1[1], pointapproach1[2], rx, ry, rz]
      pointapproach2 = p[pointapproach2[0], pointapproach2[1], pointapproach2[2], rx, ry, rz]
      point1 = p[point1[0], point1[1], point1[2], rx, ry, rz]
      point2 = p[point2[0], point2[1], point2[2], rx, ry, rz]
      rxryrz = convert_heading_to_axang(heading2)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      if findpoint3:
        point3 = p[point3[0], point3[1], point3[2], rx, ry, rz]
      else:
        point3 = point2
      end
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point4 = p[point4[0], point4[1], point4[2], rx, ry, rz]
      point5 = p[point5[0], point5[1], point5[2], rx, ry, rz]
      pointreturn1 = p[pointreturn1[0], pointreturn1[1], pointreturn1[2], rx, ry, rz]
    
      #find path2 (the part that goes up)
      four_vertical_points = find_vertical_points(pointintersect, l1delxunit, l1delyunit, l2delxunit, l2delyunit, zup, wd, heading1, heading3)
      path2r1 = four_vertical_points[0]
      path2r2 = four_vertical_points[1]
      path2l1 = four_vertical_points[2]
      path2l2 = four_vertical_points[3]
    
      #RETURN STRUCT
      ret = struct(pointintersect=pointintersect, pointapproach1=pointapproach1, pointapproach2=pointapproach2, point1=point1, point2=point2, point3=point3, point4=point4, point5=point5, pointreturn1=pointreturn1, heading1=heading1, heading2=heading2, heading3=heading3, path2r1=path2r1, path2r2=path2r2, path2l1=path2l1, path2l2=path2l2)
      return ret
    end
    
    # it takes 5 arguments as points
    # it returns a struct containing: (pointintersect, heading1, heading2, heading3, l1delxunit, l1delyunit, l2delxunit, l2delyunit)
    def analyze_touchpoints_only(p11, p12, p21, p22, p3):
      # FIND THE INTERSECTION
      # comment get the z
      zcoord=p3[2]
    
      # get the raw points from the first line
      l1p1x=p11[0]
      l1p1y=p11[1]
      l1p2x=p12[0]
      l1p2y=p12[1]
    
      # equate the first line in 2d space
      ml1 = (l1p2y-l1p1y) / (l1p2x-l1p1x)
    
      # b = y - mx
      bl1 = l1p1y - ml1 * l1p1x
    
      # get the raw points from the second line
      l2p1x=p21[0]
      l2p1y=p21[1]
      l2p2x=p22[0]
      l2p2y=p22[1]
    
      # equate the second line in 2d space
      ml2 = (l2p2y-l2p1y) / (l2p2x-l2p1x)
    
      # b = y - mx
      bl2 = l2p1y - ml2 * l2p1x
    
    
      # find the intersection of the two lines
      # m1x+b1 = m2x+b2
      # m1x - m2x = b2 - b1
      # x = (b2-b1) / (m1-m2)
      xintersect = (bl2-bl1) / (ml1-ml2)
      yintersect = ml1 * xintersect + bl1
    
      pointintersect = p[xintersect,yintersect,zcoord,0,0,0]
    
      #FIND THE VECTORS
      #define a vector from the intersection to the second point on the first line
      l1delxfull = l1p2x - xintersect
      l1delyfull = l1p2y - yintersect
    
      l1delmag = sqrt(l1delxfull*l1delxfull + l1delyfull*l1delyfull)
    
      l1delxunit = l1delxfull / l1delmag
      l1delyunit = l1delyfull / l1delmag
    
      #define a vector from the intersection to the second point on the second line
      l2delxfull = l2p2x - xintersect
      l2delyfull = l2p2y - yintersect
    
      l2delmag = sqrt(l2delxfull*l2delxfull + l2delyfull*l2delyfull)
    
      l2delxunit = l2delxfull / l2delmag
      l2delyunit = l2delyfull / l2delmag
    
      #FIND HEADINGS
      #for each heading, find the angle of the line with respect to the pos x axis. then add/subtract 90 degrees because you want to be perpendicular to that
      headingvector1 = convert_uv_to_heading(l1delxunit, l1delyunit)
      headingvector2 = convert_uv_to_heading(l2delxunit, l2delyunit)
      # find halfway heading
      heading2 = (headingvector1 + headingvector2)/2
      # find headings that the robot should face while traveling, perpendicular to the vectors of the sides of the box
      heading1 = headingvector1 + pi/2
      heading3 = headingvector2 - pi/2
    
      #RETURN STRUCT
      ret = struct(pointintersect=pointintersect, heading1=heading1, heading2=heading2, heading3=heading3, l1delxunit=l1delxunit, l1delyunit=l1delyunit, l2delxunit=l2delxunit, l2delyunit=l2delyunit)
      return ret
    end
    
    # given a struct from analyze_touchpoints_only(), calculate the points
    def calculate_DOtA_points_right(struct1):
        # get the stuff from the struct
        pointintersect = struct1[0]
        heading1 = struct1[1]
        heading2 = struct1[2]
        heading3 = struct1[3]
        l1delxunit = struct1[4]
        l1delyunit = struct1[5]
        l2delxunit = struct1[6]
        l2delyunit = struct1[7]
    
        # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
        # find locations 8 inches away from  intersect point
        # CONST
        welddistance = 8
        zup = .375
        # inches
        wd = welddistance * 25.4 / 1000
        zup = zup * 25.4 / 1000
    
        x = pointintersect[0] + l1delxunit * zup
        y = pointintersect[1] + l1delyunit * zup
        z = pointintersect[2] + zup
    
        #apply actual rxryrz to points
        # convert the headings to rxryrz and insert those values into the relevant points
        rxryrz = convert_heading_to_axang_preheatdown(heading1)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
    
        point1 = p[x, y, z + wd, rx, ry, rz]
        point2 = p[x, y, z, rx, ry, rz]
    
        # convert the headings to rxryrz and insert those values into the relevant points
        rxryrz = convert_heading_to_axang_ccw(heading1)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
    
        point4 = p[x, y, z, rx, ry, rz]
        x = x + l1delxunit * wd
        y = y + l1delyunit * wd
        point5 = p[x, y, z, rx, ry, rz]
    
        # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
        roundoverdistance = 0.05
        rod = roundoverdistance * 25.4 / 1000
    
        # now we have the unit vector. extend the weld distance from the intersection
        x = pointintersect[0] + l1delxunit * (zup)
        y = pointintersect[1] + l1delyunit * zup
        # convert the headings to rxryrz and insert those values into the relevant points
        rxryrz = convert_heading_to_axang(heading1)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
        point_1 = p[x, y, z, rx, ry, rz]
    
        x = pointintersect[0] + l1delxunit * rod
        y = pointintersect[1] + l1delyunit * rod
        point_2 = p[x, y, z, rx, ry, rz]
    
        # now we have the unit vector. extend the weld distance from the intersection
        x = pointintersect[0] + l2delxunit * wd
        y = pointintersect[1] + l2delyunit * wd
        # convert the headings to rxryrz and insert those values into the relevant points
        rxryrz = convert_heading_to_axang(heading3)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
        point_5 = p[x, y, z, rx, ry, rz]
    
        x = pointintersect[0] + l2delxunit * rod
        y = pointintersect[1] + l2delyunit * rod
        point_4 = p[x, y, z, rx, ry, rz]
    
        #FIND POINT 3
        # by calling analyze_touchpoints()
        atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
        point_3 = atret[5]
    
    
        struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5)
        return struct2
    end
    
    # given a struct from analyze_touchpoints_only(), calculate the points
    def calculate_DOtA_points_left(struct1):
        # get the stuff from the struct
        pointintersect = struct1[0]
        heading1 = struct1[1]
        heading2 = struct1[2]
        heading3 = struct1[3]
        l1delxunit = struct1[4]
        l1delyunit = struct1[5]
        l2delxunit = struct1[6]
        l2delyunit = struct1[7]
    
        # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
        # find locations 8 inches away from  intersect point
        # CONST
        welddistance = 8
        zup = .375
        # inches
        wd = welddistance * 25.4 / 1000
        zup = zup * 25.4 / 1000
    
        x = pointintersect[0] + l2delxunit * zup
        y = pointintersect[1] + l2delyunit * zup
        z = pointintersect[2] + zup
    
        #apply actual rxryrz to points
        # convert the headings to rxryrz and insert those values into the relevant points
        rxryrz = convert_heading_to_axang_preheatdown(heading3)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
    
        point1 = p[x, y, z + wd, rx, ry, rz]
        point2 = p[x, y, z, rx, ry, rz]
    
        # convert the headings to rxryrz and insert those values into the relevant points
        rxryrz = convert_heading_to_axang(heading3)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
    
        point4 = p[x, y, z, rx, ry, rz]
        x = x + l2delxunit * wd
        y = y + l2delyunit * wd
        point5 = p[x, y, z, rx, ry, rz]
    
        # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
        roundoverdistance = 0.05
        rod = roundoverdistance * 25.4 / 1000
    
        # now we have the unit vector. extend the weld distance from the intersection
        x = pointintersect[0] + l2delxunit * (zup)
        y = pointintersect[1] + l2delyunit * zup
        # convert the headings to rxryrz and insert those values into the relevant points
        rxryrz = convert_heading_to_axang_ccw(heading1)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
        point_1 = p[x, y, z, rx, ry, rz]
    
        x = pointintersect[0] + l2delxunit * rod
        y = pointintersect[1] + l2delyunit * rod
        point_2 = p[x, y, z, rx, ry, rz]
    
        # now we have the unit vector. extend the weld distance from the intersection
        x = pointintersect[0] + l1delxunit * wd
        y = pointintersect[1] + l1delyunit * wd
        # convert the headings to rxryrz and insert those values into the relevant points
        rxryrz = convert_heading_to_axang_ccw(heading3)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
        point_5 = p[x, y, z, rx, ry, rz]
    
        x = pointintersect[0] + l1delxunit * rod
        y = pointintersect[1] + l1delyunit * rod
        point_4 = p[x, y, z, rx, ry, rz]
    
        #FIND POINT 3
        # by calling analyze_touchpoints()
        atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
        point_3 = atret[5]
        #point 3 will not have the correct rxryrz though because now the gun needs to be face up.
        rxryrz = convert_heading_to_axang_ccw(heading2)
        rx = rxryrz[0]
        ry = rxryrz[1]
        rz = rxryrz[2]
        point_3 = p[point_3[0], point_3[1], point_3[2], rx, ry, rz]
    
        struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5)
        return struct2
    end
    
    # given a heading, (ccw from +x axis), find the mx+b slope
    # fails if exactly vertical
    def get_slope_from_heading(heading):
        return tan(heading)
    end
    
    
    
    # this function finds the points (and rxryrz) of the 2 points (start and end) of vertical weld section
    def find_vertical_points(pointintersect, l1delxunit, l1delyunit, l2delxunit, l2delyunit, offset, wd, heading1, heading3):
    
      # find right side stuff
      # find the point in 3d space that is .375 up and .375 over
      x = pointintersect[0] + l1delxunit * offset
      y = pointintersect[1] + l1delyunit * offset
      z = pointintersect[2] + offset
      # find rxryrz
      rxryrz = convert_heading_to_axang_preheatup(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      path2r1 = p[x, y, z, rx, ry, rz]
      path2r2 = p[x, y, z + wd, rx, ry, rz]
    
      # find left side
      # find the point in 3d space that is .375 up and .375 over
      x = pointintersect[0] + l2delxunit * offset
      y = pointintersect[1] + l2delyunit * offset
      z = pointintersect[2] + offset
      # find rxryrz
      rxryrz = convert_heading_to_axang_preheatup(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      path2l1 = p[x, y, z, rx, ry, rz]
      path2l2 = p[x, y, z + wd, rx, ry, rz]
    
      ret = struct(path2r1=path2r1, path2r2=path2r2, path2l1=path2l1, path2l2=path2l2)
      return ret
    end
    
    # this function converts a unit vector to its heading angle ccw from x+ axis
    # takes uvx and uvy
    # returns heading in radians
    def convert_uv_to_heading(uvx, uvy):
      baseang = atan(uvy/uvx)
      if uvx < 0:
        ang = baseang + pi
      elif uvy < 0:
        ang = baseang + pi * 2
      else:
        ang = baseang
      end
      return ang
    end
    
    # this function finds the equation of a line, perpendicular to a given line, and going through a given point
    # takes 3 arguments: m (the original line's slope), x (point's x coord), y (point's y coord). the b of the original line is not needed
    # returns a list of [m,b] (the slope and intercept of the new line)
    def find_perpendicular_line(origm, x, y):
      m = (1/origm) * -1
      b = y - m*x
      ret = [m, b]
      return ret
    end
    
    # this function finds the intersection point between two lines in the xy plane
    # takes 4 arguments: m1, b1, m2, b2
    # returns a list of [x,y] (the point of intersection)
    def find_intersection(m1, b1, m2, b2):
      # m1x+b1 = m2x+b2
      # m1x - m2x = b2 - b1
      # x = (b2-b1) / (m1-m2)
      x = (b2-b1) / (m1-m2)
      y = m1 * x + b1
      ret = [x, y]
      return ret
    end
    
    # this function finds the distance between 2 points in 3d space
    # it takes 6 arguments: x1, y1, z1, x2, y2, z2
    # it returns a distance
    def distance_between(x1, y1, z1, x2, y2, z2):
      distsquared = (x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)+(z2-z1)*(z2-z1)
      dist = sqrt(distsquared)
      return dist
    end
    
    # this function takes a point, a unit vector, and a distance, and adds the distance to the point in the direction of the unit vector (3d space)
    # it returns a point as a list of coordinates
    def add_vectordistance_to_point(xi, yi, zi, uvx, uvy, uvz, delta):
      xf = xi + uvx * delta
      yf = yi + uvy * delta
      zf = zi + uvz * delta
      ret = [xf, yf, zf]
      return ret
    end
    
    # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
    # this will point the gun in this heading with the bottom side of the gun facing up.
    # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
    def convert_heading_to_axang(heading):
     axisxraw = -1 * sin(heading)
     axisyraw = cos(heading) + 1
     axiszraw = sin(heading)
    
     magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
    
     axisxunit = axisxraw / magnitude
     axisyunit = axisyraw / magnitude
     axiszunit = axiszraw / magnitude
    
     angle = acos( (cos(heading) - 1) / 2 )
    
     rxout = axisxunit * angle
     ryout = axisyunit * angle
     rzout = axiszunit * angle
    
     return [rxout, ryout, rzout]
    end
    
    # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
    # this will point the gun in this heading with the preheat side of the gun tip facing up. Used for welding in a vertical path.
    # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
    def convert_heading_to_axang_preheatup(heading):
     axisxraw = -sin(heading) + 1
     axisyraw = cos(heading)
     axiszraw = cos(heading)
    
     magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
    
     axisxunit = axisxraw / magnitude
     axisyunit = axisyraw / magnitude
     axiszunit = axiszraw / magnitude
    
     angle = acos( (-sin(heading) - 1) / 2 )
    
     rxout = axisxunit * angle
     ryout = axisyunit * angle
     rzout = axiszunit * angle
    
     return [rxout, ryout, rzout]
    end
    
    # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
    # this will point the gun in this heading with the preheat side of the gun tip facing down. Used for welding in a vertical path downwards.
    # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
    def convert_heading_to_axang_preheatdown(heading):
     axisxraw = -sin(heading) - 1
     axisyraw = cos(heading)
     axiszraw = -cos(heading)
    
     magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
    
     axisxunit = axisxraw / magnitude
     axisyunit = axisyraw / magnitude
     axiszunit = axiszraw / magnitude
    
     angle = acos( (sin(heading) - 1) / 2 )
    
     rxout = axisxunit * angle
     ryout = axisyunit * angle
     rzout = axiszunit * angle
    
     return [rxout, ryout, rzout]
    end
    
    # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
    # this will point the gun in this heading with the preheat side of the gun tip facing right. Used for welding counterclockwise around the box.
    # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
    def convert_heading_to_axang_ccw(heading):
     axisxraw = -sin(heading)
     axisyraw = cos(heading) - 1
     axiszraw = -sin(heading)
    
     magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
    
     axisxunit = axisxraw / magnitude
     axisyunit = axisyraw / magnitude
     axiszunit = axiszraw / magnitude
    
     angle = acos( (-cos(heading) - 1) / 2 )
    
     rxout = axisxunit * angle
     ryout = axisyunit * angle
     rzout = axiszunit * angle
    
     return [rxout, ryout, rzout]
    end
    
    # this function is for getting the points along the path of the corner homing 45
    # point0 is the point where they touched
    def get_corner_homing_45_pathpoints(point0):
      p0x = point0[0]
      p0y = point0[1]
      p0z = point0[2]
      p0rx = point0[3]
      p0ry = point0[4]
      p0rz = point0[5]
    
      #constants
      #distances of how far away from point the touchpoints are
      d0 = 0.15 # how far from the box to retreat and approach
      d1 = 0.05
      d2 = 0.2
      sqrt2 = 0.707106781
    
      ph1 = p[p0x + d0, p0y, p0z + .05, p0rx, p0ry, p0rz] #approach point for turn
    
      ph2 = p[p0x+d0-d0*sqrt2-sqrt2*d1, p0y+d0*sqrt2+sqrt2*d1, p0z+.05, .445, -1.562, .483]
      ph3 = p[p0x+d0-d0*sqrt2-sqrt2*d2, p0y+d0*sqrt2+sqrt2*d2, p0z+.05, .445, -1.562, .483]
      ph4 = p[p0x+d0-d0*sqrt2-sqrt2*d1, p0y-d0*sqrt2-sqrt2*d1, p0z+.05, 1.699, 3.576, 1.841]
      ph5 = p[p0x+d0-d0*sqrt2-sqrt2*d2, p0y-d0*sqrt2-sqrt2*d2, p0z+.05, 1.699, 3.576, 1.841]
    
      # go back to ph1
      ph6 = p[p0x + .05, p0y, p0z -.05, 0, 0, 0] # approach point for under turn
      # moveL from ph1 to ph6
      ph7 = p[p0x-.05, p0y, p0z-.05, 0, 0, 0]
      ret = struct(ph1=ph1, ph2=ph2, ph3=ph3, ph4=ph4, ph5=ph5, ph6=ph6, ph7=ph7)
      return ret
    end
    $ 274 "path_pre≔get_corner_homing_45_pathpoints(tp)"
    global path_pre=get_corner_homing_45_pathpoints(tp)
    $ 275 "ph1≔path_pre[0]"
    global ph1=path_pre[0]
    $ 276 "ph2≔path_pre[1]"
    global ph2=path_pre[1]
    $ 277 "ph3≔path_pre[2]"
    global ph3=path_pre[2]
    $ 278 "ph4≔path_pre[3]"
    global ph4=path_pre[3]
    $ 279 "ph5≔path_pre[4]"
    global ph5=path_pre[4]
    $ 280 "ph6≔path_pre[5]"
    global ph6=path_pre[5]
    $ 281 "ph7≔path_pre[6]"
    global ph7=path_pre[6]
    $ 282 "MoveJ"
    $ 283 "ph1" "breakAfter"
    movej(ph1, a=1.3962634015954636, v=1.0471975511965976)
    $ 284 "ph2" "breakAfter"
    movej(ph2, a=1.3962634015954636, v=1.0471975511965976)
    $ 285 "MoveL"
    $ 286 "Direction: Base"
    global move_thread_flag_286=0
    thread move_thread_286():
      enter_critical
      move_thread_flag_286 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1,-1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.05)
      move_thread_flag_286 = 2
      exit_critical
    end
    move_thread_flag_286 = 0
    move_thread_han_286 = run move_thread_286()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_286
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 287 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 288 "p11≔get_actual_tcp_pose()"
    global p11= get_actual_tcp_pose ()
    $ 289 "MoveJ"
    $ 290 "ph3" "breakAfter"
    movej(ph3, a=1.3962634015954636, v=1.0471975511965976)
    $ 291 "MoveL"
    $ 292 "Direction: Base"
    global move_thread_flag_292=0
    thread move_thread_292():
      enter_critical
      move_thread_flag_292 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1,-1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.05)
      move_thread_flag_292 = 2
      exit_critical
    end
    move_thread_flag_292 = 0
    move_thread_han_292 = run move_thread_292()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_292
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 293 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 294 "p12≔get_actual_tcp_pose()"
    global p12= get_actual_tcp_pose ()
    $ 295 "MoveJ"
    $ 296 "ph3" "breakAfter"
    movej(ph3, a=1.3962634015954636, v=1.0471975511965976)
    $ 297 "Waypoint_10" "breakAfter"
    movej(get_inverse_kin(Waypoint_10_p, qnear=Waypoint_10_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 298 "MoveJ"
    $ 299 "Waypoint_11" "breakAfter"
    movej(get_inverse_kin(Waypoint_11_p, qnear=Waypoint_11_q), a=1.3962634015954636, v=0.3490658503988659)
    $ 300 "Waypoint_12" "breakAfter"
    movej(get_inverse_kin(Waypoint_12_p, qnear=Waypoint_12_q), a=1.3962634015954636, v=0.3490658503988659)
    $ 301 "MoveJ"
    $ 302 "ph4" "breakAfter"
    movej(ph4, a=1.3962634015954636, v=1.0471975511965976)
    $ 303 "MoveL"
    $ 304 "Direction: Base"
    global move_thread_flag_304=0
    thread move_thread_304():
      enter_critical
      move_thread_flag_304 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.05)
      move_thread_flag_304 = 2
      exit_critical
    end
    move_thread_flag_304 = 0
    move_thread_han_304 = run move_thread_304()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_304
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 305 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 306 "p21≔get_actual_tcp_pose()"
    global p21= get_actual_tcp_pose ()
    $ 307 "MoveJ"
    $ 308 "ph5" "breakAfter"
    movej(ph5, a=1.3962634015954636, v=1.0471975511965976)
    $ 309 "MoveL"
    $ 310 "Direction: Base"
    global move_thread_flag_310=0
    thread move_thread_310():
      enter_critical
      move_thread_flag_310 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [-1.0,1.0,0.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.05)
      move_thread_flag_310 = 2
      exit_critical
    end
    move_thread_flag_310 = 0
    move_thread_han_310 = run move_thread_310()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_310
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 311 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 312 "p22≔get_actual_tcp_pose()"
    global p22= get_actual_tcp_pose ()
    $ 313 "MoveJ"
    $ 314 "ph5" "breakAfter"
    movej(ph5, a=1.3962634015954636, v=1.0471975511965976)
    $ 315 "ph4" "breakAfter"
    movej(ph4, a=1.3962634015954636, v=1.0471975511965976)
    $ 316 "Waypoint_13" "breakAfter"
    movej(get_inverse_kin(Waypoint_13_p, qnear=Waypoint_13_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 317 "Waypoint_14" "breakAfter"
    movej(get_inverse_kin(Waypoint_14_p, qnear=Waypoint_14_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 318 "Waypoint_15" "breakAfter"
    movej(get_inverse_kin(Waypoint_15_p, qnear=Waypoint_15_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 319 "Waypoint_16" "breakAfter"
    movej(get_inverse_kin(Waypoint_16_p, qnear=Waypoint_16_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 320 "ph6" "breakAfter"
    movej(ph6, a=1.3962634015954636, v=1.0471975511965976)
    $ 321 "ph7" "breakAfter"
    movej(ph7, a=1.3962634015954636, v=1.0471975511965976)
    $ 322 "MoveL"
    $ 323 "Direction: Base Z+"
    global move_thread_flag_323=0
    thread move_thread_323():
      enter_critical
      move_thread_flag_323 = 1
      local towardsPos=calculate_point_to_move_towards(p[0.0,0.0,0.0,0.0,0.0,0.0], [0.0,0.0,1.0], 1000.0)
      movel(towardsPos, a=0.1, v=0.05)
      move_thread_flag_323 = 2
      exit_critical
    end
    move_thread_flag_323 = 0
    move_thread_han_323 = run move_thread_323()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_323
        stopl(3.0)
        local backTrackMovement=get_actual_joint_positions_history(stepsToRetract)
        local contactPose=get_forward_kin(backTrackMovement)
        local posDir=[targetTcpDirection[0],targetTcpDirection[1],targetTcpDirection[2]]
        local retractTo=contactPose
        if (norm(posDir) > 1e-6):
          local normalizedPosDir=normalize(posDir)
          local additionalRetraction=p[normalizedPosDir[0] * 0.0, normalizedPosDir[1] * 0.0, normalizedPosDir[2] * 0.0, 0, 0, 0]
          retractTo = pose_sub(contactPose, additionalRetraction)
        end
        movel(retractTo, a=3.0, v=0.1)
        $ 324 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    $ 325 "p3≔get_actual_tcp_pose()"
    global p3= get_actual_tcp_pose ()
    $ 326 "MoveJ"
    $ 327 "ph7" "breakAfter"
    movej(ph7, a=1.3962634015954636, v=1.0471975511965976)
    $ 328 "ph6" "breakAfter"
    movej(ph6, a=1.3962634015954636, v=1.0471975511965976)
    $ 329 "Waypoint_17" "breakAfter"
    movej(get_inverse_kin(Waypoint_17_p, qnear=Waypoint_17_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 330 "Waypoint_18" "breakAfter"
    movej(get_inverse_kin(Waypoint_18_p, qnear=Waypoint_18_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 331 "Home"
    movej([-3.5235366372186707, -1.9259070680664099, 2.3525050044875555, 0.20454112128959331, -0.22302944588515938, -0.6277049025321748], a=1.3962634015954636, v=1.0471975511965976)
    $ 332 "Comment"
    # Comment
    $ 333 "Comment"
    # Comment
    $ 334 "Comment"
    # Comment
    $ 335 "Comment"
    # Comment
    $ 336 "Comment"
    # Comment
    $ 337 "Comment"
    # Comment
  end
  $ 338 "Thread_1"
  thread Thread_1():
    while (True):
      $ 339 "Loop  True "
      while (  True  ):
        $ 340 "If freedrive_m_var≟ True "
        if (freedrive_m_var ==   True  ):
          $ 341 "freedrive_mode()"
          freedrive_mode()
        else:
          $ 342 "Else" "noBreak"
          $ 343 "end_freedrive_mode()"
          end_freedrive_mode()
        end
        $ 344 "sync()"
        sync()
      end
    end
  end
  threadId_Thread_1 = run Thread_1()
  $ 2 "Robot Program"
  $ 3 "'start of main program'"
  # 'start of main program'
  $ 4 "Home"
  movej([-3.5235366372186707, -1.9259070680664099, 2.3525050044875555, 0.20454112128959331, -0.22302944588515938, -0.6277049025321748], a=1.3962634015954636, v=1.0471975511965976)
  $ 5 "Set"
  set_tcp(p[0.0035133086975220607,-0.05007958866001844,0.23127815776365185,0.0,0.0,0.0])
  $ 6 "Test_Teach_Position()"
  Test_Teach_Position()
  $ 7 "Set"
  set_tcp(p[0.0035133086975220607,-0.05007958866001844,0.23127815776365185,0.0,0.0,0.0])
  $ 8 "Corner_Homing_45()"
  Corner_Homing_45()
  $ 9 "Set"
  set_tcp(p[0.00838539968723857,-0.33324903375023873,0.07852362563148635,1.2092,-1.2092,1.2092])
  $ 10 "extrude_knife()"
  extrude_knife()
  $ 11 "Script: analyze_touchpoints.script"
  # this file creates the function for analyzing touchpoints
  # define pi
  pi = 3.1415926535
  
  # this is the main entry point for calculations.
  # it takes in the 5 points, analyzes the shape of the box, and then calculates path points and returns them
  # specifically for Down, Over, then Around (DOtA)
  # specifically for right-sided boxes (vertical weld on right side of edge)
  def main_calculate_right(p11, p12, p21, p22, p3):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      struct2 = calculate_DOtA_points_right(struct1)
      return struct2
  end
  
  # this is the main entry point for calculations.
  # it takes in the 5 points, analyzes the shape of the box, and then calculates path points and returns them
  # specifically for Down, Over, then Around (DOtA)
  # specifically for left-sided boxes (vertical weld on left side of edge)
  def main_calculate_left(p11, p12, p21, p22, p3):
      struct1 = analyze_touchpoints_only(p11, p12, p21, p22, p3)
      struct2 = calculate_DOtA_points_left(struct1)
      return struct2
  end
  
  # it takes 5 arguments as points
  # it returns a struct containing: (pointintersect, pointapproach1, pointapproach2, point1, point2, point3, point4, point5, pointreturn1, heading1, heading2, heading3, path2r1, path2r2, path2l1, path2l2)
  # specifically for Around then Up (AtU)
  def analyze_touchpoints(p11, p12, p21, p22, p3):
    # FIND THE INTERSECTION
    # comment get the z
    zcoord=p3[2]
  
    # get the raw points from the first line
    l1p1x=p11[0]
    l1p1y=p11[1]
    l1p2x=p12[0]
    l1p2y=p12[1]
  
    # equate the first line in 2d space
    ml1 = (l1p2y-l1p1y) / (l1p2x-l1p1x)
  
    # b = y - mx
    bl1 = l1p1y - ml1 * l1p1x
  
    # get the raw points from the second line
    l2p1x=p21[0]
    l2p1y=p21[1]
    l2p2x=p22[0]
    l2p2y=p22[1]
  
    # equate the second line in 2d space
    ml2 = (l2p2y-l2p1y) / (l2p2x-l2p1x)
  
    # b = y - mx
    bl2 = l2p1y - ml2 * l2p1x
  
  
    # find the intersection of the two lines
    # m1x+b1 = m2x+b2
    # m1x - m2x = b2 - b1
    # x = (b2-b1) / (m1-m2)
    xintersect = (bl2-bl1) / (ml1-ml2)
    yintersect = ml1 * xintersect + bl1
  
    #FIND THE VECTORS
    #define a vector from the intersection to the second point on the first line
    l1delxfull = l1p2x - xintersect
    l1delyfull = l1p2y - yintersect
  
    l1delmag = sqrt(l1delxfull*l1delxfull + l1delyfull*l1delyfull)
  
    l1delxunit = l1delxfull / l1delmag
    l1delyunit = l1delyfull / l1delmag
  
    #define a vector from the intersection to the second point on the second line
    l2delxfull = l2p2x - xintersect
    l2delyfull = l2p2y - yintersect
  
    l2delmag = sqrt(l2delxfull*l2delxfull + l2delyfull*l2delyfull)
  
    l2delxunit = l2delxfull / l2delmag
    l2delyunit = l2delyfull / l2delmag
  
    # FIND THE FOUR POINTS ON THE LINES
    # find locations 8 inches away from  intersect point
    # CONST
    welddistance = 8
    roundoverdistance = 0.05
    zup = .375
    # inches
    wd = welddistance * 25.4 / 1000
    rod = roundoverdistance * 25.4 / 1000
    zup = zup * 25.4 / 1000
  
    # now we have the unit vector. extend the weld distance from the intersection
    x = xintersect + l1delxunit * wd
    y = yintersect + l1delyunit * wd
    z = zcoord + zup
  
    point1 = p[x,y,z,1.570796,0,0] # dummy orientation for now
  
    x = xintersect + l1delxunit * rod
    y = yintersect + l1delyunit * rod
  
    point2 = p[x,y,z,1.570796,0,0]
  
    # now we have the unit vector. extend the weld distance from the intersection
    x = xintersect + l2delxunit * wd
    y = yintersect + l2delyunit * wd
  
    point5 = p[x,y,z,0,-1.570796,0]
  
    x = xintersect + l2delxunit * rod
    y = yintersect + l2delyunit * rod
  
    point4 = p[x,y,z,0,-1.570796,0]
  
    #DEFINE APPROACH POINTS
    pointintersect = p[xintersect,yintersect,zcoord,0,0,0]
    pointapproach1 = p[xintersect+0.1,yintersect+0.1,z,1.570796,0,0]
    pointapproach2 = p[point1[0], point1[1]+0.1, point1[2], point1[3], point1[4], point1[5]]
    pointreturn1 = p[point5[0]+0.1, point5[1], point5[2], point5[3], point5[4], point5[5]]
  
    #FIND HEADINGS
    #for each heading, find the angle of the line with respect to the pos x axis. then add/subtract 90 degrees because you want to be perpendicular to that
    headingvector1 = convert_uv_to_heading(l1delxunit, l1delyunit)
    headingvector2 = convert_uv_to_heading(l2delxunit, l2delyunit)
    # find halfway heading
    heading2 = (headingvector1 + headingvector2)/2
    # find headings that the robot should face while traveling, perpendicular to the vectors of the sides of the box
    heading1 = headingvector1 + pi/2
    heading3 = headingvector2 - pi/2
  
    #FIND POINT 3
    #see if we have to / can find point 3
    findpoint3 = True
    if roundoverdistance == 0:
      findpoint3 = False
    end
    if findpoint3:
      # i need to find the point3 such that the arc from p2 to p3 to p4 is tangent to p1-p2 and p4-p5. making this a smooth path will be good
      # the direction of movement is from pointintersect in the direction of heading2
      # how much movement though? this will depend on whether it is actually a 90 degree angle or not.
      # first, find the perpendicular lines through points 2 and 4
      perp2 = find_perpendicular_line(ml1, point2[0], point2[1])
      perp4 = find_perpendicular_line(ml2, point4[0], point4[1])
      # next, find the intersection of those two lines
      perpintersect = find_intersection(perp2[0], perp2[1], perp4[0], perp4[1])
      radiusofcircle = distance_between(perpintersect[0], perpintersect[1], 0, point2[0], point2[1], 0)
      # find a vector the direction of heading2
      uvx = cos(heading2)
      uvy = sin(heading2)
      # compute point3. pass in negative radius because the direction is into the tank but we want to move from the intersection out to the rounded edge.
      point3coords = add_vectordistance_to_point(perpintersect[0], perpintersect[1], z, uvx, uvy, 0, -1 * radiusofcircle)
      point3 = p[point3coords[0], point3coords[1], point3coords[2], 0, 0, 0]
    end
  
    #APPLY ACTUAL RXRYRZ TO POINTS
    # convert the headings to rxryrz and insert those values into the relevant points
    rxryrz = convert_heading_to_axang(heading1)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    pointapproach1 = p[pointapproach1[0], pointapproach1[1], pointapproach1[2], rx, ry, rz]
    pointapproach2 = p[pointapproach2[0], pointapproach2[1], pointapproach2[2], rx, ry, rz]
    point1 = p[point1[0], point1[1], point1[2], rx, ry, rz]
    point2 = p[point2[0], point2[1], point2[2], rx, ry, rz]
    rxryrz = convert_heading_to_axang(heading2)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    if findpoint3:
      point3 = p[point3[0], point3[1], point3[2], rx, ry, rz]
    else:
      point3 = point2
    end
    rxryrz = convert_heading_to_axang(heading3)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    point4 = p[point4[0], point4[1], point4[2], rx, ry, rz]
    point5 = p[point5[0], point5[1], point5[2], rx, ry, rz]
    pointreturn1 = p[pointreturn1[0], pointreturn1[1], pointreturn1[2], rx, ry, rz]
  
    #find path2 (the part that goes up)
    four_vertical_points = find_vertical_points(pointintersect, l1delxunit, l1delyunit, l2delxunit, l2delyunit, zup, wd, heading1, heading3)
    path2r1 = four_vertical_points[0]
    path2r2 = four_vertical_points[1]
    path2l1 = four_vertical_points[2]
    path2l2 = four_vertical_points[3]
  
    #RETURN STRUCT
    ret = struct(pointintersect=pointintersect, pointapproach1=pointapproach1, pointapproach2=pointapproach2, point1=point1, point2=point2, point3=point3, point4=point4, point5=point5, pointreturn1=pointreturn1, heading1=heading1, heading2=heading2, heading3=heading3, path2r1=path2r1, path2r2=path2r2, path2l1=path2l1, path2l2=path2l2)
    return ret
  end
  
  # it takes 5 arguments as points
  # it returns a struct containing: (pointintersect, heading1, heading2, heading3, l1delxunit, l1delyunit, l2delxunit, l2delyunit)
  def analyze_touchpoints_only(p11, p12, p21, p22, p3):
    # FIND THE INTERSECTION
    # comment get the z
    zcoord=p3[2]
  
    # get the raw points from the first line
    l1p1x=p11[0]
    l1p1y=p11[1]
    l1p2x=p12[0]
    l1p2y=p12[1]
  
    # equate the first line in 2d space
    ml1 = (l1p2y-l1p1y) / (l1p2x-l1p1x)
  
    # b = y - mx
    bl1 = l1p1y - ml1 * l1p1x
  
    # get the raw points from the second line
    l2p1x=p21[0]
    l2p1y=p21[1]
    l2p2x=p22[0]
    l2p2y=p22[1]
  
    # equate the second line in 2d space
    ml2 = (l2p2y-l2p1y) / (l2p2x-l2p1x)
  
    # b = y - mx
    bl2 = l2p1y - ml2 * l2p1x
  
  
    # find the intersection of the two lines
    # m1x+b1 = m2x+b2
    # m1x - m2x = b2 - b1
    # x = (b2-b1) / (m1-m2)
    xintersect = (bl2-bl1) / (ml1-ml2)
    yintersect = ml1 * xintersect + bl1
  
    pointintersect = p[xintersect,yintersect,zcoord,0,0,0]
  
    #FIND THE VECTORS
    #define a vector from the intersection to the second point on the first line
    l1delxfull = l1p2x - xintersect
    l1delyfull = l1p2y - yintersect
  
    l1delmag = sqrt(l1delxfull*l1delxfull + l1delyfull*l1delyfull)
  
    l1delxunit = l1delxfull / l1delmag
    l1delyunit = l1delyfull / l1delmag
  
    #define a vector from the intersection to the second point on the second line
    l2delxfull = l2p2x - xintersect
    l2delyfull = l2p2y - yintersect
  
    l2delmag = sqrt(l2delxfull*l2delxfull + l2delyfull*l2delyfull)
  
    l2delxunit = l2delxfull / l2delmag
    l2delyunit = l2delyfull / l2delmag
  
    #FIND HEADINGS
    #for each heading, find the angle of the line with respect to the pos x axis. then add/subtract 90 degrees because you want to be perpendicular to that
    headingvector1 = convert_uv_to_heading(l1delxunit, l1delyunit)
    headingvector2 = convert_uv_to_heading(l2delxunit, l2delyunit)
    # find halfway heading
    heading2 = (headingvector1 + headingvector2)/2
    # find headings that the robot should face while traveling, perpendicular to the vectors of the sides of the box
    heading1 = headingvector1 + pi/2
    heading3 = headingvector2 - pi/2
  
    #RETURN STRUCT
    ret = struct(pointintersect=pointintersect, heading1=heading1, heading2=heading2, heading3=heading3, l1delxunit=l1delxunit, l1delyunit=l1delyunit, l2delxunit=l2delxunit, l2delyunit=l2delyunit)
    return ret
  end
  
  # given a struct from analyze_touchpoints_only(), calculate the points
  def calculate_DOtA_points_right(struct1):
      # get the stuff from the struct
      pointintersect = struct1[0]
      heading1 = struct1[1]
      heading2 = struct1[2]
      heading3 = struct1[3]
      l1delxunit = struct1[4]
      l1delyunit = struct1[5]
      l2delxunit = struct1[6]
      l2delyunit = struct1[7]
  
      # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
      # find locations 8 inches away from  intersect point
      # CONST
      welddistance = 8
      zup = .375
      # inches
      wd = welddistance * 25.4 / 1000
      zup = zup * 25.4 / 1000
  
      x = pointintersect[0] + l1delxunit * zup
      y = pointintersect[1] + l1delyunit * zup
      z = pointintersect[2] + zup
  
      #apply actual rxryrz to points
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_preheatdown(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point1 = p[x, y, z + wd, rx, ry, rz]
      point2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point4 = p[x, y, z, rx, ry, rz]
      x = x + l1delxunit * wd
      y = y + l1delyunit * wd
      point5 = p[x, y, z, rx, ry, rz]
  
      # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
      roundoverdistance = 0.05
      rod = roundoverdistance * 25.4 / 1000
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l1delxunit * (zup)
      y = pointintersect[1] + l1delyunit * zup
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_1 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l1delxunit * rod
      y = pointintersect[1] + l1delyunit * rod
      point_2 = p[x, y, z, rx, ry, rz]
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l2delxunit * wd
      y = pointintersect[1] + l2delyunit * wd
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_5 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l2delxunit * rod
      y = pointintersect[1] + l2delyunit * rod
      point_4 = p[x, y, z, rx, ry, rz]
  
      #FIND POINT 3
      # by calling analyze_touchpoints()
      atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
      point_3 = atret[5]
  
  
      struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5)
      return struct2
  end
  
  # given a struct from analyze_touchpoints_only(), calculate the points
  def calculate_DOtA_points_left(struct1):
      # get the stuff from the struct
      pointintersect = struct1[0]
      heading1 = struct1[1]
      heading2 = struct1[2]
      heading3 = struct1[3]
      l1delxunit = struct1[4]
      l1delyunit = struct1[5]
      l2delxunit = struct1[6]
      l2delyunit = struct1[7]
  
      # FIND THE POINTS ON THE LINES OF THE FIRST TURN PATH
      # find locations 8 inches away from  intersect point
      # CONST
      welddistance = 8
      zup = .375
      # inches
      wd = welddistance * 25.4 / 1000
      zup = zup * 25.4 / 1000
  
      x = pointintersect[0] + l2delxunit * zup
      y = pointintersect[1] + l2delyunit * zup
      z = pointintersect[2] + zup
  
      #apply actual rxryrz to points
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_preheatdown(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point1 = p[x, y, z + wd, rx, ry, rz]
      point2 = p[x, y, z, rx, ry, rz]
  
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
  
      point4 = p[x, y, z, rx, ry, rz]
      x = x + l2delxunit * wd
      y = y + l2delyunit * wd
      point5 = p[x, y, z, rx, ry, rz]
  
      # FIND THE POINTS ON THE LINES OF THE SECOND AROUND PATH
      roundoverdistance = 0.05
      rod = roundoverdistance * 25.4 / 1000
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l2delxunit * (zup)
      y = pointintersect[1] + l2delyunit * zup
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading1)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_1 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l2delxunit * rod
      y = pointintersect[1] + l2delyunit * rod
      point_2 = p[x, y, z, rx, ry, rz]
  
      # now we have the unit vector. extend the weld distance from the intersection
      x = pointintersect[0] + l1delxunit * wd
      y = pointintersect[1] + l1delyunit * wd
      # convert the headings to rxryrz and insert those values into the relevant points
      rxryrz = convert_heading_to_axang_ccw(heading3)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_5 = p[x, y, z, rx, ry, rz]
  
      x = pointintersect[0] + l1delxunit * rod
      y = pointintersect[1] + l1delyunit * rod
      point_4 = p[x, y, z, rx, ry, rz]
  
      #FIND POINT 3
      # by calling analyze_touchpoints()
      atret = analyze_touchpoints(point_2, point_1, point_4, point_5, pointintersect)
      point_3 = atret[5]
      #point 3 will not have the correct rxryrz though because now the gun needs to be face up.
      rxryrz = convert_heading_to_axang_ccw(heading2)
      rx = rxryrz[0]
      ry = rxryrz[1]
      rz = rxryrz[2]
      point_3 = p[point_3[0], point_3[1], point_3[2], rx, ry, rz]
  
      struct2 = struct(point1=point1, point2=point2, point4=point4, point5=point5, point_1=point_1, point_2=point_2, point_3=point_3, point_4=point_4, point_5=point_5)
      return struct2
  end
  
  # given a heading, (ccw from +x axis), find the mx+b slope
  # fails if exactly vertical
  def get_slope_from_heading(heading):
      return tan(heading)
  end
  
  
  
  # this function finds the points (and rxryrz) of the 2 points (start and end) of vertical weld section
  def find_vertical_points(pointintersect, l1delxunit, l1delyunit, l2delxunit, l2delyunit, offset, wd, heading1, heading3):
  
    # find right side stuff
    # find the point in 3d space that is .375 up and .375 over
    x = pointintersect[0] + l1delxunit * offset
    y = pointintersect[1] + l1delyunit * offset
    z = pointintersect[2] + offset
    # find rxryrz
    rxryrz = convert_heading_to_axang_preheatup(heading1)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    path2r1 = p[x, y, z, rx, ry, rz]
    path2r2 = p[x, y, z + wd, rx, ry, rz]
  
    # find left side
    # find the point in 3d space that is .375 up and .375 over
    x = pointintersect[0] + l2delxunit * offset
    y = pointintersect[1] + l2delyunit * offset
    z = pointintersect[2] + offset
    # find rxryrz
    rxryrz = convert_heading_to_axang_preheatup(heading3)
    rx = rxryrz[0]
    ry = rxryrz[1]
    rz = rxryrz[2]
    path2l1 = p[x, y, z, rx, ry, rz]
    path2l2 = p[x, y, z + wd, rx, ry, rz]
  
    ret = struct(path2r1=path2r1, path2r2=path2r2, path2l1=path2l1, path2l2=path2l2)
    return ret
  end
  
  # this function converts a unit vector to its heading angle ccw from x+ axis
  # takes uvx and uvy
  # returns heading in radians
  def convert_uv_to_heading(uvx, uvy):
    baseang = atan(uvy/uvx)
    if uvx < 0:
      ang = baseang + pi
    elif uvy < 0:
      ang = baseang + pi * 2
    else:
      ang = baseang
    end
    return ang
  end
  
  # this function finds the equation of a line, perpendicular to a given line, and going through a given point
  # takes 3 arguments: m (the original line's slope), x (point's x coord), y (point's y coord). the b of the original line is not needed
  # returns a list of [m,b] (the slope and intercept of the new line)
  def find_perpendicular_line(origm, x, y):
    m = (1/origm) * -1
    b = y - m*x
    ret = [m, b]
    return ret
  end
  
  # this function finds the intersection point between two lines in the xy plane
  # takes 4 arguments: m1, b1, m2, b2
  # returns a list of [x,y] (the point of intersection)
  def find_intersection(m1, b1, m2, b2):
    # m1x+b1 = m2x+b2
    # m1x - m2x = b2 - b1
    # x = (b2-b1) / (m1-m2)
    x = (b2-b1) / (m1-m2)
    y = m1 * x + b1
    ret = [x, y]
    return ret
  end
  
  # this function finds the distance between 2 points in 3d space
  # it takes 6 arguments: x1, y1, z1, x2, y2, z2
  # it returns a distance
  def distance_between(x1, y1, z1, x2, y2, z2):
    distsquared = (x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)+(z2-z1)*(z2-z1)
    dist = sqrt(distsquared)
    return dist
  end
  
  # this function takes a point, a unit vector, and a distance, and adds the distance to the point in the direction of the unit vector (3d space)
  # it returns a point as a list of coordinates
  def add_vectordistance_to_point(xi, yi, zi, uvx, uvy, uvz, delta):
    xf = xi + uvx * delta
    yf = yi + uvy * delta
    zf = zi + uvz * delta
    ret = [xf, yf, zf]
    return ret
  end
  
  # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
  # this will point the gun in this heading with the bottom side of the gun facing up.
  # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
  def convert_heading_to_axang(heading):
   axisxraw = -1 * sin(heading)
   axisyraw = cos(heading) + 1
   axiszraw = sin(heading)
  
   magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
  
   axisxunit = axisxraw / magnitude
   axisyunit = axisyraw / magnitude
   axiszunit = axiszraw / magnitude
  
   angle = acos( (cos(heading) - 1) / 2 )
  
   rxout = axisxunit * angle
   ryout = axisyunit * angle
   rzout = axiszunit * angle
  
   return [rxout, ryout, rzout]
  end
  
  # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
  # this will point the gun in this heading with the preheat side of the gun tip facing up. Used for welding in a vertical path.
  # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
  def convert_heading_to_axang_preheatup(heading):
   axisxraw = -sin(heading) + 1
   axisyraw = cos(heading)
   axiszraw = cos(heading)
  
   magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
  
   axisxunit = axisxraw / magnitude
   axisyunit = axisyraw / magnitude
   axiszunit = axiszraw / magnitude
  
   angle = acos( (-sin(heading) - 1) / 2 )
  
   rxout = axisxunit * angle
   ryout = axisyunit * angle
   rzout = axiszunit * angle
  
   return [rxout, ryout, rzout]
  end
  
  # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
  # this will point the gun in this heading with the preheat side of the gun tip facing down. Used for welding in a vertical path downwards.
  # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
  def convert_heading_to_axang_preheatdown(heading):
   axisxraw = -sin(heading) - 1
   axisyraw = cos(heading)
   axiszraw = -cos(heading)
  
   magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
  
   axisxunit = axisxraw / magnitude
   axisyunit = axisyraw / magnitude
   axiszunit = axiszraw / magnitude
  
   angle = acos( (sin(heading) - 1) / 2 )
  
   rxout = axisxunit * angle
   ryout = axisyunit * angle
   rzout = axiszunit * angle
  
   return [rxout, ryout, rzout]
  end
  
  # this function converts a heading (ccw radians from the positive x axis) into rxryrz to be put into a point p[]
  # this will point the gun in this heading with the preheat side of the gun tip facing right. Used for welding counterclockwise around the box.
  # the values used in this program were calculated by doing rotation matrix math in the file on WI-CALVINB10 C. Documents. Theory for converting rotations into axis angle representations
  def convert_heading_to_axang_ccw(heading):
   axisxraw = -sin(heading)
   axisyraw = cos(heading) - 1
   axiszraw = -sin(heading)
  
   magnitude = sqrt(axisxraw*axisxraw + axisyraw*axisyraw + axiszraw*axiszraw)
  
   axisxunit = axisxraw / magnitude
   axisyunit = axisyraw / magnitude
   axiszunit = axiszraw / magnitude
  
   angle = acos( (-cos(heading) - 1) / 2 )
  
   rxout = axisxunit * angle
   ryout = axisyunit * angle
   rzout = axiszunit * angle
  
   return [rxout, ryout, rzout]
  end
  
  # this function is for getting the points along the path of the corner homing 45
  # point0 is the point where they touched
  def get_corner_homing_45_pathpoints(point0):
    p0x = point0[0]
    p0y = point0[1]
    p0z = point0[2]
    p0rx = point0[3]
    p0ry = point0[4]
    p0rz = point0[5]
  
    #constants
    #distances of how far away from point the touchpoints are
    d0 = 0.15 # how far from the box to retreat and approach
    d1 = 0.05
    d2 = 0.2
    sqrt2 = 0.707106781
  
    ph1 = p[p0x + d0, p0y, p0z + .05, p0rx, p0ry, p0rz] #approach point for turn
  
    ph2 = p[p0x+d0-d0*sqrt2-sqrt2*d1, p0y+d0*sqrt2+sqrt2*d1, p0z+.05, .445, -1.562, .483]
    ph3 = p[p0x+d0-d0*sqrt2-sqrt2*d2, p0y+d0*sqrt2+sqrt2*d2, p0z+.05, .445, -1.562, .483]
    ph4 = p[p0x+d0-d0*sqrt2-sqrt2*d1, p0y-d0*sqrt2-sqrt2*d1, p0z+.05, 1.699, 3.576, 1.841]
    ph5 = p[p0x+d0-d0*sqrt2-sqrt2*d2, p0y-d0*sqrt2-sqrt2*d2, p0z+.05, 1.699, 3.576, 1.841]
  
    # go back to ph1
    ph6 = p[p0x + .05, p0y, p0z -.05, 0, 0, 0] # approach point for under turn
    # moveL from ph1 to ph6
    ph7 = p[p0x-.05, p0y, p0z-.05, 0, 0, 0]
    ret = struct(ph1=ph1, ph2=ph2, ph3=ph3, ph4=ph4, ph5=ph5, ph6=ph6, ph7=ph7)
    return ret
  end
  $ 16 "pathturn≔main_calculate_left(p11,p12,p21,p22,p3)"
  global pathturn=main_calculate_left(p11,p12,p21,p22,p3)
  $ 18 "Call move_path_3left"
  move_path_3left()
  $ 19 "Home"
  movej([-3.5235366372186707, -1.9259070680664099, 2.3525050044875555, 0.20454112128959331, -0.22302944588515938, -0.6277049025321748], a=1.3962634015954636, v=1.0471975511965976)
end
