#rot_speed=0.1
#current_pose=get_actual_tcp_pose()
#time_int = 5
#target_pose=pose_trans(current_pose, p[0,0,0,0,0,rot_speed*time_int])
#speedl(pose_sub(target_pose, current_pose), rot_speed, time_int)

#get the headings and compare
#current heading
heading1=path1[9]
#destination heading
heading3 = path1[11]
headingdelta = heading3 - heading1
time_int = 3 #const
rot_speed = headingdelta/time_int 

speedl([0,0,0,0,0,rot_speed],0.5,time_int)