# this script tests welding path with a 90 degree turn

pi = 3.1415926535

p1 = p[-.80,.9,0,pi/2,0,0]
p2 = p[p1[0]+0.1,p1[1],p1[2],pi/2,0,0]
p2 = 

movej(pointapproach1, a=1.2, v=0.25)

movel(pointapproach2, a=1.2, v=0.25)

movel(point1, a=1.2, v=0.25)

movel(point2, a=1.2, v=0.25)

movel(point3, a=1.2, v=0.25)

movel(point4, a=1.2, v=0.25)

movel(pointapproach3, a=1.2, v=0.25)

movel(pointapproach1, a=1.2, v=0.25)